### ISSUE TITLE
Collector for tcp and udp stats?

### ISSUE THREAD

**Issue by brharrington** [intelsdi-x/snap#1003]
We are investigating a switch from snmp to snap for collecting basic system stats. Looking through the current collectors in the plugin catalog, I didn't see any that provide tcp or udp stats. Is there an existing or any planned work for a collector that would provide tcp and udp level networking stats? Something similar to what is available via:

http://net-snmp.sourceforge.net/docs/mibs/tcp.html
http://net-snmp.sourceforge.net/docs/mibs/udp.html

**Comment by lynxbat** [comment]
@brharrington We actually just completed a design spike on an SNMP plugin design out of an ask of our Networking group. Would you be willing to review the approach and comment? I can ask the team to post as an RFC.

We could also use some help implementing it in the short term since we don't think we can get to it for a month or so.

**Comment by brharrington** [comment]
> Would you be willing to review the approach and comment?

Sure. 

> We could also use some help implementing it in the short term since we don't think we can get to it for a month or so.

I can potentially help, but it will depend a bit on the scope and how some of our priorities shape up for Q3.

**Comment by katarzyna-z** [comment]
@brharrington  You can read the RFC for SNMP plugin, see #1010.

**Comment by mjbrender** [comment]
Hey @brharrington, we launched the SNMP plugin recently: https://github.com/intelsdi-x/snap-plugin-collector-snmp

Take a look around it and let me know if you think it covers your wants on this issue. 👌

**Comment by katarzyna-z** [comment]
The SNMP plugin is available and it has been added to plugin catalog so I'm closing this issue.
