### ISSUE TITLE
Need example tasks for other schedule types

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#1007]
There should be more example tasks that deal with other schedule types [here](https://github.com/intelsdi-x/snap/tree/master/examples/tasks). Right now all the examples deal with simple schedule only.

**Comment by mbbroberg** [comment]
As a group we've decided to get away from lots of example files in this repo toward documenting behavior and leaving it to plugins to show off any recommended features. Given that [the different schedule types have examples here](https://github.com/intelsdi-x/snap/blob/master/docs/TASKS.md#schedule), I'm going to close this one.
