### ISSUE TITLE
RFC - snap SNMP collector plugin

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#1010]
It describes concept of snap SNMP collector plugin.
## Use Case
As a snap user I want to collect metrics from network devices using Simple Network Management Protocol (SNMP).

## Desired features
- Support for SNMP v1, SNMP v2c, and SNMP v3.
- Metrics defined by the user (e.g. metric name, OID).
- Configurable SNMP hosts (user can define from which host metrics are collected and can configure host parameters).
- Querying one value or multiple values:
	 - for multiple values -  the OIDs are queried using the GETNEXT SNMP command until the subtree is left,
	 - for one value - the OIDs are queried using the GET SNMP command.
- Defining prefix and suffix for metric name. Prefix or suffix can be received through SNMP request or from string parameter in configuration.
- Defining  'scale' parameter to multiply value of numeric metric.
- Defining 'shift' parameter to add specific value to numeric metric.
- Collecting data in different data types (e.g. string, int, uint, float64).

## Architecture
Polling SNMP agent using SNMP requests - GET, (GETNEXT). Traps - not supported.

## Configuration

SNMP plugin is configured through snap's global config, plugin configuration file (setfile), and config section in task manifest.

### snap's global Config
"snmp" section should be added to "collector" section in snap's global config 
 "setfile"  - path to snmp plugin configuration file (path to setfile)

### Plugin configuration file (setfile)

Setfile contains JSON structure which is used to define metrics. Metric is defined as JSON object in following format:
```
"<metric_name>": {
      "OID": "<numeric_object_identifier>",
      "mode": "<metric_mode>",
      "prefix": {
        "source": "<prefix_source>",
        "string": "<prefix>"
      },
      "suffix": {
        "source": "<suffix_source>",
        "string": "<OID_to_get_suffix>"
      },
      "scale": <scale_value>,
      "shift": <shift_value>,
      "unit": "<unit>",
      "description": "<description>"
    }
```

Exemplary metric definition:
```
  "__metric1__": {
      "OID": ".1.3.6.1.2.1.1.9.1.3",
      "mode": "multiple",
      "prefix": {
        "source": "snmp",
        "OID": ".1.3.6.1.2.1.1.9.1.3"
      },
      "suffix": {
        "source": "snmp",
        "OID": ".1.3.6.1.2.1.1.9.1.3"
      },
      "scale": 1.25,
      "shift": 2,
      "unit": "unit",
      "description": "description"
    },
 "__metric2__": {
      "OID": ".1.3.6.1.2.1.1.9.1.3.1",
      "mode": "single",
      "prefix": {
        "source": "snmp",
        "OID": ".1.3.6.1.2.1.1.9.1.3.1"
      },
      "suffix": {
        "source": "snmp",
        "OID": ".1.3.6.1.2.1.1.9.1.3.1"
      },
      "scale": 1.25,
      "shift": 2,
      "unit": "unit",
      "description": "description"
    },
 "__metric3__": {
      "OID": ".1.3.6.1.2.1.1.9.1.3.1",
      "mode": "single",
      "prefix": {
        "source": "string",
        "string": "prefix"
      },
      "suffix": {
        "source": "string",
        "string": "suffix"
      },
      "scale": 1.25,
      "shift": 2,
      "unit": "unit",
      "description": "description"
    }

```
### Task manifest

SNMP host configuration is defined in task manifest, in the "config" section "/intel/snmp" 
section must be created and set of appropriate SNMP host parameters must be configured.
Exemplary task manifest:
```
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "120s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/snmp/*": {}
           },
            "config": {
                "/intel/snmp": {
                    "snmp_host_name": "snmp_host",
                    "snmp_host_address": "127.0.0.1",
                    "user_name": "name",
                    "security_level ": "authPriv",
                    "auth_protocol": "MD5",
                    "auth_passphrase": "password",
                    "privacy_protocol": "DES",
                    "privacy_passphrase": "password",
                    "network" : "udp",
                    "retries" : 3,
                    "timeout" : 1
                }
            },
            "process": null,
            "publish": [
                {
                    "plugin_name": "file",
                    "config": {
                        "file": "/tmp/published.txt"
                    }
                }
            ]
        }
    }
}
```

## Namespaces and tags for SNMP plugin

Metric catalog:
- specific: ``/intel/snmp/<prefix><metric_name><suffix>/value``
- dynamic : ``/intel/snmp/*/value``     

Exemplary namespaces:
``/intel/snmp/metric0/value``
``/intel/snmp/metric1/value``

Tags:
 - ``OID`` -  numeric object identifier which is used to read  metric                                                                    
 - ``SNMP_HOST_NAME`` - name given by the user for SNMP host
 - ``SNMP_HOST_ADDRESS`` - IP address or host name with port number of SNMP host

**Comment by marcin-krolik** [comment]
@katarzyna-z this looks great! :+1:

**Comment by lynxbat** [comment]
👍

**Comment by ss7pro** [comment]
It would be nice if we can implement some kind of logic which is important for operators to ensure:

- there's no need to deploy separate instance for each hosts we're collecting data from
- collector will adjust number of running threads to ensure that it will keep up with collecting each metric in a provided interval. This means that if we're monitoring 20k metrics with 5s interval it will spawn a separate thread (corner case) for each metric if data fetch&store takes more than 5 seconds. On the other hand when data fetch&store works smoothly it will try to keep number of threads as low as possible.
- collector process should be also having a cup on a maximum memory usage (all threads together should not consume more than configured).
- it would be an also a nice feature if we can make collector to distribute it's tasks across multiple machines.
- SNMP is usually over UDP so it's nice to have configurable: timeout on missing replay, retry number replay timeout, interval between retires (this should be growing on each following retry). Retry feature is nice on a metrics which we don't want to monitor frequently but want to ensure that we have at least one during interval.

**Comment by katarzyna-z** [comment]
> •SNMP is usually over UDP so it's nice to have configurable: timeout on missing replay, retry number replay timeout, interval between retires (this should be growing on each following retry). Retry feature is nice on a metrics which we don't want to monitor frequently but want to ensure that we have at least one during interval.

Configurable number of retries and timeout were taken into account,  I forgot to add this. I corrected my first comment. I added to host configuration following parameters: 
- network - to configure network, e.g udp, tcp, 
- retries - number of connection retries, 
- timeout - connection timeout in seconds.

**Comment by brharrington** [comment]
> Support for SNMP v1, SNMP v2, and SNMP v3.

There are several variants of v2, does this mean v2c?

How important is it to support v1? Dropping v1 support would allow use of bulkget.

> Defining prefix and suffix for metric name. Prefix or suffix can be received through SNMP request or from string parameter in configuration.

How would this behave with respect to naming restrictions? For example, using the OID from your example I get back the string:

```
"The MIB for Message Processing and Dispatching."
```

Which is not a valid path element.

The example uses an snmp source, I'm assuming the other option would be something like:

```json
  "prefix": {
    "source": "string",
    "string": "/foo/bar"
  },
```

> Defining 'scale' parameter to multiply value of numeric metric.
> Defining 'shift' parameter to add specific value to numeric metric.

Why shift for adding a value? What is the precedence if both are specified?

> "setfile" - path to snmp plugin configuration file (path to setfile)

For my use-cases I think this will work fine. Out of curiosity though, is there another collector that uses a similar pattern right now? One down side to this is that the set of OIDs queried could not be changed via the REST API when defining a task. The user would have to ensure that a local file was available with the right definitions. Is there a standard location for those sort of configuration files? Is there an easy way for a user of the REST API to discover the available set?

> Exemplary metric definition:

In this example, what would be the `metric_name`? I'm not sure about the specification for multiple get, I'll have to work through a concrete example.

> specific: /intel/snmp/<prefix><metric_name><suffix>/value

To check my understanding, specific would only be ones defined with `mode=single` and a string prefix and suffix. Is that correct?

**Comment by katarzyna-z** [comment]
@brharrington Thank you for your response. I'm starting responding from the easier questions/doubts.

> There are several variants of v2, does this mean v2c?

SNMP v2 means SNMP v2c (I corrected this in RFC)

> How would this behave with respect to naming restrictions? 

Not allowed character in prefix or suffix (received through SNMP request or configured by the user) will be replaced with '_' (see [snap-plugin-utilities](https://github.com/intelsdi-x/snap-plugin-utilities#ns-package) and pay attention to [ReplaceNotAllowedCharsInNamespacePart](https://github.com/intelsdi-x/snap-plugin-utilities/blob/master/ns/namespace.go#L173). This function will be used in plugin implementation and user will be notified about changes in prefix and suffix.

> The example uses an snmp source, I'm assuming the other option would be something like:
  "prefix": {
    "source": "string",
    "string": "/foo/bar"
  },

You correctly understood the configuration options for prefix source set to "string" but '/' will be replaced with '_'

> Why shift for adding a value? What is the precedence if both are specified?

I'm showing this using simple equation:
new_metric_value =  numeric_metric_value * scale + shift 
So firstly 'scale' is in use then 'shift'.

> 
For my use-cases I think this will work fine. Out of curiosity though, is there another collector that uses a similar pattern right now?

There is another plugin that uses a similar pattern, please see [snap-plugin-collector-dbi](https://github.com/intelsdi-x/snap-plugin-collector-dbi)

> 
In this example, what would be the  metric_name ? I'm not sure about the specification for multiple get, I'll have to work through a concrete example.

'multiple' mode is to read all elements from specified node 
In this example for multiple mode we will have following set of metrics:

```
/intel/snmp/the_mib_for_message_processing_and_dispatching__metric1__the_mib_for_message_processing_and_dispatching/value
/intel/snmp/the_management_information_definitions_for_the_snmp_user-based_security_model__metric1__the_management_information_definitions_for_the_snmp_user-based_security_model/value
/intel/snmp/the_snmp_management_architecture_mib__metric1__the_snmp_management_architecture_mib/value
/intel/snmp/the_mib_module_for_snmpv2_entities__metric1__the_mib_module_for_snmpv2_entities/value
/intel/snmp/the_mib_module_for_managing_tcp_implementations__metric1__the_mib_module_for_managing_tcp_implementations/value
/intel/snmp/the_mib_module_for_managing_ip_and_icmp_implementations__metric1__the_mib_module_for_managing_ip_and_icmp_implementations/value
/intel/snmp/the_mib_module_for_managing_udp_implementations__metric1__the_mib_module_for_managing_udp_implementations/value
/intel/snmp/view-based_access_control_model_for_snmp__metric1__view-based_access_control_model_for_snmp/value 
/intel/snmp/the_mib_modules_for_managing_snmp_notification_plus_filtering__metric1__the_mib_modules_for_managing_snmp_notification_plus_filtering/value
/intel/snmp/the_mib_module_for_logging_snmp_notifications__metric1__the_mib_module_for_logging_snmp_notifications/value

**Comment by brharrington** [comment]
Does everything need to be flattened into the same namespace element? When I first read the spec, I thought I could configure something like:

```json
"loadavg1": {
      "OID": ".1.3.6.1.4.1.2021.10.1.5.1",
      "mode": "single",
      "prefix": {
        "source": "string",
        "string": "load"
      },
      "suffix": {
        "source": "string",
        "string": null
      },
      "scale": 0.01,
      "description": "The number of jobs in the run queue (state R) or waiting for disk I/O (state D) averaged over 1 minute."
    },
"loadavg5": {...},
"loadavg15": {...},
```

And get a set of metrics like:

```
/intel/snmp/load/loadavg1
/intel/snmp/load/loadavg5
/intel/snmp/load/loadavg15
```

So I could make the output similar to [other plugins](https://github.com/intelsdi-x/snap-plugin-collector-load#collected-metrics) and work quite naturally with things like wildcards (`/intel/snmp/load/*`).

**Comment by lynxbat** [comment]
+1 on the using the namespace element to make the queries more powerful.

**Comment by brharrington** [comment]
As a example of using multiple, I was thinking about getting metrics per network interface.

http://www.net-snmp.org/docs/mibs/interfaces.html

Ideally I would like to get these mapped in as metrics like:

```
/intel/snmp/net/if/[interface]/mtu
/intel/snmp/net/if/[interface]/in_octets
/intel/snmp/net/if/[interface]/out_octets
...
```

What about a config like:

```json
[
  {
    "mode": "single",
    "namespace": [
      {"source": "string", "string": "load"},
      {"source": "string", "string": "loadavg1"}
    ],
    "OID": ".1.3.6.1.4.1.2021.10.1.5.1",
    "scale": 0.01,
    "shift": 0,
    "unit": "unit",
    "description": "description"
  },
  {
    "mode": "table",
    "namespace": [
      {"source": "string", "string": "net"},
      {"source": "string", "string": "if"},
      {"source": "snmp", "name": "interface", "OID": ".1.3.6.1.2.1.2.2.1.2"},
      {"source": "string", "string": "in_octets"}
    ],
    "OID": ".1.3.6.1.2.1.2.2.1.10",
    "scale": 1.0,
    "shift": 0,
    "unit": "unit",
    "description": "description"
  },
  {
    "mode": "walk",
    "namespace": [
      {"source": "string", "string": "load2"},
      {"source": "oid-translate", "index": 9}
    ],
    "OID": ".1.3.6.1.4.1.2021.10.1.5",
    "scale": 0.01,
    "shift": 0,
    "unit": "unit",
    "description": "description"
  }
]
```

So for this example, the set of metrics would be:

* Static
    * `/intel/snmp/load/loadavg1`
* Dynamic
    * `/intel/snmp/load2/[translation]`, for example:
        * `/intel/snmp/load2/laLoadInt_1`
        * `/intel/snmp/load2/laLoadInt_2`
        * `/intel/snmp/load2/laLoadInt_3`
    * `/intel/snmp/net/if/[interface]/in_octets`, for example:
        * `/intel/snmp/net/if/eth0/in_octets`

With this scheme there would be three modes:

* `single`: get the value for a particular oid
* `walk`: similar to `multiple` in the original proposal. Walks a tree to make it easy to get a comprehensive listing of data from snmp. For this proposal I'm suggesting a subset (use index=0 for the full path) of the translated oid for the name.
* `table`: like `walk`, but expects a table like those used for load avg, network interfaces, disk stats, etc.  The OIDs used in either the namespace or value field would be a prefix of everything but the row index. This would allow tables to be mapped in with a more idiomatic path structure if desired. See network interfaces example above.

**Comment by katarzyna-z** [comment]
@brharrington Thank you for your proposals. I've analyzed it.

I think that you propose great solution to configure namespaces in plugin configuration file. I want to change "prefix" and "suffix" into your proposition:
```
"namespace": [
      {"source": "string", "string": "net"},
      {"source": "string", "string": "if"},
      {"source": "snmp", "name": "interface", "OID": ".1.3.6.1.2.1.2.2.1.2"},
      {"source": "string", "string": "in_octets"}
    ],
```
and then also build namespaces as you showed.

I think that is good to introduce a new source  {"source": "oid-translate", "index": 9} but I would like to add this in the second version of plugin implementation . To my knowledge, browsing of MIBs is required to translate of OIDs, I didn't found any go library to do it so there is a need to do it on our own. Probably it will be better to provide users the possibility to collect metrics using SNMP and then introduced this enhancement.

In the first version of plugin, I want to add the another source of namespace part - "index" and give the user possibility to use one part of OID as namespace part, exemplary:

Having this MIB tree:
```
laEntry 1.3.6.1.4.1.2021.10.1
laIndex 1.3.6.1.4.1.2021.10.1.1
laErrorFlag 1.3.6.1.4.1.2021.10.1.100
laErrMessage 1.3.6.1.4.1.2021.10.1.101
laNames 1.3.6.1.4.1.2021.10.1.2
laLoad 1.3.6.1.4.1.2021.10.1.3
laConfig 1.3.6.1.4.1.2021.10.1.4
laLoadInt 1.3.6.1.4.1.2021.10.1.5
laLoadFloat 1.3.6.1.4.1.2021.10.1.6
```
we could create the following configuration:
```
 {
    "mode": "multiple",
    "namespace": [
      {"source": "string", "string": "load2"},
      {"source": "string", "string": "laEntry"},
      {"source": "index", "oid_part": 9}
      {"source": "string", "string": "value"},
    ],
    "OID": "1.3.6.1.4.1.2021.10.1",
    "scale": 0.01,
    "shift": 0,
    "unit": "unit",
    "description": "description"
  }
```
Metric catalog:
``/intel/snmp/load2/laEntry/*/value``

Collected metrics:

```
namespace: /intel/snmp/load2/laEntry/1/value	tags: OID:".1.3.6.1.4.1.2021.10.1.1" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/100/value  tags: OID:".1.3.6.1.4.1.2021.10.1.100" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/101/value  tags: OID:".1.3.6.1.4.1.2021.10.1.101" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/2/value    tags: OID:".1.3.6.1.4.1.2021.10.1.2" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/3/value    tags: OID:".1.3.6.1.4.1.2021.10.1.3" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/4/value    tags: OID:".1.3.6.1.4.1.2021.10.1.4" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/5/value    tags: OID:".1.3.6.1.4.1.2021.10.1.5" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/6/value    tags: OID:".1.3.6.1.4.1.2021.10.1.6" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
```

In this example OID in configuration of metric indicates the node from which metrics are read. There is a need to have non-dynamic element at the end of namespace (this should be check during validation of plugin configuration) so I added this ```{"source": "string", "string": "value"}```.


In the second version of plugin (with translation of OIDs) we could create the following configuration:
```
 {
    "mode": "multiple",
    "namespace": [
      {"source": "string", "string": "load2"},
      {"source": "string", "string": "laEntry"},
      {"source": "oid-translate", "index": 9}
      {"source": "string", "string": "value"},
    ],
    "OID": "1.3.6.1.4.1.2021.10.1",
    "scale": 0.01,
    "shift": 0,
    "unit": "unit",
    "description": "description"
  }
```
Metric catalog:
``/intel/snmp/load2/laEntry/*/value``

Collected metrics:

```
namespace: /intel/snmp/load2/laEntry/laIndex/value	tags: OID:".1.3.6.1.4.1.2021.10.1.1" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laErrorFlag/value  tags: OID:".1.3.6.1.4.1.2021.10.1.100" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laErrMessage/value  tags: OID:".1.3.6.1.4.1.2021.10.1.101" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laNames/value    tags: OID:".1.3.6.1.4.1.2021.10.1.2" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laLoad/value    tags: OID:".1.3.6.1.4.1.2021.10.1.3" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laConfig/value    tags: OID:".1.3.6.1.4.1.2021.10.1.4" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laLoadInt/value    tags: OID:".1.3.6.1.4.1.2021.10.1.5" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
namespace: /intel/snmp/load2/laEntry/laLoadFloat/value    tags: OID:".1.3.6.1.4.1.2021.10.1.6" SNMP_HOST_NAME:"<host_name>"  SNMP_HOST_ADDRESS: "<address>"
```

I have difficulties with understanding your proposition of modes (``walk``, ``table``). Could you give the MIB tree for examples of new modes and show ``table`` mode with two namespaces? I think that with this information it will be easier to understand.

**Comment by brharrington** [comment]
> I have difficulties with understanding your proposition of modes (walk, table). Could you give the MIB tree for examples of new modes and show table mode with two namespaces? I think that with this information it will be easier to understand.

The `walk` I think is the same as `multiple` in the original proposal. I changed the name because `table` would also have multiple results and to me it was similar in behavior to the `snmpwalk` command. That said I don't care too much about what the modes are called. For `table`, here are some examples:

### Network Interfaces

http://www.net-snmp.org/docs/mibs/interfaces.html

The OID consists of:

```
.1.3.6.1.2.1.2.2.1.{COLUMN}.{ROW}
```

So in this case I wanted to be able to pull the value for a particular column (2 or ifDescr) that has the human readable name of the interface and include that as the dynamic part of the metric namespace element. I left of the row for the OIDs in the config with the intent that `table` mode would loop over the rows of the table.

Config element would look something like:

```
{
  "mode": "table",
  "namespace": [
    {"source": "string", "string": "net"},
    {"source": "string", "string": "if"},
    {"source": "snmp", "name": "interface", "OID": ".1.3.6.1.2.1.2.2.1.2"},
    {"source": "string", "string": "in_octets"}
  ],
  "OID": ".1.3.6.1.2.1.2.2.1.10",
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description"
},
```

Though maybe it could be simplified to reduce the repetition of the OID prefix. Possibly:

```
{
  "mode": "table",
  "namespace": [
    {"source": "string", "string": "net"},
    {"source": "string", "string": "if"},
    {"source": "column", "name": "interface", "column": "2"},
    {"source": "string", "string": "in_octets"}
  ],
  "OID": ".1.3.6.1.2.1.2.2.1",
  “column”: 10,
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description"
},
```

Example output of walking the tree:

```
$ snmpwalk -On -v 2c -c public localhost .1.3.6.1.2.1.2
.1.3.6.1.2.1.2.1.0 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.2.1 = STRING: lo
.1.3.6.1.2.1.2.2.1.2.2 = STRING: eth0
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: softwareLoopback(24)
.1.3.6.1.2.1.2.2.1.3.2 = INTEGER: ethernetCsmacd(6)
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 65536
.1.3.6.1.2.1.2.2.1.4.2 = INTEGER: 9001
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 10000000
.1.3.6.1.2.1.2.2.1.5.2 = Gauge32: 4294967295
.1.3.6.1.2.1.2.2.1.6.1 = STRING: 
.1.3.6.1.2.1.2.2.1.6.2 = STRING: 
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: up(1)
.1.3.6.1.2.1.2.2.1.7.2 = INTEGER: up(1)
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: up(1)
.1.3.6.1.2.1.2.2.1.8.2 = INTEGER: up(1)
.1.3.6.1.2.1.2.2.1.9.1 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.9.2 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 2426340104
.1.3.6.1.2.1.2.2.1.10.2 = Counter32: 2116292856
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 10366434
.1.3.6.1.2.1.2.2.1.11.2 = Counter32: 80096532
.1.3.6.1.2.1.2.2.1.12.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.12.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.13.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.14.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.15.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 2426340104
.1.3.6.1.2.1.2.2.1.16.2 = Counter32: 3087761414
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 10366434
.1.3.6.1.2.1.2.2.1.17.2 = Counter32: 23902595
.1.3.6.1.2.1.2.2.1.18.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.18.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.21.1 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.21.2 = Gauge32: 0
.1.3.6.1.2.1.2.2.1.22.1 = OID: .0.0
.1.3.6.1.2.1.2.2.1.22.2 = OID: .0.0
```

### Disk Table

http://www.net-snmp.org/docs/mibs/ucdavis.html#dskTable

OID format:

```
.1.3.6.1.4.1.2021.9.1.{COLUMN}.{ROW}
```

Here column 2 (dskPath) and column 3 (dskDevice) might be useful as dynamic elements in the metric namespace. Configuration like:

```
{
  "mode": "table",
  "namespace": [
    {"source": "string", "string": “disk”},
    {"source": “column”, "name": “path”, “column”: "2"},
    {"source": “column”, "name": “device”, “column”: “3”},
    {"source": "string", "string": “percent_used”}
  ],
  "OID": ".1.3.6.1.4.1.2021.9.1",
  “column”: 9,
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description"
},
```

Sample input restricted to two rows:

```
$ snmpwalk -On -v 2c -c public localhost .1.3.6.1.4.1.2021.9 | awk '$1 ~ /.*\.[12]$/ {print $0}'
.1.3.6.1.4.1.2021.9.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.2021.9.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.2021.9.1.2.1 = STRING: /
.1.3.6.1.4.1.2021.9.1.2.2 = STRING: /sys/fs/cgroup
.1.3.6.1.4.1.2021.9.1.3.1 = STRING: /dev/xvda
.1.3.6.1.4.1.2021.9.1.3.2 = STRING: none
.1.3.6.1.4.1.2021.9.1.4.1 = INTEGER: -1
.1.3.6.1.4.1.2021.9.1.4.2 = INTEGER: -1
.1.3.6.1.4.1.2021.9.1.5.1 = INTEGER: 10
.1.3.6.1.4.1.2021.9.1.5.2 = INTEGER: 10
.1.3.6.1.4.1.2021.9.1.6.1 = INTEGER: 10288440
.1.3.6.1.4.1.2021.9.1.6.2 = INTEGER: 4
.1.3.6.1.4.1.2021.9.1.7.1 = INTEGER: 5959052
.1.3.6.1.4.1.2021.9.1.7.2 = INTEGER: 4
.1.3.6.1.4.1.2021.9.1.8.1 = INTEGER: 3788828
.1.3.6.1.4.1.2021.9.1.8.2 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.9.1 = INTEGER: 37
.1.3.6.1.4.1.2021.9.1.9.2 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.10.1 = INTEGER: 22
.1.3.6.1.4.1.2021.9.1.10.2 = INTEGER: 0
.1.3.6.1.4.1.2021.9.1.11.1 = Gauge32: 10288440
.1.3.6.1.4.1.2021.9.1.11.2 = Gauge32: 4
.1.3.6.1.4.1.2021.9.1.12.1 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.12.2 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.13.1 = Gauge32: 5959052
.1.3.6.1.4.1.2021.9.1.13.2 = Gauge32: 4
.1.3.6.1.4.1.2021.9.1.14.1 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.14.2 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.15.1 = Gauge32: 3788828
.1.3.6.1.4.1.2021.9.1.15.2 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.16.1 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.16.2 = Gauge32: 0
.1.3.6.1.4.1.2021.9.1.100.1 = INTEGER: noError(0)
.1.3.6.1.4.1.2021.9.1.100.2 = INTEGER: noError(0)
.1.3.6.1.4.1.2021.9.1.101.1 = STRING: 
.1.3.6.1.4.1.2021.9.1.101.2 = STRING:
```

### Disk IO

http://www.net-snmp.org/docs/mibs/ucdDiskIOMIB.html

OID format:

```
.1.3.6.1.4.1.2021.13.15.1.1.{COLUMN}.{ROW}
```

Here I would want column 2 (diskIODevice) to be in the metric namespace element because it is more accessible to a human. Sample config:

```
{
  "mode": "table",
  "namespace": [
    {"source": "string", "string": “diskio”},
    {"source": "column", "name": “device”, “column”: "2"},
    {"source": "string", "string": "bytes_read"}
  ],
  "OID": ".1.3.6.1.4.1.2021.13.15.1.1",
  “column”: 3,
  "scale": 1.0,
  "shift": 0,
  "unit": "unit",
  "description": "description"
},
```

Sample input restricted to two rows:

```
$ snmpwalk -On -v 2c -c public localhost .1.3.6.1.4.1.2021.13.15 | awk '$1 ~ /.*\.(25|26)$/ {print $0}'
.1.3.6.1.4.1.2021.13.15.1.1.1.25 = INTEGER: 25
.1.3.6.1.4.1.2021.13.15.1.1.1.26 = INTEGER: 26
.1.3.6.1.4.1.2021.13.15.1.1.2.25 = STRING: xvda
.1.3.6.1.4.1.2021.13.15.1.1.2.26 = STRING: xvdb
.1.3.6.1.4.1.2021.13.15.1.1.3.25 = Counter32: 287122432
.1.3.6.1.4.1.2021.13.15.1.1.3.26 = Counter32: 1661440
.1.3.6.1.4.1.2021.13.15.1.1.4.25 = Counter32: 3714703360
.1.3.6.1.4.1.2021.13.15.1.1.4.26 = Counter32: 970989056
.1.3.6.1.4.1.2021.13.15.1.1.5.25 = Counter32: 17552
.1.3.6.1.4.1.2021.13.15.1.1.5.26 = Counter32: 428
.1.3.6.1.4.1.2021.13.15.1.1.6.25 = Counter32: 373044
.1.3.6.1.4.1.2021.13.15.1.1.6.26 = Counter32: 313222
.1.3.6.1.4.1.2021.13.15.1.1.9.25 = INTEGER: 0
.1.3.6.1.4.1.2021.13.15.1.1.9.26 = INTEGER: 0
.1.3.6.1.4.1.2021.13.15.1.1.10.25 = INTEGER: 0
.1.3.6.1.4.1.2021.13.15.1.1.10.26 = INTEGER: 0
.1.3.6.1.4.1.2021.13.15.1.1.11.25 = INTEGER: 0
.1.3.6.1.4.1.2021.13.15.1.1.11.26 = INTEGER: 0
.1.3.6.1.4.1.2021.13.15.1.1.12.25 = Counter64: 287122432
.1.3.6.1.4.1.2021.13.15.1.1.12.26 = Counter64: 1661440
.1.3.6.1.4.1.2021.13.15.1.1.13.25 = Counter64: 3714703360
.1.3.6.1.4.1.2021.13.15.1.1.13.26 = Counter64: 35330727424
```

**Comment by brharrington** [comment]
> I think that is good to introduce a new source {"source": "oid-translate", "index": 9} but I would like to add this in the second version of plugin implementation .

No objections. The `single` and `table` modes would cover my use-cases.

> I think that is good to introduce a new source {"source": "oid-translate", "index": 9} but I would like to add this in the second version of plugin implementation .

That sounds fine. It makes it easier to loop over the table without needing an explicit config per column. I'll mention this is also an example where I would probably try to use the the `table` format for several reasons:

1. Most of our users are not familiar with snmp so for someone querying the snap API I would rather they didn't have to know about OIDs. Using the `table` pattern I could use `laName` column as the dynamic element so the user would have a more presentable view. Though admittedly the load avg table could also be done with `single` because I know the exact size in advance.
2. This mode loops over the tree applying the same conversion (scale and shift) to each value. The `table` mode allows me to have a config entry per column so I can tune the conversions. For example I would want to divide `laLoadInt` by 100 to get the value the user expects, but that isn't needed for `laLoadFloat`.
3. The `table` mode allows me to prune out unnecessary columns earlier. I probably wouldn't want to expose `laLoad`, `laLoadInt`, and `laLoadFloat` as they are redundant other than having different types.

**Comment by katarzyna-z** [comment]
@brharrington Thanks for examples, now I understand the ``table`` mode :)

**Comment by mjbrender** [comment]
Hey everyone, we launched the SNMP plugin: https://github.com/intelsdi-x/snap-plugin-collector-snmp

That brings this RFC to conclusion. Please open recommendations via issues on the plugin repo! 🐢
