### ISSUE TITLE
New version of grpc package is causing error during plugin compilation

### ISSUE THREAD

**Issue by mstachowski** [intelsdi-x/snap#1026]
New version of `grpc` has got `SupportPackageIsVersion3` constant instead of `SupportPackageIsVersion2` ([grpc documentation](https://godoc.org/google.golang.org/grpc#pkg-constants)). This situation is causing following error during compilation:

`
../go/src/github.com/intelsdi-x/snap/grpc/controlproxy/rpc/control.pb.go:393: undefined: grpc.SupportPackageIsVersion2
`

**Comment by elemoine** [comment]
How do you compile Snap? Did you just run `go get github.com/intelsdi-x/snap`?

This is issue is the same as https://github.com/intelsdi-x/snap/issues/994.

**Comment by mstachowski** [comment]
@elemoine I am cloning snap into gopath and there I am running `make build` and `make all`.

Issue #994 is the same as mine (I was looking for issues with grpc instead of looking for issues with building). In this case we can close this.

**Comment by elemoine** [comment]
> @elemoine I am cloning snap into gopath and there I am running make build and make all.

There's no `make build`. Do you mean `make deps`?

If you do clone Snap and run `make deps all` then it should work. Please confirm that you do get an error when you do that.
