### ISSUE TITLE
Running Snap error

### ISSUE THREAD

**Issue by candysmurf** [intelsdi-x/snap#1029]
The latest Snap is broken with this error when run it:

Step:
1. ./build/bin/snapd -l 1 -t 0
2. see log on the console:
       proto: duplicate proto type registered: rpc.CollectMetricsReply

It seems caused by this merge:  e68b1a3df159125502e44efbc007425a7138ea12.

**Comment by geauxvirtual** [comment]
That message is not from that commit or PR. This could be related to PR #1012 which added plugins being able to communicate over gPRC. @IRCody should be able to validate that.

**Comment by jcooklin** [comment]
☝️ I found this to be true.  It was introduced in #1012.
