### ISSUE TITLE
RFC: RPC Type, Content Types, and Client Libraries

### ISSUE THREAD

**Issue by danielscottt** [intelsdi-x/snap#1038]
# Overview
### RPC Type

When a plugin and `snapd` perform their initial handshake, the plugin must inform the daemon which form of RPC it uses: Gob or JSON-RPC. This is known through the `RPCType` key in a plugin's `Meta`.  JSON-RPC was introduced as a solution for polyglot plugins, however due to the current nature of Snap's pipeline, only Collectors may be written in languages other than Go.  This is because, before sending data to Processors or Publishers following collection, `snapd` encodes [everything as Gob](https://github.com/intelsdi-x/snap/blob/e68b1a3df159125502e44efbc007425a7138ea12/scheduler/job.go#L327).

With the landing of patch [#1012](https://github.com/intelsdi-x/snap/pull/1012), gRPC is also now supported as a communication protocol between `snapd` and its plugins. This RFC proposes the setting of a strict contract: _Only_ gRPC is supported.  This means the removal of JSON-RPC as well as Gob.  **Note: legacy plugins will continue to be supported for the time being.  They will be deprecated at a later date.**

The new gRPC API will be versioned, and we will guarantee no breaking changes within versions.
### Content Types

Content Types are, in a way, the edges to Snaps workflow graph. These content types were initially designed to be an opportunity for data to be encoded and decoded arbitrarily throughout Snap's pipeline. The benefit of this arbitrary encoding is that a successive series of plugins may modify the data model after the initial collection.  To achieve this, a plugin would need access directly to the encoded data.

This RFC proposes the removal of content-types, and their eventual replacement with a bool in `plugin.Meta`: `CustomPayload`.
### Client Libraries

When writing a Snap plugin in Go, a plugin author is provided with a plugin proxy, as well as an implementation for the helper functions required to implement the plugin's RPC interface.  The proxy also takes the RPC server's functions and wraps them around the plugin author's code; this way, a plugin author need only implement their business logic and is not required to take on the tedious task of starting a plugin, managing a server, or implementing functions such as `SetKey`, or `Ping`.

This RFC proposes that the Go plugin client library be removed from the main snap tree, and be reimplemented as a stand-alone library.  This solution can act not only as an prototype for client libraries in other languages, but will also delineate client libraries' histories from Snap's main source.  This separation allows a plugin author to vendor at the client library rather than needing to chase the fast-moving Snap source tree.

Like the gRPC API they support, these client libraries will be versioned accordingly with the API they support.
# Phases

To accomplish this, I propose its solution in phases.
### Phase 0: Pre-prep
- Add a deprecated warning to the master branch of Snap stating that both Content Types and RPC Type are being deprecated and will be replaced with protobuf and concrete types in a coming release.
- Create a new feature branch on `intelsdi-x/snap`.
### Phase 1: Implementation
- On new feature branch:
  - Remove `control/plugin` client library from snap tree.
  - Remove content types
  - Remove `RPCType`, version new protobuf RPC Server
  - Make use of gRPC's SSL features
    - Removes the need of `SetKey` from the RPC interface.
- Client Libraries
  - Go
  - C
  - C++
  - Python
### Phase 2: Release
- Tag (and branch?) current `master` denoting legacy RPC commit
- Merge feature branch into `master`
- Merge all plugin feature branches into master
- RFC for Custom Payloads
### Phase 3: Custom Payloads
- Custom Payload implementation
- Client Library updates for Custom Payloads
- Daemon's ability to switch on Client types

**Comment by ConnorDoyle** [comment]
@danielscottt could you add a note about planned compatibility guarantees? Could be something simple like "no breaking changes to the gRPC service protocol allowed within a major version series".

**Comment by danielscottt** [comment]
@ConnorDoyle ✔️

**Comment by IRCody** [comment]
Link: #1150.

**Comment by mbbroberg** [comment]
@intelsdi-x/snap-maintainers I think a lot of this work has been completed, albeit not exactly as described. I'm closing this one as a combo of duplicate/won't fix.

See: 
#1150 
#1296
