### ISSUE TITLE
Snap logs don't signal any startup

### ISSUE THREAD

**Issue by lynxbat** [intelsdi-x/snap#1045]
A default log level has no indication Snap knows it is running. It would be cool to have a text splash similar to common services like influx.

Example:

<img width="502" alt="screenshot 2016-06-30 14 37 45" src="https://cloud.githubusercontent.com/assets/1278669/16505086/3ad84f92-3ed0-11e6-948a-5512c6dd09b3.png">

**Comment by marea-cobb** [comment]
Any preference between displaying Snap or a turtle?
[ascii_snappy.docx](https://github.com/intelsdi-x/snap/files/488487/ascii_snappy.docx)
