### ISSUE TITLE
Plugin Load Error when loading snap-plugin-publisher-kafka

### ISSUE THREAD

**Issue by smartx-jshan** [intelsdi-x/snap#1057]
•OS version : Ubuntu 14.04.4
•Snap version: Snap v0.14-beta
•Environment details: Virtual Machine based on KVM

When loading snap-plugin-publisher-kafka, I see the error message as below.

$ snapd -t 0 -l 1
$ snapctl plugin load snap-plugin-publisher-kafka

![snap error](https://cloud.githubusercontent.com/assets/19390594/16679708/9e927396-4524-11e6-8914-9d33ebe601cd.png)

gob: name not registred for interface: "*cpolicy.ConfigPolicyNode"

However, when I use Snap v0.11-beta with kafka plugin, it works correctly.

**Comment by andrzej-k** [comment]
Hi @smartx-jshan - thanks for reporting this! 
That may be the issue with no updated Godeps - we'll investigate it further. Just to let you know, I've opened a new issue to capture this in snap-plugin-publisher-kafka repo, and will close this one.
