### ISSUE TITLE
Sectioning plugin catalog

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#1067]
With growing number of plugins of different types our Plugin Catalog may benefit from sectioning "Maintained plugins" in PLUGIN_CATALOG.md. How about creating a section for each plugin type, for example like below, as opposed to having all plugins on a single list?

## Maintained collector plugins
| Name  | Description | Link | Download |
| :---- | :---------- | :--- | :------- |
| CollectorPlugin| Plugin description | [snap-plugin-collector-apache](https://github.com/intelsdi-x/snap-plugin-collector-apache) | [Linux](https://s3-us-west-1.amazonaws.com/snap-plugins-linux-latest/snap-plugin-collector-apache)

## Maintained processor plugins
| Name  | Description | Link | Download |
| :---- | :---------- | :--- | :------- |
| ProcessorPlugin | Plugin description| [snap-plugin-collector-apache](https://github.com/intelsdi-x/snap-plugin-collector-apache) | [Linux](https://s3-us-west-1.amazonaws.com/snap-plugins-linux-latest/snap-plugin-collector-apache)

## Maintained publisher plugins
| Name  | Description | Link | Download |
| :---- | :---------- | :--- | :------- |
| PublisherPlugin | Plugin description| [snap-plugin-collector-apache](https://github.com/intelsdi-x/snap-plugin-collector-apache) | [Linux](https://s3-us-west-1.amazonaws.com/snap-plugins-linux-latest/snap-plugin-collector-apache)

**Comment by lynxbat** [comment]
Good idea.

We have a few things in flight for categorizing the quality, stability, and type of plugins including partners starting to host better catalogs (outside of github).

We will be posting our 1.0 plans soon and this will include that.

**Comment by mjbrender** [comment]
+1 to this being good @andrzej-k. Hey @nanliu, when we further discuss auto-generating this file, let's take this feature into account.
