### ISSUE TITLE
Latest snap plug-in package released is missing disk plug-in

### ISSUE THREAD

**Issue by juliasantos** [intelsdi-x/snap#1072]
I downloaded the lastest snap plug-in package and it appears to be missing the snap-plugin-collector-disk plug-in. This plug-in listed as "done" and the docs for it say it is in the latest release.

**Comment by thomastaylor312** [comment]
@nanliu Will this be added in to 0.15?

**Comment by nanliu** [comment]
Yes, this will be released in 0.15

**Comment by nanliu** [comment]
Plugin released in 0.15.
