### ISSUE TITLE
mock plugins not providing testing coverage for publishers

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#1079]
Note comment at the bottom of this Issue: https://github.com/intelsdi-x/snap-plugin-publisher-mysql/issues/16#issuecomment-233093616

The type mismatch issue, particular `uints`, may need better coverage.

**Comment by nanliu** [comment]
We need better acceptance test. At minimum we should attempt to load all plugins as part of the release process. I've done this manually for the 0.15 release and will write an acceptance test to help catch these type of issues.

**Comment by mjbrender** [comment]
That's a great additional feature @nanliu. Separately, shouldn't mock cover us here?

**Comment by IRCody** [comment]
Is the idea that mock collectors should publish metrics that cover some specific set of types so there is an easy way to verify a publisher at least supports those base types?

**Comment by mjbrender** [comment]
@IRCody exactly my point, since I thought that's what mock is for. Is that premise right though?

**Comment by IRCody** [comment]
The mock plugins are used for Snapd tests. I don't think the intention is for them to be used by plugin authors to act as some sort of minimal test for a plugin.

**Comment by lynxbat** [comment]
@IRCody is right. Plugin tests should be for the plugins. The mocks are for Plugin API tests on Snapd itself.

**Comment by nanliu** [comment]
Sounds like we decided mock plugins are only for Snap testing, and not intended for plugins. Should we close this issue?

**Comment by IRCody** [comment]
@mjbrender: Going to close this for now, feel free to re-open if you think there is still discussion that needs to happen.
