### ISSUE TITLE
Descriptions for rules need to be passed from plugin to daemon

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#1081]
When rules are encoded prior to being sent to the daemon, Description does not appear to be passed, at least afaict. An example of the Gob Encoding that is(not) happening can be seen [here](https://github.com/intelsdi-x/snap/blob/master/control/plugin/cpolicy/integer.go#L90-L124).

**Comment by candysmurf** [comment]
@IRCody agreed with you that the description currently it's not being sent.

**Comment by candysmurf** [comment]
The question is that if we need to encode "Description" or simply not expose it.

**Comment by mbbroberg** [comment]
Changing from a question to a bug given that it drops information the daemon can be expected to have.

**Comment by katarzyna-z** [comment]
Description of plugin rules are not provided in existing plugin code. In config policy plugin's authors define:
- rule name,
- requirement boolean
- default value
- min & max value (if applicable).
What's more `snaptel metric get` which partially presents config policy rules also do not have such column. The reason of that is rule name quite clear and usage is described in readme.

cc: @IzabellaRaulin
