### ISSUE TITLE
Ignore specified metrics that are not available

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap#1086]
When deploying on a variety of systems, there may be metrics available on some systems that are not available on others. However, this means each system would need a unique task manifest that is tailored to that system. What I'm proposing is either an optional tag for a metric to be ignored if not available or a setting that allows the snap collector to collect every listed metric that is available and ignore the ones that are not. This would allow a single task manifest to be used on multiples systems with various unique metrics. One example would be cpu metrics. The linux kernel provides 10 columns of metrics: `user, nice, system, idle, iowait, irq, softirq, steal, guest, guest_nice`
Older versions of the kernel only have a subset of these metrics available. This would mean either the use of a wildcard at the end of the metric: `/intel/procfs/cpu/all/*` if you wanted only one task that could collect on a variety of systems. This solution is not ideal and an alternative would be making the unique metrics optional using some kind of unique tag in the task manifest or a snapd configuration.

**Comment by candysmurf** [comment]
@jtlisi, It’s a good idea and we are investigating how to deliver the feature and will update you once it's ready for you to test.

**Comment by jtlisi** [comment]
@candysmurf Sounds good! If there is anything I can do to help please let me know.

**Comment by nanliu** [comment]
This is related to #1190. Since most of the discussion occurs in that issue, I'm going to close this in favor of #1190. Please provide feedback to the proposals on how to enable optional metrics and which one you would like to see implemented.
