### ISSUE TITLE
Document the '--metric-version' values that can be used with 'snapctl'

### ISSUE THREAD

**Issue by tjmcs** [intelsdi-x/snap#1088]
We need to better document the various `--metric-version` values that can be used with a `snapctl metric get ...` command (and the associated `GET` that can be performed against the `/metrics` resource in the Snap RESTful API). Specifically, we should discuss that a value of:
- **0** can be used to get **all** versions of a given metric (or set of metrics if a wildcard is used in the specified metric namespace)
- **-1** can be used to get the latest version of a given metric (or set of metrics), and
- that values greater than zero can be used to retrieve a specific version

This documentation should also discuss the newly added ability to use a wildcard when specifying the metric namespace and discuss the change over to passing the namespace in as a query string value that modifies a `GET` against the `/metrics` URI (which results in a URI that looks like `/metrics?ns=[METRIC_NAMESPACE_VALUE]`)

**Comment by katarzyna-z** [comment]
Available help, see below, seems to be enough clear for user. If they specify version they may expect getting metric in this version. It's common approach.
```
OPTIONS:
   --metric-version value, -v value    The metric version. 0 (default) returns all. -1 returns latest. (default: 0)
   --metric-namespace value, -m value  A metric namespace
```
