### ISSUE TITLE
Support dynamic metric type annotation as the default

### ISSUE THREAD

**Issue by candysmurf** [intelsdi-x/snap#1098]
### Problem
- When a metric includes dynamic elements, it's not always obvious what the field is meant to represent

Example `snapctl metric list`:

```
/intel/cass/*/*/*/max
/intel/cass/*/*/*/mean
```
### Proposed Solutilon
- Shows the annotated metric catalog **as the default** when listing the metric catalog `snapctl metric list` (today this is displayed when the flag `--verbose` is present)

```
/intel/cass/[type]/[scope]/[name]/max
/intel/cass/[type]/[scope]/[name]/mean
```
- The framework should support in task manifests both forms of the namespace (those including `*` and `[field_name]`)
- Update docs

**Comment by geauxvirtual** [comment]
The reason the metrics are not expanded in the default metric catalog list with dynamic field entries as opposed to the `--verbose` listing is that the default listing groups metric versions together, and there is no guarantee that each version of the metric has the same fields as the other versions. The `--verbose` flag prints each metric in the catalog on a separate line allowing for the dynamic elements to be expanded to provide more detail on required values per metric.

**Comment by IzabellaRaulin** [comment]
This feature has been added by https://github.com/intelsdi-x/snap/pull/931 and works properly (see below):
```
$ snaptel metric list
NAMESPACE                VERSIONS
/intel/mock/*/baz        1
```
and with option "verbose":
```
$ snaptel metric list --verbose
NAMESPACE                VERSION         UNIT    DESCRIPTION
/intel/mock/[host]/baz   1
```

and this issue may be closed. 

@candysmurf - if there is still something to be done in the context of this issue, feel free to open it again. Thank You.
