### ISSUE TITLE
Snapctl task create doesn't give error/debug message for wrongly formatted input

### ISSUE THREAD

**Issue by ssorsa** [intelsdi-x/snap#1100]
If the task .yaml - file is wrongly formatted or not in proper format and the user tries to load it with snapctl: "snapctl task create" command, the output doesn't state any error messages to the user. Snapctl should put an error message to the user, that the input file is not properly formatted or it can't parse the input file. Now you can only try to load the file, but you don't get any tasks.

**Comment by obourdon** [comment]
I think it is a duplicate of #1097 and has been fixed by #1097

**Comment by candysmurf** [comment]
@ssorsa, Would you please get the latest Snap and let us know if the problem is fixed?

**Comment by ssorsa** [comment]
I updated the snap few mins ago and tested, now it works and reports errors while you try to load malformed .yaml or .json. So, fixed!
