### ISSUE TITLE
on plugin load error snapd should log what the plugin sent to stdout 

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1105]
When snapd starts a plugin **and is unable to unmarshal it's stdout** the snapd log should include whatever the plugin sent to stdout to facilitate debugging.  Today snapd only returns the error from the unmarshal which includes the first letter of whatever was sent to stdout (e.g. "invalid character 'p' looking for beginning of value").

**Comment by IRCody** [comment]
I think the rest client does something similar when it has marshaling errors [here](https://github.com/intelsdi-x/snap/blob/89e29ab274b1fe7e353949b7d0cfaca27ddd3f8a/mgmt/rest/client/client.go#L256-L263) by returning the first 1k characters of any error to help debugging. Seems like a similar method could be used here.
