### ISSUE TITLE
New make install doesn't work if you don't have GOPATH set up for root.

### ISSUE THREAD

**Issue by mkuculyma** [intelsdi-x/snap#1108]
There is a possibility that following the steps from "Build and Test" tutorial (https://github.com/intelsdi-x/snap/blob/master/docs/BUILD_AND_TEST.md) a user could omit fact that they need to export GOPATH variable for root as well. And if they do omit this detail, snap will not compile with the command "sudo make install" - in the latest commit `make install` causes not only `cp` binaries to /user/local/bin, but also before that executes `make` for which GOPATH is needed.

**What do you think about adding an annotation in this tutorial that GOPATH should be set both for user and root?** This issue will probably reveal itself to the users that start their journey with Snap. Annotation will help us not to spoil the first impression with compilation error.

**Comment by mjbrender** [comment]
Good catch @mkuculyma. I think that clarification is needed and if we end up changing the requirement for `sudo`, we'll readjust. Would you mind opening a pull request to fix this? 

cc @intelsdi-x/snap-maintainers
