### ISSUE TITLE
Namespace validation is too permissive

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap#1116]
Blacklist there https://github.com/intelsdi-x/snap/blob/master/control/metrics.go#L44 lacks regexp control characters `+` and `$`.
Additionally my  suggestion is to disallow any non-printable character in namespace and use `"\0"` internally as separator. `unicode` package contains definitions of character classes, so it should be used for such check.

**Comment by mjbrender** [comment]
@lmroz great improvement. Tagging it based on the context.

**Comment by kindermoumoute** [comment]
I close that because of https://github.com/intelsdi-x/snap/pull/1252
