### ISSUE TITLE
syslog collector

### ISSUE THREAD

**Issue by vnitinv** [intelsdi-x/snap#1117]
Hi,

Can anyone point me if we already have a syslog collector. If not, can someone help me in developing the same.
this collector is supposed to listen on to a specific port on which different devices are publishing their syslogs. 
syslog string example

```
Jul 31 03:44:11  linux-01 mgd[8806]: UI_COMMIT_COMPLETED: commit complete
```

If I can get a proto type code, I can extend it. Thanks in advance.

**Comment by vnitinv** [comment]
to add, I am able to collect syslog using this go module
https://github.com/mcuadros/go-syslog

log:
```
map[content:UI_CMDLINE_READ_LINE: User 'root', command 'configure ' tls_peer: hostname:bng-ui-vm-94 tag:mgd facility:23 severity:6 client:10.209.16.206:514 timestamp:2016-07-31 04:37:25 +0000 UTC priority:190]
map[priority:189 facility:23 severity:5 timestamp:2016-07-31 04:37:25 +0000 UTC hostname:bng-ui-vm-94 content:UI_DBASE_LOGIN_EVENT: User 'root' entering configuration mode tag:mgd client:10.209.16.206:514 tls_peer:]
map[tag:mgd content:UI_CMDLINE_READ_LINE: User 'root', command 'commit ' facility:23 timestamp:2016-07-31 04:38:00 +0000 UTC priority:190 severity:6 client:10.209.16.206:514 tls_peer: hostname:bng-ui-vm-94]
```

So I can use this module to collect syslog, Just need to know how to write collector using this so that snap can consume these datas.

**Comment by IRCody** [comment]
@vnitinv: AFAIK there is not already a syslog collector. The [plugin authoring](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md) documentation is a good resource for writing a plugin. You can also look at some examples from the [plugin catalog](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md) to get an idea of what is involved.  If you run into any trouble with the docs or writing the plugin please ping us back here or on slack.

**Comment by dishmael** [comment]
Created a [Syslog collector plugin](https://github.com/dishmael/snap-plugin-collector-syslog). It is still under construction but appears stable in dev. Will work on documentation. Looking for feedback and suggestions.

**Comment by mjbrender** [comment]
@dishmael very cool. Your PR will close this issue so I updated it and I hope it helps @vnitinv too. Love seeing this contribution.

**Comment by vnitinv** [comment]
Thanks @dishmael
