### ISSUE TITLE
snapctl printing "If the number of maximum failures is not specified, use default value of x"

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#1131]
When starting a task without the maximum number of failures, snapctl will print out the following:
```
% ./snapctl task create -t task.json  
Using task manifest to create task
If the number of maximum failures is not specified, use default value of 10
```
this feels like an odd place to be printing this out and is phrased somewhat oddly. If we want to inform the user of what we are doing it could be phrased like:
```
No value provided for maximum failures, using default value of 10
```
To more clearly state what is happening, rather than putting it as a conditional (which is only printed in the case where the # of max failures is not specified).

Relevant code is [here](https://github.com/intelsdi-x/snap/blob/a9436084ae0c803b00e1452cf104db1b917692c1/cmd/snapctl/task.go#L134).

**Comment by tjmcs** [comment]
This is addressed as part of PR #1127, which is currently still open but close to being merged. When that PR is merged, this issue should be closed as well.
