### ISSUE TITLE
Using config based strategy make the task fail with error "Plugin strategy not set"

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap#1132]
Code used:
```
func Meta() *plugin.PluginMeta {
	return plugin.NewPluginMeta(
		name,
		version,
		pluginType,
		[]string{plugin.SnapGOBContentType},
		[]string{plugin.SnapGOBContentType},
		plugin.Unsecure(true),
		plugin.RoutingStrategy(plugin.ConfigRouting),
	)
}
```

Error when running the task:
<img width="1899" alt="screen shot 2016-08-09 at 5 55 29 pm" src="https://cloud.githubusercontent.com/assets/10092554/17538471/97b21910-5e5a-11e6-8a64-6f257c549568.png">

**Comment by marcin-krolik** [comment]
@kindermoumoute I tried to reproduce this error with various scenarious without success. Last one I tried was
- `snapd` built from `master-d9b23fa`
- `meminfo` checkout `master-edd7a87`, changed routing strategy to `plugin.ConfigRouter`, compiled
- `mock-file` and `passthru` loaded
- started task from `meminfo` examples

I got no error on task start, task is running and metrics are being gathered.

Could you provide some more information how to reproduce it?

**Comment by kindermoumoute** [comment]
@marcin-krolik I can't reproduce it too. Maybe I was using a version of Snap older than when you added this feature in #850.
