### ISSUE TITLE
Snapctl task create needs more detailed error message from malformed input files

### ISSUE THREAD

**Issue by ssorsa** [intelsdi-x/snap#1137]
When user creates a task in snapctl: "snapctl task create -t task.json" and the input format is malformed the error message that the user is given for some errors is: 

Using task manifest to create task
Error parsing JSON file input - json: cannot unmarshal string into Go value of type map[string]interface {}

Even a line number would be useful in this situation. Now the user needs to figure out the correct line where the error lies. In namespace error the message is:

Error creating task:Invalid namespace: intel/proc

When the user is missing the first "/". This line gives more information for correcting the issue compared to the "Error parsing JSON file input - json: cannot unmarshal string into Go value of type map[string]interface {}".

I'm asking if the line number from malformed input file would be added to the error message.

**Comment by IRCody** [comment]
@ssorsa: Thanks for the feedback. Better error messages definitely improve the user experience.

>I'm asking if the line number from malformed input file would be added to the error message.

I think this is a good idea. I am adding an enhancement label to this issue so it can hopefully be added in the future.

**Comment by nanliu** [comment]
Maybe this package can provide a more human friendly error: https://godoc.org/go4.org/errorutil
