### ISSUE TITLE
Plugin name in distributed-mock-file.json incorrect

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#1141]
In [distributed-mock-file.json](https://github.com/intelsdi-x/snap/blob/master/examples/tasks/distributed-mock-file.json) the file publishers name was not updated when it was changed from file => mock-file which makes the example not work without having an extra dependency outside of snap.

**Comment by kjang96** [comment]
Are we trying to change the file publisher in mock-file.yaml and mock-file.json to "file" instead of "mock-file" or changing the example plugin to be loaded to "snap-plugin-publisher-mock-file" instead of "snap-plugin-publisher-file"?

**Comment by kjlyon** [comment]
We need to change [this](https://github.com/intelsdi-x/snap/blob/master/examples/tasks/distributed-mock-file.json#L28) line to reference "mock-file" so the mock file publisher gets loaded.

**Comment by kjang96** [comment]
We are referring to the README example right? "mock-file" is never loaded as per the example instructions, whereas "file" is, so why are we changing to "mock-file"?

**Comment by kjlyon** [comment]
@kjang96 and I determined we were talking about different issues. This issues is now assigned to me.

**Comment by jcooklin** [comment]
The intent of this issue to make it consistent which plugins we leverage.  Specifically leveraging the file publisher https://github.com/intelsdi-x/snap-plugin-publisher-file.

We will eventually accompany these tasks with run scripts which pull down all of the dependencies, start snap, load plugins and tasks without requiring snap to be built.
