### ISSUE TITLE
Invalid namespace validation

### ISSUE THREAD

**Issue by iwankgb** [intelsdi-x/snap#1147]
function [``wmap.isValidNamespaceString()``](https://github.com/intelsdi-x/snap/blob/5192dc4b9d55b3f87c876443bdc7b6f2e079bcad/scheduler/wmap/wmap.go#L323) is responsible for namespace validation in [``CollectWorkflowMapNode.GetConfigTree()``](https://github.com/intelsdi-x/snap/blob/5192dc4b9d55b3f87c876443bdc7b6f2e079bcad/scheduler/wmap/wmap.go#L187). Function is inconsistent with [documentation ](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md#metric-naming) and [``control.validateMetricNamespace()``](https://github.com/intelsdi-x/snap/blob/5192dc4b9d55b3f87c876443bdc7b6f2e079bcad/control/metrics.go#L340).

I believe that metric validation logic should be unified. At the moment it is impossible to set configuration for following namespaces:
* /foo/*/bar
* /foo/bar_baz

that are perfectly correct as metric namespaces.

**Comment by skonefal** [comment]
This partly looks like duplicate of #1133

**Comment by IRCody** [comment]
@iwankgb Thank you for reporting this. I believe this is a duplicate of #1133, but that issue did not include the links to documentation changes that would need to be done so I have edited it to include your links. 

If you think #1133 doesn't completely capture your issue respond back here and @ me and I'll reopen.
