### ISSUE TITLE
snapctl exit status

### ISSUE THREAD

**Issue by iwankgb** [intelsdi-x/snap#1148]
When ``snapctl`` fails because of missing plugin configuration then 0 exit status is returned and it is difficult to determine application error as output parsing might not work all the time.

snapd logs:
````
time="2016-08-17T12:54:06Z" level=info msg="API response" _module="_mgmt-rest" index=4 method=POST status="Internal Server Error" status-code=500 url="/v1/tasks"
````
Command execution:
````
[vagrant@localhost snap]$ snapctl --url=http://localhost:49365 task create -t task.yml 
Using task manifest to create task
Error creating task:
required key missing (port)
required key missing (qps)
[vagrant@localhost snap]$ echo $?
0
````

**Comment by IRCody** [comment]
@iwankgb: Thanks for reporting. I agree that the exit status should signal correctly if there is an error.

**Comment by daria-lewandowska** [comment]
I think this is fixed in snap newest version. 
My command execution is: 
`Using task manifest to create task`
`Error creating task:required key missing (host)`
`$ echo $?`
`1`

**Comment by iwankgb** [comment]
@daria-lewandowska, @IRCody - if it is fixed on master then I don't mind this issue being closed :)

**Comment by IRCody** [comment]
Thanks @daria-lewandowska for noticing and updating the issue. @iwankgb: Going to go ahead and close it then.
