### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by rl1748** [intelsdi-x/snap#1151]
Real newbie type question ...  What tool is used to view the data that is stored by the Publisher ?

**Comment by IRCody** [comment]
Hey @rl1748: The goal for publishers is not to store the data, but to publish it somewhere else, which is where you would be able to access it. 

For example if you look at one of the example tasks, [mock-file.yaml](https://github.com/intelsdi-x/snap/blob/master/examples/tasks/mock-file.yaml), You will see that it is using the mock-file publisher. This publisher outputs metrics it receives into the file that is specific in the manifest, which in this case is `/tmp/snap_published_mock_file.log`. To view the data that has been published you can open this file up in an editor or just do `cat /tmp/snap_published_mock_file.log`.

If you were using another publisher, say the [mysql publisher](https://github.com/intelsdi-x/snap-plugin-publisher-mysql), the data would be stored in the database that is specified in the task manifest.

Hopefully that helps. If you have more questions let us know here or by joining our [slack](https://intelsdi-x.herokuapp.com/).

**Comment by IRCody** [comment]
@rl1748: I'm going to close this issue, but if I didn't answer your question clearly feel free to respond back and ping with `@ircody` and your question and I can reopen it.

**Comment by rl1748** [comment]
Cody, looks like Grafana is the answer to my question  ?      I watched the video where Grafana provided a graphical interface to data collected by the publishers.

**Comment by IRCody** [comment]
@rl1748: You're right, Grafana is one of the most common tools to visualize metrics. I think I must've misunderstood the gist of your question. If you have anymore questions let me know.
