### ISSUE TITLE
Redesign maintainer notification workflow

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#1155]
When we started with GH teams it was under the impression that anyone could tag groups like @intelsdi-x/snap-maintainers or @intelsdi-x/plugin-maintainers and get our attention. Unfortunately, that is not how this feature behaves - only **organization members** can get the attention of teams. 

I'd like to rethink how people contact maintainers given this behavior. I've contacted GitHub for recommendations, but hope a public discussion could help narrow in on one.

**Comment by IRCody** [comment]
Would it be useful to have an account that can be tagged that you could use to send notifications to a group of people via something else (slack?)

**Comment by thomastaylor312** [comment]
Isn't there a Slack plugin or webhook we could use that could push alerts into a Slack channel any time a new issue or PR is opened or a specific trigger phrase is given in a comment?

**Comment by nanliu** [comment]
What about https://github.com/facebook/mention-bot?

**Comment by mjbrender** [comment]
Genius @nanliu. I love what mention-bot should do for us for reviews.

**Comment by kjlyon** [comment]
@kjlyon is currently working on this issue

**Comment by kjlyon** [comment]
This problem can be solved simply by having all snap maintainers add `snap-maintainers` as a highlight word in their slack notifications. This way, whenever a post comes through that has contains the text `@slack-maintainers` or `@intelsdi-x/slack-maintainers`, who ever has their notification set up will be notified. 
At this point we have already eliminated the recommendations to use the @snap-maintainers tag in our GitHub documentation and lately we have had good activity in our Slack channel. I believe we should continue to suggest people use Slack to contact us and we can use GitHub's @snap-maintainers functionality to notify ourselves on issues. Thus the issue, as described above, is closed.
In response to @nanliu's recommendation, mention-bot looks like a great tool, but I think it is solving a different problem.
