### ISSUE TITLE
Snap doesn't return error on invalid task file

### ISSUE THREAD

**Issue by thomastaylor312** [intelsdi-x/snap#1157]
When creating a task from a JSON file, Snap ignores invalid configuration

Bad config file:
```
{
   "version":1,
   "schedule":{
      "type":"simple",
      "interval":"1s"
   },
   "workflow":{
      "collect":{
         "metrics":{
            "/intel/procfs/disk/*/*":{

            }
         }
      },
      "process":null,
      "publish":{
         "plugin_name":"file",
         "config":{
            "file":"/tmp/testoutput"
         }
      }
   }
}
```

When you create the task, it creates successfully with the following output from `snapctl task export`:
```
{
   "id":"3c972277-60e1-4339-8a43-74539bdc3d94",
   "name":"Task-3c972277-60e1-4339-8a43-74539bdc3d94",
   "deadline":"5s",
   "workflow":{
      "collect":{
         "metrics":{
            "/intel/procfs/disk/*/*":{
               "version":0
            }
         }
      }
   },
   "schedule":{
      "type":"simple",
      "interval":"1s"
   },
   "creation_timestamp":1471977934,
   "last_run_timestamp":1471977973,
   "hit_count":39,
   "task_state":"Running",
   "href":"http://localhost:8181/v1/tasks/3c972277-60e1-4339-8a43-74539bdc3d94",
   "Err":null
}
```

It appears that snap ignored the invalid parts of the workflow instead of erroring on creation. This is tested against the latest master

**Comment by IRCody** [comment]
@thomastaylor312: You are talking about the Publish not being a list correct? (It took me a few to notice). I wonder if that's json marshaling not returning an error or if we are ignoring it?

**Comment by thomastaylor312** [comment]
Yes, and it also happened when my publish was outside of the `workflow` object/dictionary

**Comment by thomastaylor312** [comment]
Sorry, I meant that the `publish` was outside of the `collect` object/dictionary

**Comment by thomastaylor312** [comment]
@IRCody The invalid task manifest is valid JSON, it is just an invalid task manifest

**Comment by IRCody** [comment]
@thomastaylor312: Even if it's validJSON marshaling it into the task object should fail I think. I will try to look into it.

**Comment by geauxvirtual** [comment]
Unless specific code is written to validate the task manifest sections, `json.Unmarshal` will just ignore anything that doesn't exist in the object that was passed to it.

**Comment by IRCody** [comment]
@geauxvirtual: Thanks! That would explain the behavior then I think then. It matches what we are seeing where the task is created with only the portion of the task manifest that maps correctly to something in the task struct. I'm not sure the best way to fix it though, even with custom unmarshal there are limits to what you can check for I think.

**Comment by geauxvirtual** [comment]
I can put something together tomorrow as this ties into my work on #1130.

**Comment by geauxvirtual** [comment]
In the current code I'm working on, I have this being outputted as an error message with the invalid task manifest supplied up above.

```
--- intelsdi-x/snap ‹tb/1130* ?› » go run cmd/snapctl/*.go task create -t test.json
Using task manifest to create task
Error parsing JSON file input - Unrecognized key 'process' in workflow of task.

exit status 1
```
