### ISSUE TITLE
Clarify scope and purpose of examples/ folder

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#1158]
The goal of files/folders in `examples/` is not clear. I'd like to discuss a couple points (and can check them off as we do).

Biggest question: 
- [ ] 1. What is the first example we want everyone to use with Snap? 

More on tactics: 
- [ ] 2. How should the `tasks/` folder differ from example tasks in each plugin repository?
- [ ] 3. How can we ensure all these files - tasks, configs, full demos - run? 
- [ ] 4. When is it best to have a folder in this repo v a separate one (example from [Velocity](https://github.com/nanliu/snap-demo-velocity))? 

A few opinions on where we go from here:

1 -> I'd like people to be able to deploy "an Application", Snap, Grafana as containers, not include any persistence layer, and have a dashboard of Tasks running in a Grafana Graph. We don't need persistence to do this when using the Snap App from raintank ([link](https://grafana.net/plugins/raintank-snap-app)). We then collect stats from the Docker API. 

The "Application" we use as example could be as simple as `dd if=/dev/urandom | bzip2 -9 > /dev/null` running. Just something to give it a graph worth seeing.

If we want a non-Docker version, it could be a Vagrantfile with limited dependencies. When I think of a reliable demo, I think of psutil. We use it extensively when we demo and it always has numbers to show. It should be a good baseline to get Grafana Graphs together worth showing if we don't go the Docker route. 

2 -> I'm unsure here. Only opinion is that we have examples that include different types of plugins (collector, processor, publisher). 

3 -> I could see requirements coming from our build process. I don't have an opinion on what they are, but it'd be awesome to write them down. 

4 -> Not sure again. I think it's scoping comes from build workflow. 

Relates to: 
#786 << Have valid examples, including the metadata (especially stop using mock)
#1007 << Adding further schedule types

**Comment by IRCody** [comment]
>1 What is the first example we want everyone to use with Snap?

>1 -> I'd like people to be able to deploy "an Application", Snap, Grafana as containers, not include any persistence layer, and have a dashboard of Tasks running in a Grafana Graph. We don't need persistence to do this when using the Snap App from raintank (link). We then collect stats from the Docker API.

>The "Application" we use as example could be as simple as dd if=/dev/urandom | bzip2 -9 > /dev/null running. Just something to give it a graph worth seeing.

>If we want a non-Docker version, it could be a Vagrantfile with limited dependencies. When I think of a reliable demo, I think of psutil. We use it extensively when we demo and it always has numbers to show. It should be a good baseline to get Grafana Graphs together worth showing if we don't go the Docker route.


I like the idea of having some sort of way to vagrant up/docker run an example that includes all the moving parts that includes a good readme type explanation of what is happening.

> 2. How should the tasks/ folder differ from example tasks in each plugin repository?

I think a differentiation between the tasks/ folder in snap and the example tasks in the plugin repos should be that the tasks/ folder in snap focus on what different sorts of things you can do with tasks. An example tasks in a plugin repo should focus on that specific plugins options/etc. Some that come to mind:

* Collect->Process->Publish -- the "standard" workflow
* Collect-> Publish (no process) -- Might be useful to ensure that people know you can go from collect directly to publish.
* Collect->Publish, Collect->Process->Publish -- display a forking of the workflow that demonstrates collecting raw metrics, as well as publishing processed metrics.
* distributed workflow example
* Example of config on all of {collect,process,publish}


>3. How can we ensure all these files - tasks, configs, full demos - run?

Would it make sense to include this as some sort of large-test?

**Comment by jcooklin** [comment]
>How can we ensure all these files - tasks, configs, full demos - run?

My current opinion on this is that our end-2-end tests should leverage the tasks in examples/tasks which will confirm that our examples actually work.

>When is it best to have a folder in this repo v a separate one (example from Velocity)?

IMO, general examples should be in the snap and plugin repos and we will expect that these examples always work as they will be executed on merge and in some cases nightly.  As a general rule separate repos for examples would be for a specific audience and may not  be supported long term. 

>I like the idea of having some sort of way to vagrant up/docker run an example that includes all the moving parts that includes a good readme type explanation of what is happening.

This is the direction we are headed.  The intent is that a `make test-large` will run locally large tests (requiring either docker-compose or kubernetes).  Alternatively, I would like for local run scripts to exist next to the example tasks which will depend on nothing more than bash and curl.  The run script will download the latest deps (snapd, snapctl, plugins), start snapd, load plugins and start tasks.  Compiling snap or plugins should not be required to run examples.

**Comment by candysmurf** [comment]
It seems a good time to redefine the scope of examples. Should snap examples be focused on Snap and have docs linked to other plugin-lib repo examples?
