### ISSUE TITLE
Clearer advice on reason for plugin/ folder

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#1159]
I've received feedback what `plugin/` confuses new developers of Snap. Upon review, it does appear that these mock plugins could be seen as references on how to design a plugin. I think we would benefit from being explicit about this folder's role in relation to the project.

**Comment by mjbrender** [comment]
Hey @jcooklin - another touchpoint we've talked about briefly but I haven't offered a fix for. What do you think of this approach?

https://github.com/mjbrender/snap/tree/demo-edit/plugin#please-note-these-are-not-example-plugins

I'd dig having a copy of this on each subfolder so people can't land in a folder and be unsure of the goal. If my understanding of why we have this folder is off, that's okay too :) - let's clarify.

**Comment by IRCody** [comment]
I think some sort of disclaimer makes sense and would be a simple way to avoid any confusion.

**Comment by candysmurf** [comment]
Should those mock plugins reside in "plugin-lib" repositories?

**Comment by elemoine** [comment]
Or `test-plugins` maybe. If the plugins in this dir are only for testing I think the directory name should explicitly reflect that. Just my 2 cents.
