### ISSUE TITLE
Errors during capturing of stderr from plugins

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#1167]
It seems that there is an issue with capturing logs from plugin which are sent to stderr. The issue was observed using the cpu plugin. 

I've prepared the special versions of cpu plugin to observe what if plugin sends logs frequently:
- cpu plugin with frequent short log, the version is available [here](https://github.com/katarzyna-z/snap-plugin-collector-cpu/commit/a79c0a040d6308a9276a54d2e6f8cd27581f8b95), 
- cpu plugin with long log, the version is is available [here](https://github.com/katarzyna-z/snap-plugin-collector-cpu/commit/9738a2b2145067d19cb5e3c776ec9d233428b204).

I've tested this two special versions of cpu plugin with two version of snap:
- snap with capturing of logs from plugins, it is this [commit](https://github.com/intelsdi-x/snap/commit/5d91b04fa8b7d398fea04f5cbbe970f21cf32bd9),
- snap without capturing of logs from plugins, it is this [commit]( https://github.com/intelsdi-x/snap/commit/84aa75e8074ecbf633b43d07a96a12aa43f6861a).

I've observed that errors appear only in snap with capturing of logs from plugins. It seems that there is a problem in capturing stderr from plugins when log line is long. In the snap version without capturing of logs from plugins there was a special case for errors returned by the scanner, please see [this](https://github.com/intelsdi-x/snap/commit/5d91b04fa8b7d398fea04f5cbbe970f21cf32bd9#diff-9263d577284097ec1bec3e3fce13eb32L328) .

It could be fixed on plugin side (by adding a newline at the end of the log) but it will be good to have a protection also on snap side.

**Comment by candysmurf** [comment]
@katarzyna-z, thanks for reporting an issue in details. For the scanner one, the log is in a goroutine. It won't cause the hanging. It's understandable.

It doesn't make sense if a long log causes hanging. It seems a program issue to me. Can you elaborate more? thanks!
