### ISSUE TITLE
Rest client test at line 430 is unreliable

### ISSUE THREAD

**Issue by kjlyon** [intelsdi-x/snap#1176]
* /home/travis/gopath/src/github.com/intelsdi-x/snap/mgmt/rest/client/client_func_test.go 
  Line 430:
  Expected: 'error 0: Task is already stopped. '
  Actual:   'error 0: Subscription does not exist '
  (Should be equal)

**Comment by candysmurf** [comment]
@kjlyon, thanks for reporting it. Do you have steps to reproduce it?

**Comment by kjlyon** [comment]
This issue was identified in PR #1174 . [Here](https://travis-ci.org/intelsdi-x/snap/jobs/156899302) is the exact error in travis.
