### ISSUE TITLE
case sensitive plugin name

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap#1178]
Currently, it is possible to load 2 plugins with the same name, if we change the case.

So, "Use" and "use" collector could both be loaded with the same version.

This could open snap to a few subtle issues, such as removing the wrong plugin.

Not sure how to solve this, but talking on slack, @IRCody and @thomastaylor312 had some ideas. 

I'm opening this issue so can move the conversation here and other can contribute.

**Comment by thomastaylor312** [comment]
Based on the discussion from slack, I am more of a fan of enforcing lower case only, but @IRCody did point out that it could break existing plugins. The other option is to have case insensitive comparisons.

**Comment by IRCody** [comment]
The options I thought of for addressing this are:

>  Enforce only lower case for plugin names.

This would be easy implementation wise. The negative is that it could cause plugins that currently work to be unable to load (if they have an upper case name). The `Use` plugin is an example.

> Do case insensitive comparison for plugin names in snap.

This is a little more work implementation wise. The obvious benefit is that it has no impact on existing plugins provided they do not conflict with another plugin's name when doing a case-insensitive comparison.

**Comment by thomastaylor312** [comment]
@IRCody Do you think the risk of breaking is ok? I think option 1 is better and we can have that be the rule for when we hit 1.0. If we were already at 1.0, I would think option 2 would be safer.

**Comment by IRCody** [comment]
I would want to know how many existing plugins are effected and probably go through and fix those before making a change we know is going to break them but I also like option 1 better.

**Comment by jcooklin** [comment]
Adding to what has already been said I feel the next step could/should be

1. Add to the announcements (on slack, main readme, etc.) that we intend to enforce lowercase names for plugins on the 0.17 release (4 weeks) describing why and what impact this may have.
2. Before the 0.17 release log a warning when a plugin is loaded that doesn't pass validation.

cc: @mjbrender
