### ISSUE TITLE
snapd ram memory usage dramatically increases when a plugin is added

### ISSUE THREAD

**Issue by ericho** [intelsdi-x/snap#1189]
Looking in the memory usage that snapd consumes in the different stages I noticed that the memory increases when a plugin is added. For instance:

Without any plugin added, ```snapd -t 0 --log-level 1```
```
$ ps -C snapd -o pid=,%mem=,vsz=,rss=
31100  1.5  19324  7864
```

So, adding a plugin, ```snapctl plugin load snap-plugin-processor-passthru```

```
$ ps -C snapd -o pid=,%mem=,vsz=,rss=
31100  7.2  55612 36556
```

So from a very nice 7.8MB increased into 36.6MB

Adding another one, ```snapctl plugin load snap-plugin-collector-cpu```
```
$ ps -C snapd -o pid=,%mem=,vsz=,rss=
31100  8.2  55612 41348
```

Now, the ram is 41.3MB. 

The behavior is the same changing the order of plugins loaded. It seems that some initialization happens in snapd, but is good to have such a big increase?

**Comment by geauxvirtual** [comment]
Yes, this is normal since the plugin binary is read into memory before being written to the filesystem when loading through snapctl. The memory gets released, but unless the OS is under pressure for memory, the OS will continue to report the application is using the amount of memory it was allocated. The only way to see the amount of memory snapd is actually using is from within the application itself.

**Comment by ericho** [comment]
So, if the memory is released, when should I see a memory decrease? 

I though that maybe after running a task the number should decrease (i'm assuming that the in-memory binaries are write in this step), so I did the following: 

```
$ snapctl task create -t testing-snap.json
Using task manifest to create task
If the number of maximum failures is not specified, use default value of 10
Task created
ID: cadfa65f-fe87-4294-8618-0a350565493a
Name: Task-cadfa65f-fe87-4294-8618-0a350565493a
State: Running
$ ps -C snapd -o pid=,%mem=,vsz=,rss=
31197  8.3  55612 41832
```

I'm just running collector-cpu and publisher-file plugins. 

Running several times the ps commands I get the following: 

```
$ ps -C snapd -o pid=,%mem=,vsz=,rss=
31197  8.3  55612 41832
31197  8.3  55612 41988
31197  8.3  55612 41988
31197  8.4  55612 42152
31197  8.4  55612 42272
```

Actually the memory usage is increasing (maybe a memory leak there..)

**Comment by ericho** [comment]
I just saw a decrease, after some minutes:

```
31197  2.8  55612 14304
```

**Comment by jcooklin** [comment]
>So, if the memory is released, when should I see a memory decrease?

It's going to depend on the OS but like @geauxvirtual mentioned generally it's when the OS is under pressure.  

@ericho should we close this issue or do you have additional findings or points you would like to discuss?

**Comment by ericho** [comment]
Sure, I think we can close it. Thaks for the explanation :)

**Comment by candysmurf** [comment]
@ericho, thanks for reporting concerns!
