### ISSUE TITLE
Plugins started on unsuccessful task start are not stopped

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#1210]
After creating a task, if the task is stopped and a plugin is removed that the task needs, attempting to start the task will result in starting the plugins required for the task, but not stopping those plugins when the task fails to start due to a missing required plugin. There is no way to stop these plugins without stopping snapd.

**Comment by lynxbat** [comment]
Would a plugin existence check on start solve this?

**Comment by geauxvirtual** [comment]
Code currently tries to subscribe to dependencies and then tries to unsubscribe from dependencies if any error is found during subscription. This doesn't look to be stopping the started plugins though.

https://github.com/intelsdi-x/snap/blob/master/scheduler/scheduler.go#L486-L510

**Comment by geauxvirtual** [comment]
I believe the problems lies here https://github.com/intelsdi-x/snap/blob/master/scheduler/scheduler.go#L500. We are ranging over `subbedDeps`, but nothing actually sets `subbedDeps`, so this slice is empty.

**Comment by geauxvirtual** [comment]
To expand on the last comment, there is only one dependency group created for the task. `subbedDeps` is only added to if all subscriptions succeed. If an error occurs during subscription of dependencies, then the code tries to iterate over `subbedDeps` which has not been added to yet.

**Comment by lynxbat** [comment]
Nice catch
