### ISSUE TITLE
Autoscaling using Heat and Snap metrics

### ISSUE THREAD

**Issue by jaiswalsanjeev** [intelsdi-x/snap#1212]
Is it possible to autoscale using Heat template and use snap metrics instead of Ceilometer alarms?

I did not see anything for autoscaling yet. Can someone let me know about this?

**Comment by IzabellaRaulin** [comment]
cc: @intelsdi-x/snap-maintainers, @intelsdi-x/plugin-maintainers

**Comment by andrzej-k** [comment]
Hi @jaiswalsanjeev, Would you be so kind to elaborate more on  use cases and flows you are interested in? 

When you say snap metrics - do you mean custom metrics provided by snap and available in Ceilometer, and Ceilometer emitting alarms for such custom metrics? Or would you rather see snap emitting alarms (to webhook or log) by observing metrics collected by Ceilometer? I'm assuming that you are not interested in changing Heat autoscaling much, correct?

I'm guessing (to be confirmed once we learn more about use cases) that we currently don't have out of the box solution for this - but that could be interesting feature.  Just to let you know we do have Ceilometer publisher plugin on our plugins wish list - https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md#wish-list and looking for a contributor :)

**Comment by jaiswalsanjeev** [comment]
Hi Andrzej,

I am interested in snap amitting alarms to webhook or log without using Ceilometer. My main usecase is for Heat autoscaling ,without using Celiometer. Currently , I am using other external monitoring agents –Zabbix/Consul etc to call webhooks for Heat and autoscaling , since we have issues with Ceilometer performance and have disabled it completely in our environment.

In our current production environment, we have disabled Ceilometer due to performance issues and problems with Ceilometer breaking RabbitMQ.

Question is: Can I just use snap emitting alarms for autoscaling by themselves without use of Celiometer?

Thanks,
[Description: cid:image003.png@01CE4CD0.6DA59600]

Sanjeev Jaiswal
VP – Cloud Operations
Reliance Jio Infocomm Limited.
Reliance Corporate Park, Bldg. No. TC23, 4B, 4th Floor, CA-04
Thane - Belapur Road, Ghansoli, Navi Mumbai - 400 701
Direct      : +91-22-44787507
Mobile    : +918452886027
E- mail    : sanjeev.jaiswal@ril.com<mailto:sanjeev.jaiswal@ril.com>

**Comment by andrzej-k** [comment]
Thanks @jaiswalsanjeev for this background. I did a quick check and it seems that autoscaling feature is no longer developed as part of Heat - there is a new project for this called Senlin. Here is a link to documentation about autoscaling support in Senlin: http://docs.openstack.org/developer/senlin/user/scenarios/autoscaling.html
I didn't do much research on it yet, but it seems it's not so heavily depending on Ceilometer, and it may be easier to use snap as metrics source. BTW. are you mainly scaling VMs or OpenStack services?

**Comment by jaiswalsanjeev** [comment]
Thanks Andrzej. I will look into Senlin and autoscaling with Aodh for alarming and snap metrics. I am looking at autoscaling VM’s.

[Description: cid:image003.png@01CE4CD0.6DA59600]

Sanjeev Jaiswal
VP – Cloud Operations
Reliance Jio Infocomm Limited.
Reliance Corporate Park, Bldg. No. TC23, 4B, 4th Floor, CA-04
Thane - Belapur Road, Ghansoli, Navi Mumbai - 400 701
Direct      : +91-22-44787507
Mobile    : +918452886027
E- mail    : sanjeev.jaiswal@ril.com<mailto:sanjeev.jaiswal@ril.com>

**Comment by andrzej-k** [comment]
Great - just let us know if you'd need any help with snap in this setup.

**Comment by andrzej-k** [comment]
Hey @jaiswalsanjeev - If you don't mind I'll close this issue. In case of any new questions let's start new discussion under new issue, ok?

**Comment by jaiswalsanjeev** [comment]
Yes, Thanks. Please close the issue.
