### ISSUE TITLE
plugins downloaded via the pluginCatalog dont work

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap#1216]
The plugin catalog typically use links to files in the form: 
https://s3-us-west-1.amazonaws.com/snap-plugins-linux-latest/snap-plugin-collector-cpu

Though the link suggests that the plugins downloaded should work with the **latest** snapd (currently 0.16.1), the plugins cant be loaded, returning the error

```
time="2016-09-19T04:06:20Z" level=error msg="error in getting metric types" _block=load-plugin _module=control-plugin-mgr error="gob: type mismatch: no fields matched compiling decoder for GetMetricTypesReply" plugin-type=collector 
time="2016-09-19T04:06:20Z" level=error msg="gob: type mismatch: no fields matched compiling decoder for GetMetricTypesReply" _block=start _module=control autodiscoverpath="/opt/snap/plugins" plugin=&{snap-plugin-collector-cpu 7377409 457 {63594994707 0 0x1333600} {50 63 1 33225 0 0 0 0 7377409 4096 14416 {1459397907 0} {1459397907 0} {1474257974 126781412} [0 0 0]}} 
```

**Comment by nanliu** [comment]
I didn't realize we had download link in the plugin catalog. I'm trying to track down the s3 repo, but currently they are not updated on new releases. For now please use the bundle in github release.

We are trying to move each plugin to it's own release schedule and they are expected to exist in:
```
https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/plugins/<plugin_name>/<sha1|version>/<os>/<arch>/<plugin_name>
```

We are updating the plugin release so that it will support latest version and latest build:
https://github.com/intelsdi-x/snap-pluginsync/pull/17

I will update the download link in the markdown file as we update this across the repos.

**Comment by woodsaj** [comment]
yes, i reverted to using the tarbal from the snap release, but being able to just download and load only the plugins I want would be great.   

Additionally all of the plugins in the plugin bundle appear to have been built with CGO and therefor dynamically linked. So they dont run in the alpine docker container from https://hub.docker.com/r/intelsdi/snap/ due to missing shared libraries.

**Comment by nanliu** [comment]
Status update, the gox -cgo flag is only enabled for libvirt/node-manager plugins, but for some reason everything is build with dynamic linked binaries. 

```
cgo enabled for libvirt
Number of parallel builds: 1
...
cgo disabled for file
Number of parallel builds: 1
```

I'm checking if CGO_ENABLED=0 will solve this.

**Comment by nanliu** [comment]
Took a while to track down, looks like CGO_ENABLED=0 is respected. I will update the tar.gz as soon as the build completes.

**Comment by nanliu** [comment]
I've updated the release tar.gz bundles, and I tracked down the s3 repos so I will update them shortly.

**Comment by nanliu** [comment]
The s3 repos are updated as well. If there's any issues, please post issues in those specific plugins github repo. I'm going to keep this issue open since we need to update the links in the plugin catalog with the new build artifacts that we are releasing continuously.

**Comment by mjbrender** [comment]
With @nanliu's updates, the Plugin Catalog has tested builds only. Thanks for catching this @woodsaj - let us know if you have another issue. Closing this ticket.
