### ISSUE TITLE
Error reported when plugin catalog is empty

### ISSUE THREAD

**Issue by marcin-krolik** [intelsdi-x/snap#1229]
Reproduction steps:
1. Start `snapd` eg. `snapd -t 0 -l 1&`
2. Check metric catalog (no collectors loaded) `snapctl metric list`

Results:
Snapctl reports error
```bash
$ snapctl metric list
Error getting metrics: metric catalog is empty, no plugin loaded
```
Snapd reports error
```bash
ERRO[2016-09-22T12:56:08+02:00] error fetching metrics                        _block=fetch _file=metrics.go, _module=control error=metric catalog is empty, no plugin loaded
```

This should not be reported as error, maybe just info, or warning?

During large tests `pytest` module checks snap output for any error, and fails the test if any error was found. While this could be easily changed to omit/discard errors returned by snapd, I think it's not beneficial to large tests in general

**Comment by lynxbat** [comment]
Yeah, this is not an error. Asking for a list of metrics should be able to return an empty list.
I wouldn't mention plugins at all in the response as it is not really relevant.

**Comment by geauxvirtual** [comment]
This is definitely a change in behavior with the merge of PR #1220. Prior to this PR, an empty list would be returned to snapctl, and snapctl would just print out the column headers.

**Comment by lynxbat** [comment]
Functionally a REST API call to a list can return an empty list without error.

Snapctl can be a bigger discussion. I would prefer maybe a "helper" message after the empty list that can say "Try loading a plugin first to get some metrics"

**Comment by IRCody** [comment]
I submitted a PR for this and opened #1233 to track improvements to snapctl dealing with empty lists for metrics/plugins.
