### ISSUE TITLE
Grpc error "received message length 9399375 exceeding the max size 4194304" when processing more then 10000 probes.

### ISSUE THREAD

**Issue by sandlbn** [intelsdi-x/snap#1238]
When I tried to collect metric from middle size cluster and process it using grpc2 I get a grpc error 
rpc error: code = 13 desc = grpc: received message length 9399375 exceeding the max size 4194304

**My workflow**
I have 100 machines and every vm is collecting around 200 different metrics. I tried to process metrics using some anomaly detection plugin, same happened when I switched to the different processor plugin.

**Proposed approach**
I think the easiest way is to expose maxMsgSize as an configurable value.  Right now snap uses 

`var defaultMaxMsgSize = 1024 * 1024 * 4
`

**Comment by IRCody** [comment]
@sandlbn: Are all 100 vm's going to the same instance of the anomaly detection plugin?

Also it would be helpful to link where the MaxMsgSize is coming from.

**Comment by sandlbn** [comment]
@IRCody sorry for a delay, but I just seen your message. Yes, I'm looking to use one processor in deployment, this could be helpful for people who want to run some kind on analytics and parse stream of data on the fly. MaxMsgSize is coming from https://github.com/grpc/grpc-go/blob/master/server.go#L110 .

**Comment by IRCody** [comment]
@sandlbn: That's ok. I created [this](https://github.com/intelsdi-x/snap-plugin-lib-go/issues/43) issue on the plugin-lib to expose those options to the plugin author.

It seems like if you're using existing plugins though you'd almost want to be able to expose it to the task creator? I'm not sure of a good way to do that. What do you think?

**Comment by kjlyon** [comment]
Hi @sandlbn, @IRCody opened [this](https://github.com/intelsdi-x/snap-plugin-lib-go/issues/43) issue to address your comment. This issue will be closed. Please leave any further comments on that issue.
