### ISSUE TITLE
Error 405 while using snapctl

### ISSUE THREAD

**Issue by rkd286** [intelsdi-x/snap#1241]
Please refer attachment:
![image](https://cloud.githubusercontent.com/assets/22471467/18870186/21fe2c6a-84cd-11e6-9e54-ef1f87dd4722.png)

**Comment by nanliu** [comment]
Seems like you have a jetty service rather than snapd is running on port 8181

**Comment by IRCody** [comment]
@rkd286: If you have snapd running on a different port you can use the `snapctl -u "http://localhost:<port>" plugin load snap-plugin-collector-mock1` to target it to a different port (or address).

**Comment by IRCody** [comment]
@rkd286: I'm going to close this but if you have more issues feel free to post another issue or respond here.
