### ISSUE TITLE
How do I create a 'collector' type task?

### ISSUE THREAD

**Issue by ldcastell** [intelsdi-x/snap#1243]
I'm trying to create a task for a collector plugin (in this case keystone plugin), but when I run:
`snapctl task create` passing my manifest file as parameter I get: `Error creating task:Plugin not found: type(processor) name(keystone) version(-1)`

I'm guessing it is because the keystone plugin is a collector, But I could not find in your documentation how to create a task for this type of plugin and the plugin Documentation is also wrong.

thanks!

**Comment by geauxvirtual** [comment]
Can you post the task manifest you are trying to pass to snap?

**Comment by ldcastell** [comment]
Sure!, here is it: http://pastebin.com/raw/G8ARZ0re

**Comment by geauxvirtual** [comment]
It looks like you are not processing any of the metrics, so you can simplify the task manifest to the following:

```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/openstack/keystone/total_tenants_count": {},
                "/intel/openstack/keystone/total_users_count": {},
                "/intel/openstack/keystone/total_endpoints_count": {},
                "/intel/openstack/keystone/admin/users_count": {}
            },
            "config": {},
            "tags": {},
            "publish": [
                {
                    "plugin_name": "file",
                    "config": {
                        "file": "/tmp/published_keystone"
                    }
                }
            ]
        }
    }
}
```

**Comment by ldcastell** [comment]
Thank you! that did the trick  :)
