### ISSUE TITLE
configurable plugin restart limit

### ISSUE THREAD

**Issue by krzysztofx** [intelsdi-x/snap#1246]
Hi

Would it be possible to expose currently hardcoded limit as a part of global configuration ? I mean MaxPluginRestartCount = 3  from control/runner.go . 
Since snap currently doesn't give any means for controlled plugin reload, that would be workaround for situations where plugin has to be restarted. 

Thanks

**Comment by IRCody** [comment]
@krzysztofx: It's definitely possible. I'd be interested to know if anyone else has run into this issue.

**Comment by obourdon** [comment]
@krzysztofx I'd be interested in knowing in which use cases this occurs and needs to be fixed

**Comment by krzysztofx** [comment]
Hi
I'm developing  some plugin for getting DPDK statics.  Brief picture is that collector plugin process attaches to primary DPDK process as  a secondary . When primary restarts for some reason, secondary has invalid memory handlers to common memory area, so it has to reintialize it . Unfortunatelly current DPDK libraries  implementation is lacking memory reinitialization routines, so the only and recommended way to reconnect with primary DPDK process is to restart secondary process and establish DPDK connectivity anew.  
Simplest workaround is to terminate snap collector plugin and expect snapd to resurrect it . So we need to extend or disable plugin restart limitation. 
I can  imagine more complex solution/feature  where plugin could request it's own renitialization from Snap core process, but I'm afraid it's not something that we can get  quickly.

Thanks
Krzysztof

**Comment by krzysztofx** [comment]
Hi 
@obourdon @IRCody 
Do you know if there's any chance for exposing that parameter in near future ?  

Thanks
Krzysztof

**Comment by bjray** [comment]
@krzysztofx - we are a bit short staffed over the holidays, and our next 2 weeks are already planned.  We will try to pull it in before the end of the year.

**Comment by mjbrender** [comment]
Hey @krzysztofx! Your request landed in master as of the PR mentioned above. Hope it helps you out! Let us know if you need it as part of our next public version of Snap or you're comfortable building from source.
