### ISSUE TITLE
List Snap maintainers

### ISSUE THREAD

**Issue by bjray** [intelsdi-x/snap#1261]
We want to provide an easy way for external contributors to know who our maintainers are, what packages they maintain and how to contact them.

One idea on how we do this is to provide a MAINTAINERS file in /docs that lists the maintainers along with their email and github id, similar to https://github.com/coreos/etcd/blob/master/MAINTAINERS. 

This aligns to #1155 and helps prepare for external maintainers

**Comment by nanliu** [comment]
This is related to #588.

**Comment by IzabellaRaulin** [comment]
Resolved by https://github.com/intelsdi-x/snap/pull/1311
