### ISSUE TITLE
Task moved to disabled state when system becomes too busy

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap#1268]
After exchanging on the subject in slack channel here are the details of this issue:

I am running a snapd instance with 12 plugins (amongst which cpu, df, disk, …) and collecting metrics from all of these each and every 10s. If I put my system under heavy load (using stress Linux CLI tool `stress -c 2 -t 90`) I suddendly hit this line in the code [https://github.com/intelsdi-x/snap/blob/master/control/available_plugin.go#L265](https://github.com/intelsdi-x/snap/blob/master/control/available_plugin.go#L265) with errors like (connection is shut down, unexpected EOF, …). I also tried to increase GOMAXPROC abd SNAP_MAX_PLUGINS but this did not seem change anything at all (not even postponing the issue).

As suggested by @lynxbat I also tried to overcome this by changing some default values in [https://github.com/intelsdi-x/snap/blob/master/control/available_plugin.go#L45](https://github.com/intelsdi-x/snap/blob/master/control/available_plugin.go#L45)

and as @lynxbat stated:

> I imagine the load is just too much for the health limits
> Snap isn't guaranteed to get priority for framework to plugin communication so under extreme stress the RPC calls could be in a wait state. Maybe try changing the health defaults to be more relaxed and see if it changes. I don't think these are exposed through config, but this might be the reason to do this now
> My guess is `DefaultHealthCheckTimeout` being higher would resolve this
> We are being pretty aggressive at 1 second
> Try setting to your task interval (10 secs)
> At some point Snap can't guarantee the RPC call since Linux scheduler is controlling it.
> We would have to use cgroups, core pinning, or something else to make sure it had interrupt priority. Maybe @connor would have something to recommend.
> I would be curious see to a chart of the response times. Maybe a metric we need to add is "snap" metrics on framework perf
> Would be useful and something we could optionally enable from the command line

As already investigated by @ConnorDoyle:

> At a first glance, the problem looks like @lynxbat described (you can see scheduling latency > health grace period). In the short term, you could try isolating “system” (snapd etc) processes using `numactl` or `cgexec`. We could make failure detection more tunable (something like [http://fubica.lsd.ufcg.edu.br/hp/cursos/cfsc/papers/hayashibara04theaccrual.pdf](http://fubica.lsd.ufcg.edu.br/hp/cursos/cfsc/papers/hayashibara04theaccrual.pdf)) but with sched latencies like you experienced you could still get false positives.
> Another thing that came to mind is that it could make sense to modulate health grace period by task frequency (e.g. for something that collects frequently we want to know sooner that it failed)

and @lynxbat:

> Maybe also implementing some of the backoff patterns. The Netflix Cass driver has some great ones.

**Comment by obourdon** [comment]
[perf_sched.txt](https://github.com/intelsdi-x/snap/files/518946/perf_sched.txt)
[lscpu.txt](https://github.com/intelsdi-x/snap/files/518947/lscpu.txt)

**Comment by IRCody** [comment]
I went ahead and added the files in-line to make it easier to see.

lscpu:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2399.996
BogoMIPS:              4799.99
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer xsave avx f16c rdrand hypervisor lahf_lm abm tpr_shadow vnmi flexpriority ept fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

perf_sched:
```
$ sudo perf sched latency --sort max
-----------------------------------------------------------------------------------------------------------------
  Task                  |   Runtime ms  | Switches | Average delay ms | Maximum delay ms | Maximum delay at       |
 -----------------------------------------------------------------------------------------------------------------
  lscpu:8676            |      5.939 ms |        3 | avg: 1950.448 ms | max: 5851.322 ms | max at: 294827.971448 s
  snap-plugin-col:(85)  |    405.388 ms |     4806 | avg:   87.014 ms | max: 5537.070 ms | max at: 294848.223291 s
  python:(14)           |   2093.672 ms |     7394 | avg:   50.547 ms | max: 5176.805 ms | max at: 294808.046617 s
  snap-plugin-pub:(23)  |    109.711 ms |     1321 | avg:   98.805 ms | max: 4401.605 ms | max at: 294829.935672 s
  snapd:(25)            |    311.192 ms |     4450 | avg:   42.914 ms | max: 4285.627 ms | max at: 294825.468356 s
  hyperkube:(35)        |   4620.547 ms |    54194 | avg:   10.313 ms | max: 4196.815 ms | max at: 294794.847677 s
  true:(25)             |    226.562 ms |     1728 | avg:   31.551 ms | max: 4091.281 ms | max at: 294802.225655 s
  influxd:(8)           |    518.084 ms |     5130 | avg:   48.697 ms | max: 3663.406 ms | max at: 294843.843407 s
  exe:(154)             |    102.662 ms |     4416 | avg:   17.173 ms | max: 3173.280 ms | max at: 294842.183127 s
  iptables-restor:(16)  |    150.702 ms |      109 | avg:   71.003 ms | max: 1721.301 ms | max at: 294811.195776 s
  sh:(14)               |     53.952 ms |       96 | avg:   93.263 ms | max: 1650.574 ms | max at: 294811.181167 s
  iptables:(84)         |    245.676 ms |      387 | avg:   48.392 ms | max: 1620.900 ms | max at: 294832.167014 s
  grafana-server:(8)    |     95.319 ms |      887 | avg:   38.686 ms | max: 1615.180 ms | max at: 294842.350334 s
  etcd:(22)             |   3328.395 ms |    44405 | avg:    8.354 ms | max: 1545.187 ms | max at: 294837.863629 s
```

**Comment by IRCody** [comment]
>As suggested by @lynxbat I also tried to overcome this by changing some default values in https://github.com/intelsdi-x/snap/blob/master/control/available_plugin.go#L45

Just for clarity, what values did you try?

**Comment by obourdon** [comment]
From the top of my head I think I tried 3 seconds and 5 times retry.

**Comment by IRCody** [comment]
Not that this is a permanent solution, but since the max-delay in your perf stuff is ~5 seconds would it make since to try 6 seconds?

>As already investigated by @ConnorDoyle:

>>At a first glance, the problem looks like @lynxbat described (you can see scheduling latency > health grace period). In the short term, you could try isolating “system” (snapd etc) processes using numactl or cgexec. We could make failure detection more tunable (something like http://fubica.lsd.ufcg.edu.br/hp/cursos/cfsc/papers/hayashibara04theaccrual.pdf) but with sched latencies like you experienced you could still get false positives.
Another thing that came to mind is that it could make sense to modulate health grace period by task frequency (e.g. for something that collects frequently we want to know sooner that it failed)

The issue with basing health checks off the task interval is that, unless you use sticky routing, there isn't a direct mapping between tasks and plugins. This means one plugin could be serving multiple tasks with varying intervals.

**Comment by IRCody** [comment]
@obourdon: Looking into this more, I think there is another issue that is built into the health checks for plugins. Even if the health check interval is changed from the snap side, the plugins are expecting health checks every 1.5 seconds and if it fails 3 ([here](https://github.com/intelsdi-x/snap/blob/master/control/plugin/session.go#L210) of them it kills itself. This value would also need to be changed for the other timeouts to matter.

**Comment by obourdon** [comment]
No more active on discontinued project
