### ISSUE TITLE
Try to understand performance behavior on plugin load operations

### ISSUE THREAD

**Issue by ericho** [intelsdi-x/snap#1270]
Hi, 

This is more a question than an issue. 
I'm experimenting with snap to get environmental data from an Intel Edison board. Basically what i'm doing is to build snap for 32 bits as well as the needed plugins. 

Since the first experiment running snap on this board I noticed some behavior in the plugin load procedure. If I load a plugin it takes some time to complete the operation, but if I load a second plugin then it fails due to a timeout. 

I saw that there is a timeout in the loadPlugin operations so I changed to 15 seconds, and now I'm able to load two plugins. I tried to load a third one and it failed due to the same timeout, so I changed to 30 seconds and it worked. 

The same thing happened with the `snapctl task create -t myfile.json` I needed to change another timeout in order to make it work. 

So, my questions are :smile:
- What could cause the performance behavior on plugin load? My thought is that every load operation should take (almost) the same amount of time. 
- Is there a way to avoid the plugin load operation? I mean if a put the plugins in a specific location is it possible to tell snap that these plugins "were" loaded?

I know that snap is not meant to run on this kind of platforms but still is fun to try it.
Thanks in advance!

**Comment by kindermoumoute** [comment]
> Is there a way to avoid the plugin load operation? I mean if a put the plugins in a specific location is it possible to tell snap that these plugins "were" loaded?
No, you can load a bunch of plugins in a specific location in the same time you run snapd with `-a` flag. But it's doing the same than loading one by one plugins.

> What could cause the performance behavior on plugin load? My thought is that every load operation should take (almost) the same amount of time.
Plugin are compressed when loaded, could this be a performance behavior on a platform such Edison? @IRCody 

> I know that snap is not meant to run on this kind of platforms but still is fun to try it.
This kind of feedback is welcomed, thank you!

**Comment by IRCody** [comment]
@ericho: Which plugins are you trying to load?

>What could cause the performance behavior on plugin load? My thought is that every load operation should take (almost) the same amount of time.

I'm wondering if the later ones were just a lot larger which caused it to take longer to be transferred/load. Other than plugin size I can't think of anything that should effect the load time so drastically.

**Comment by ericho** [comment]
I tried with ```snap-plugin-collector-mock1``` ```snap-plugin-processor-passthru``` ```snap-plugin-publisher-mock-file``` in different order of loading with the same result. 

The last experiment was with ```snap-plugin-processor-passthru``` ```snap-puglin-publisher-file``` and ```snap-plugin-collector-edison```. The last one is the one that I'm creating :smile:

Can plugins be loaded without compression? 
Snap has some benchmark option enabled? I think I can use cpubenchmark to try to see what is going on.

**Comment by kindermoumoute** [comment]
> Snap has some benchmark option enabled? I think I can use cpubenchmark to try to see what is going on.
No benchmark yet, but you can easily [create a flamegraph of the CPU use](https://github.com/intelsdi-x/snap/blob/master/docs/PROFILING.md), PM me on the [Slack channel](https://intelsdi-x.herokuapp.com/) if you need help for that.

**Comment by kjlyon** [comment]
Hello @ericho, It's been a while since we've heard from you. We are going to be closing this issue. If your problem still persists or if we didn't answer your questions, please feel free to open another issue or reach out to us on our [Slack channel](https://intelsdi-x.herokuapp.com/).
