### ISSUE TITLE
Get metric from tree still use `/` separator

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap#1273]
Calling the API on `/v1/metrics/*namespace` will call a `getMetricsFromTree`method, which use a deprecated `parseNamespace` function, that will split a namespace from the `/` separator.

See https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/server.go#L518-L526

@candysmurf @kjlyon it would be interesting to have the API test that, thoughts?

**Comment by candysmurf** [comment]
@kindermoumoute, this method never gets called. Look: https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/server.go#L471.

**Comment by kindermoumoute** [comment]
If the namespace is not defined, it's normal it fails. After loading a mock plugin:
```
curl http://localhost:8181/v1/metrics/intel/mock/bar
{
  "meta": {
    "code": 200,
    "message": "Metrics returned",
    "type": "metrics_returned",
    "version": 1
  },
  "body": [
    {
      "last_advertised_timestamp": 1476294245,
      "namespace": "/intel/mock/bar",
      "version": 1,
      "dynamic": false,
      "href": "http://localhost:8181/v1/metrics?ns=%2Fintel%2Fmock%2Fbar&ver=1"
    }
  ]
}
```

**Comment by candysmurf** [comment]
@kindermoumoute, do you mind to try this: curl http://localhost:8181/v1/*namespace to see if you get all metrics back?

**Comment by kindermoumoute** [comment]
`*namespace` is not a namespace, that's why it returns 404.

**Comment by candysmurf** [comment]
@kindermoumoute, I'm very confused by the syntax. Got it. It's the syntax of this library Snap uses: https://github.com/julienschmidt/httprouter.
