### ISSUE TITLE
Snapd Config Tags and Vars

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap#1280]
## Global Tags

**Proposition:** A configurable array of tags that are applied globally to any metrics collected by tasks scheduled on the snap agent. 
- Every metric collected and brought into the agent would have this tag appended, similar to how the `'plugin_running_on'` tag is currently applied to every collected metric
- It would exist in the config file supplied to snap upon startup and would look like this

```
"tags":{
    "foo":"bar",
    "krabby":"patty"
}
```
## Global Vars

**Proposition:** A key value pair array in the snapd config that could be accessed globally and could be inserted as dynamic variables within tasks that are loaded into the agent

Config  

```
"vars":{
    "foo":"bar",
    "krabby":"patty"
}
```

Task Example

```
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/mock/foo": {<% foo %>},
            },
            "config": {
                "/intel/mock": {
                    "password": "<% bar %>",
                }
            },
            "process": null
        }
    }
}
```

**Value:** The value in these two propositions is made more clear when viewed with respect to the use of Tribe. When using tribe a task manifest loaded into an agreement is shared across the tribe. This feature allows snapd agents to differentiate themselves from other members in terms of there collection/publishing configurations but at the same time allows them to leverage shared workflow made possible by the tribe

**Comment by IRCody** [comment]
@jtlisi: Can you talk about what this gets you that isn't currently supplied by the tags section described in this page: [Tasks.md](https://github.com/intelsdi-x/snap/blob/master/docs/TASKS.md).

**Comment by jtlisi** [comment]
Currently, if I load a task through a tribe agreement, the tags will be identical across every node in that agreement. This would allow for two snap agents to have unique tasks while sharing the same task workflow.

**Comment by lynxbat** [comment]
I just want to agree to this because of `"krabby":"patty"`...

**Comment by IRCody** [comment]
@jtlisi: Thanks for expanding on it, makes sense to me now.

**Comment by jackson-intel** [comment]
We are working on deploying some Intel collectors with SNAP. We would like the ability to dynamically define paths in config and setfiles using something like a $SNAPHOME environment variable. Perhaps this could work for us.

**Comment by jcooklin** [comment]
@jtlisi: [This](https://github.com/intelsdi-x/snap/pull/1431) PR adds interpolation of ENV variables before processing the task and the global config, as it exists, provides the ability to share a task with tribe but certain key/value pairs (config items) that are specific to the node.    

Do you think there is still a need for something like *Global Vars* that you describe above?  If not, I propose that this issue be modified to focus just on *Global Tags*.
