### ISSUE TITLE
graph in docs/PLUGIN_SIGNING.md needs to be updated

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap#1282]
Graph in docs/PLUGIN_SIGNING.md needs to be updated:

https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_SIGNING.md#how-it-works

**Expectations:** renaming Pulse to Snap

**Comment by mjbrender** [comment]
You're awesome @djbb7 👏
