### ISSUE TITLE
problem when load node-manager plugin on Haswell Ubuntu 14.04

### ISSUE THREAD

**Issue by doublechiang** [intelsdi-x/snap#1312]
Having problem tried to install plugin-node-manager on Intel Haswell powered server.
I can install the cpu/disk/meminfo plugin and collect information, however, when I tried to install node-manger plugin, it will fail with 
`Error loading plugin:
unexpected EOF`

The platform is Ubuntu 14.04.
I had followed the README, installed the ipmitool packages.
There is a problem, in my system there is no imp_msghandler module exist.
So I can only install 2 modules.

Any suggestion is very appreciated, thanks in advance.

`rsa@ubuntu:/lib/modules$ uname -r
3.13.0-88-generic`
`rsa@ubuntu:/lib/modules/3.13.0-88-generic$ find . -name ipmi*
./kernel/drivers/char/ipmi
./kernel/drivers/char/ipmi/ipmi_si.ko
./kernel/drivers/char/ipmi/ipmi_watchdog.ko
./kernel/drivers/char/ipmi/ipmi_poweroff.ko
./kernel/drivers/char/ipmi/ipmi_devintf.ko`
`rsa@ubuntu:/lib/modules/3.13.0-88-generic$ lsmod | grep ipmi
ipmi_devintf           17572  0
ipmi_si                53296  0`

**Comment by candysmurf** [comment]
@doublechiang, let me see if I can get utuntu 14.04 up and try it out.

**Comment by candysmurf** [comment]
@doublechiang, I tried node-manager plugin on Ubuntu 14.04. Unfortunately, I don't have IPMI modules, so I got a different error message. I opened an issue for it. Please refer to https://github.com/intelsdi-x/snap-plugin-collector-node-manager/issues/27

This issue may not cause by Snap. We can follow up on this later.

**Comment by PatrykMatyjasek** [comment]
Hi @doublechiang 
I've tested it at my ubuntu 14.04. Plugin is able to load even without modules loaded. But it returns empty list of metrics. Please try to run it with this config:
```
{
        "control":{
                "plugins":{
                        "collector":{
                                "node-manager":{
                                        "all":{ 
                                              "mode":"legacy_inband", 
                                              "channel":"0x00",
                                              "slave":"0x00"
                                                }
                                           }
                                     }
                         },
        }
}
```
If it won't help please report an issue at node-manager plugin repo

**Comment by doublechiang** [comment]
Thanks for the reply.
My config file /etc/snap/snapd.conf is as following, 
Thanks for the information that the plugin can be loaded without ilmi module loaded.

From the error message I assume it's related to the node-manager-plugin itself since I can install other plugin and running without problem.

`
{
    "log_level": 1,
    "control": {
        "cache_expiration": "1s",
        "plugin_trust_level": 0,
        "plugins": {
            "collector": {
                "node-manager": {
                    "all": {
                        "mode": "legacy_inband",
                        "channel": "6",
                        "slave": "0x2c"
                    }
                }
            }
        }
    },
    "restapi": {
        "enable": true,
        "https": false,
        "port": 8181
    }
}
`

**Comment by doublechiang** [comment]
@PatrykMatyjasek  
Thanks for the help, after I changed to channel and slave value back to default "0x00". the plugin can be loaded.
