### ISSUE TITLE
Defining Plugin Status

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#1322]
Not all plugins in the Plugin Catalog are as mature as others. Based on user discussion, I want to offer 3 status indicators that can be indicated in each plugin repository. 

**Updated Goal (1/17/17)** - provide support levels for plugins based on their maturity. 

--- 
~It should be clear if a plugin is known to run, known to *not* run or is somewhere in between.~

~Here they are:~
~**Stable** - This plugin is known to compile and run in the Snap framework. If you have any issues, please open an Issue.~
~**Not Working** - We’re not sure if this compiles or runs in the Snap framework. If you want to use it, please pick up open Issues and help it run again!~
~**Under Construction** - Master *should* compile and run in the Snap framework, but it may not work how you expect. See open Issues before using.~

**Comment by thomastaylor312** [comment]
`Not Working` seems a little misleading. Trying to think of a better option

**Comment by IRCody** [comment]
`Unstable`?

**Comment by candysmurf** [comment]
Shouldn't all published plugins run?:-) Highlight on the platform dependencies?

**Comment by thomastaylor312** [comment]
I like @IRCody's. `Stale` could also be an option, but I am not sure if that has a more negative connotation

**Comment by mjbrender** [comment]
I originally used `Broken`, to clarify the assumption that it once worked and is not now running in an e2e test (whether manual or automated). @candysmurf the catalog goal is to share all plugins that can be used or contributed to. Sometimes that means it won't work, especially as dependencies change.

**Comment by candysmurf** [comment]
refactoring or upgrading

**Comment by thomastaylor312** [comment]
@mjbrender I think broken would be good because like you said, we need to have something that indicates that it did work at some point but it might not now

**Comment by bjray** [comment]
For "Not Working", could we use something related to "Broken - Help Wanted"?

**Comment by mjbrender** [comment]
"Broken" is the clear winner with an emphasis on the help others can offer up. Thanks everyone who hopped in 👍

**Comment by mjbrender** [comment]
Opening this back up so I can close it with a PR to PLUGIN_AUTHORING.md.

**Comment by mjbrender** [comment]
There's some questions about the term "Stable." It's a little too strong. Maybe something that clarifies that it's known to work would be sufficient, like "Working". 

The point of these categories is to clarify whether or not a user should trust a plugin to run appropriately.

**Comment by mjbrender** [comment]
At the advice of @nanliu, we're going toward a different set of terms: Supported and Approved, with others in the plugin catalog being unlabeled to imply it hasn't hit one of those maturity levels yet. I'm drawing the matrix now and will include it in a PR that fixes this issue.

**Comment by candysmurf** [comment]
@mjbrender, what differences between supported and approved? Supported seems easy to understand. What about "approved"?

**Comment by mjbrender** [comment]
@candysmurf definitely important to clarify. I have a branch that's outlining those requirements. More definition to come, but check it out so far: https://github.com/mjbrender/snap/blob/tiering/docs/PLUGIN_STATUS.md#plugin-status-matrix
