### ISSUE TITLE
snapd daemon not running

### ISSUE THREAD

**Issue by rkd286** [intelsdi-x/snap#1335]
I am unable to run the snapd daemon. Tried several times.
![snapd](https://cloud.githubusercontent.com/assets/22471467/20056991/fdc0c7d8-a50e-11e6-8df5-a87a0ff5f3e6.png)

**Comment by geauxvirtual** [comment]
It does look like snapd is running as the prompt is not returning. The default log level for snapd is `warning` or `3`, so only warning messages would be printed to stdout. You can try running snapd with `snapd -t 0 -l 1` for debug logging or `snapd -t 0 -l 2` for info logging and more log messages should be printed to stdout.

**Comment by nanliu** [comment]
Another possibility, if you installed snap as a package, the default log location is `/var/log/snap/snapd.log`, so there will be no output to stdout. Try `snapd -t 0 -l 1 -o ''` to redirect logs to stdout, or check the log file for output.

**Comment by mjbrender** [comment]
@rkd286 yeah, +1 to @nanliu's point. How did you install Snap? If you did as a package, output will be in `/var/log/snap/snapd.log` and you'd want to interact with Snap using the service commands (like `systemctl start snap-telemetry` for 16.04) [explored here](https://github.com/intelsdi-x/snap#running-snap).

Let me know if that helps! Thanks for jumping in and using Snap - we're excited here. 

Side note: If you want to see how we're progressing on running with Windows, jump into the #snap-windows Slack channel: http://slack.snap-telemetry.io/

**Comment by nanliu** [comment]
I'm closing this issue since there hasn't been any updates. Please feel free to reopen, or reach out on our slack channel if you need further assistance debugging this.
