### ISSUE TITLE
Event Endpoint / Streaming Feature Spec

### ISSUE THREAD

**Issue by lynxbat** [intelsdi-x/snap#136]
Summary:
[Scheduler Tasks](https://github.com/intelsdi-x/pulse/blob/master/scheduler/task.go#L17) collect metrics and execute workflow based on a schedule. This is polling or sampling a data point on a [schedule](https://github.com/intelsdi-x/pulse/blob/master/scheduler/schedule.go#L10) and then performing workflow upon it. A very different feature is the ability to subscribe to an source of data that emits a stream of events and perform a workflow on one or many of these events. This spec names these new data sources `event endpoints` and the events that can be collected an `event stream`.

A metric namespace looks like:
`/system/cpu/load` (this is a metric that has to be collected on a schedule)

An event endpoint would look like:
`/system/docker/events` (this is an event stream, it needs to have a subscription)

Core module responsibilities:
__Scheduler__ - creates, reports, manages `event endpoint subscriptions`, receives `event streams` and fires a workflow.
__Control__ - ensures plugins for `event endpoints` are started, subscribes to `event endpoint`, collects events into `event stream`, sends to Scheduler with subscription ID.

Scheduler would own the active Subscriptions just like it owns Tasks.

Possible Flow:
 1. User/MGMT to Scheduler - please subscribe to` /foo/bar/events` with the time window of 1 second and maximum `event stream` default

 2. Scheduler to Control - subscribe to `event stream` with config
 3. Control:
    1. ensures plugin for `event endpoint` is available (running) and binds subscription ID to this plugin
    2. subscribes to `event endpoint` within available plugin and wires to `event endpoint listener` on control
 4. Plugin event endpoint
    1. starts `event endpoint collection` (triggered or polling with index)
    2. `event endpoint collection` triggers on time window or maximum event parameters and calls `event endpoint listener` API on control with `event stream`.
 5. Control
    1. receives `event stream` on `event endpoint listener`
    2. correlates `event stream` to the subscription
    3. calls Scheduler with `event stream` data
 6. Scheduler -
    1. receives `event stream` from Control
    2. fires workflow with `event stream` data

Example functions

Scheduler:

```go
CreateEventStreamSubscription(e eventStream, wf workflow, timeWindow time.Interval, maxEvents int) EventStreamSubscription {
/*
* eventStream - the event stream to subscribe to
* workflow - the workflow to perform on the event(s)
* timeWindow - optional window of time to collect events from the event stream before triggering workflow
* maxEvents - optional high water mark
*/
}
```

Collector Plugin:
```go
es := NewEventStream{}

e1 := NewEvent{
	Key: "facter-value-change",
	Property: "disks",
	Value: 5,
}
e2 := NewEvent{
	Key: "facter-value-change",
	Property: "disk-space",
	Value: "200GB",
}	
es.AddEvents(e1, e2)
err := EventListener.Send(es)	
```

Taxonomy:
* event endpoint - a source of data that can be subscribed to receive events. It is provided by a collector plugin.
* event stream - a collection of ordered events that have been received from an event endpoint.
* event listerner callback - a callback endpoint on the Control module that can receive event streams from a collector plugin.
* event subscription - a contract for a collector plugin to collect and send event streams to a subscriber. A subscription has a unique ID.

### Additional considerations
* Event streams should have an index per event that is maintained over the subscription

**Comment by mjbrender** [comment]
Hey @intelsdi-x/snap-maintainers - I cleaned this up based on new labels. I haven't seen it picked up in the backlog, so marketing as on hold.

**Comment by lynxbat** [comment]
This is a required feature per me @mjbrender. Not on the current release list but we need to keep it.

**Comment by mjbrender** [comment]
@lynxbat thanks for that detail. I'm using labels to keep our issues clear.

**Comment by candysmurf** [comment]
This seems a very good feature for Redfish plugin. They like event-driven data collection.

**Comment by lynxbat** [comment]
We have decided to rewrite a new version of this RFC. Closing this one ahead of that.
