### ISSUE TITLE
[question] What are the currently-supported Snap releases?

### ISSUE THREAD

**Issue by rji** [intelsdi-x/snap#1364]
I apologize if this question has been asked before, but I couldn't find it readily accessible in the docs or the readme. Is there a list or policy on how long a particular Snap version is supported? Specifically, as a plugin maintainer, I'm curious if it's safe to assume that I should be testing with `snap-latest` and `snap-latest - 1`.

Follow-up question: it appears that `-beta` has been dropped from the release version beginning with v0.17. Is the API considered stable at his point, and is it enough to test against `0.latest` until the major version is bumped?

**Comment by kindermoumoute** [comment]
> Follow-up question: it appears that -beta has been dropped from the release version beginning with v0.17. Is the API considered stable at his point, and is it enough to test against 0.latest until the major version is bumped?

Everything <1.0.0 is still beta.

**Comment by kindermoumoute** [comment]
> Is there a list or policy on how long a particular Snap version is supported? Specifically, as a plugin maintainer, I'm curious if it's safe to assume that I should be testing with snap-latest and snap-latest - 1.

Not AFAIK.

**Comment by jcooklin** [comment]
The API isn't changing between now and 1.0 which will land before the end
of the year.

**Comment by rji** [comment]
Thanks!
