### ISSUE TITLE
Is it normal that after restart tasks dissapear ?

### ISSUE THREAD

**Issue by hostingwalk** [intelsdi-x/snap#1366]
service snap-telemetry restart

and after that:
[root@server1 ~]# snapctl task list
No task found. Have you created a task?

**Comment by kindermoumoute** [comment]
Yes, stoping the daemon stop every task.

**Comment by mjbrender** [comment]
+1 to what @kindermoumoute said @hostingwalk. If you would like to persist your tasks between restart, you will need to save the Task Manifest and load at start. We have discussed an auto-load folder similar to how we automatically load plugins in `opt/snap/plugins` ([reference](https://github.com/intelsdi-x/snap/blob/master/docs/SNAPTELD_CONFIGURATION.md#snapteld-control-configurations)), but I don't believe that's been written up. 

Recall you can export running tasks after you create them with `snapctl task export <task_id>`, which is helpful if you didn't already have a Task Manifest around. 

Does that help you out?

**Comment by mjbrender** [comment]
You know what, I completely forgot you can save Task Manifests in the same `auto_discover_path` location set in the configuration file. You can read through [details here](https://github.com/intelsdi-x/snap/blob/master/docs/SNAPTELD_CONFIGURATION.md#restarting-snapteld-to-pick-up-configuration-changes).

**Comment by mjbrender** [comment]
Hey again @hostingwalk - given this is known behavior (Snap won't persist plugins or tasks upon reboot) and you know about the `auto_discover_path` functionality now, I'll close this issue. Feel free to open a PR for any documentation you think would have helped you know this earlier. 

Thanks so much for asking your question!
