### ISSUE TITLE
Is there any Collector-Plugin for collecting the data from the database in the desktop?

### ISSUE THREAD

**Issue by PraveenkumarDonga** [intelsdi-x/snap#1392]
Thanks,
Praveen.

**Comment by kindermoumoute** [comment]
Hi Praveen, what Desktop database are you thinking?

**Comment by PraveenkumarDonga** [comment]
Hi! kindermoumoute, 
I am planing to have mongodb.
is there any way to import the data to from files like .csv and .xls fomat

Thanks!

**Comment by sandlbn** [comment]
@PraveenkumarDonga  I have a great news for you. We have a brand new collector for mongodb, you can check it here https://github.com/intelsdi-x/snap-plugin-collector-mongodb/ .

**Comment by kindermoumoute** [comment]
Seems there is a follow up of the discussion in https://github.com/intelsdi-x/snap-plugin-collector-mongodb/issues/5
