### ISSUE TITLE
mock2-grpc (collector): namespaces not updated in GetConfigTypes

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap#1393]
https://github.com/intelsdi-x/snap/blob/master/plugin/collector/snap-plugin-collector-mock2-grpc/mock/mock.go#L159
Namespaces used there does not match declared ones.

**Comment by IRCody** [comment]
@lmroz: To clarify - The configPolicy is being set for a namespace that is not advertised directly via GetMetricTypes. From looking at it I would expect the result to be that the config is just never applied.

Aside from fixing this specific test plugin, is there additional validation that can be done from the framework perspective to alert/warn users about this issue?
