### ISSUE TITLE
GRPC based collectors **must** provide LastAdvertisedTime or framework panics

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1394]
The client call to GetMetricTypes sets the LastAdvertisedTime ([here](https://github.com/intelsdi-x/snap/blob/master/control/plugin/client/grpc.go#L256)) but this doesn't happen for the collect call.

**Comment by IRCody** [comment]
@jcooklin: Would a good resolution for this be to add some additional checks in the loop in [ToCoreMetrics](https://github.com/intelsdi-x/snap/blob/master/control/plugin/client/grpc.go#L299-L305) that sets LastAdvertisedTime (and I think potentially other fields) if they are not set by the plugin-lib? This would transparently apply to collect and GetMetricTypes and lets us remove the extra loop that is doing this check in GetMetricTypes.
