### ISSUE TITLE
SNAP about Machine Check

### ISSUE THREAD

**Issue by FionaLi1990** [intelsdi-x/snap#1401]
If the SNAP provides plug-in about Machine Check? If not,why?Do SNAP or Intel have the plan about MC？

**Comment by jcooklin** [comment]
@FionaLi1990 if you are referring to http://www.mcelog.org then yes there are plans to work on this plugin soon.

**Comment by mjbrender** [comment]
@FionaLi1990 to answer the other part of your question, we prioritize plugins based on use cases. Could you elaborate a bit on your interest in Snap + Machine Check? I'm especially curious how you use the error handling to troubleshoot. If you prefer to answer privately, email me: matthew [.] brender `@intel`.com. 

We don't have this slotted to start just yet, so let us know if you start one! We have a lot people playing with plugins in [our Slack channel](http://slack.snap-telemetry.io) these days that would be happy to help.

**Comment by kjlyon** [comment]
Hi @FionaLi1990 thank you for reaching out to us. Is http://www.mcelog.org what you're looking for? If it is, we would love to hear your comments and any ideas you have for that plugin. If not, can you provide us with some more details on what you're asking?

**Comment by kjlyon** [comment]
Hi @FionaLi1990, we haven't heard from you in a while. Due to lack of response, I will be closing this issue. Please reach out to us here or on [our Slack channel](http://slack.snap-telemetry.io/) to open this issue again or raise another question. Thank you.
