### ISSUE TITLE
Website: Bad Link

### ISSUE THREAD

**Issue by mattttt** [intelsdi-x/snap#1408]
Couldnt find a public repo for the snap-telemetry.io website, so apologies if this is the wrong place to post. 

The link within the "Active Community" section is broken, mistakenly including a trailing parenthesis:
![screenshot_2016-12-02_14_30_07](https://cloud.githubusercontent.com/assets/2886187/20847452/1d34bdfe-b89c-11e6-966b-d37eb4727a00.png)

`https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md)` should be `https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md`

**Comment by IRCody** [comment]
Thanks for pointing this out @mattttt. I submitted a PR for it so it should be fixed soon!
