### ISSUE TITLE
Plugin Wanted: Publisher for Elasticsearch or logstash

### ISSUE THREAD

**Issue by ldktta** [intelsdi-x/snap#1428]
Plugin Wanted: Publisher for Elasticsearch or logstash

**Comment by kindermoumoute** [comment]
@ldktta an Elasticsearch publisher is already in the wishlist gh issue https://github.com/intelsdi-x/snap/issues/1413. AFAIK the plugin development is currently in progress.

**Comment by mjbrender** [comment]
Hey @ldktta! So glad you want to use Snap. As @kindermoumoute mentioned, we have a wishlist issue so this is a duplicate so closing this one makes sense. 

Could you give a +1 over on the other issue and mention what specifically you want to measure? The more we understand what people want to measure here, the better we'll make the plugin. #1413
