### ISSUE TITLE
RDT metrics collector

### ISSUE THREAD

**Issue by ss7pro** [intelsdi-x/snap#1436]
We need to start collecting RDT related metrics to take advantage of them when enabling IA in multiple OpenSource cloud solutions. Our main focus should be on the RDT interface exposed targeted to be delivered in 4.10 kernel and missing features should be extracted using user space tools. More documentation can be found here:

https://github.com/01org/intel-cmt-cat/blob/master/README#L195

@skonefal

**Comment by andrzej-k** [comment]
@ss7pro Thanks for bringing this up.
Looking at RDT SW enabling status, it seems that Linux perf could be a good way to get per core, per task, CMT and MBM metrics using one tool. This requires kernel 4.6+ and perf enabled on the host, but apart from this there should be no other SW dependencies.
So I think that we could try to revisit our perf plugin and update it with new metrics. Would that work for you?

**Comment by ss7pro** [comment]
I would try to extract as much as we can from /sys and before introducing dependency for other tools. You can find a good overview hot RDT support is going to be implemented in libcontainer:

https://github.com/opencontainers/runc/issues/433

**Comment by andrzej-k** [comment]
Agree on reducing dependencies - and when libcontainer will support RDT it will be probably preferable way of gathering CMT, MBM metrics. I was thinking about using perf as it also allows to gather per task metrics (as opposed to https://github.com/01org/intel-cmt-cat)
Let's sync offline on your usecases first, and then decide on how to design plugin.

**Comment by mjbrender** [comment]
Just a heads up @ss7pro / @andrzej-k - there's discussion starting up next week with someone more familiar with RDT on writing a plugin. Keep up the open conversation on what you want to see and I'll share what we learn.

**Comment by ss7pro** [comment]
Can we setup a bridge for this discussion so I can join ?

**Comment by lynxbat** [comment]
@ss7pro @andrzej-k @mjbrender lets move RDT discussion off Github. Agreed we should have @ss7pro be a part of it.

**Comment by skonefal** [comment]
Hello @ss7pro,

Feel free to take https://github.com/intelsdi-x/snap-plugin-collector-rdt !

**Comment by IzabellaRaulin** [comment]
@skonefal, thank you for your contribution. In this PR #1664 the rdt collector will be added to plugin catalog to be more visible to everyone!
