### ISSUE TITLE
Plugin Wanted: Entropy collector

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#1439]
When application is using /dev/random and there is no entropy available in the system it may cause application to block waiting on more randomness.
The most obvious example of applications using entropy are security related (like TLS).

How about creating an entropy collector plugin which will indicate how much entropy is available in the system?

From the design perspective it can just expose one metric (entropy_available), whose value is populated from /proc/sys/kernel/random/entropy_avail.

**Comment by davecaplinger** [comment]
I agree that reading /proc/sys/kernel/random/entropy_avail should be easy; however, for the use case you mentioned ("security needs entropy, so we should monitor it"), you may find this discussion interesting: http://www.2uo.de/myths-about-urandom/

**Comment by andrzej-k** [comment]
Hey @davecaplinger Thanks for the link, very informative.
But I think we can try to help those using applications talking to (blocking) /dev/random to discover potential issues with depleting entropy. And we can do this by exposing entropy_avail metric. I think there is still a number of such applications.

**Comment by nanliu** [comment]
Entropy Plugin: https://github.com/janczer/snap-plugin-collector-entropy
