### ISSUE TITLE
How Snap collect cpu statistics?

### ISSUE THREAD

**Issue by subhabratamallick** [intelsdi-x/snap#1446]
I have gone through several collector plugins. What I see there is a structure and data is coming through it. Can you please tell me from exactly where or by running which scripts you are collecting cpu statistics?

**Comment by marcin-krolik** [comment]
Hi @subhabratamallick Maybe visiting [plugin catalog](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md) will help? You can find all plugins there, also these collecting cpu metrics like CPU collector. Each plugin have it's own documentation which brings information how metrics are acquired. Hope it helps

**Comment by kjlyon** [comment]
Hello @subhabratamallick, we have an issue open to address this, #1517. This feature request will help address your issue faster and reduce amount of time searching through documentation of many plugins. If you have ideas on implementation, or want to add more to the issue described, feel free. We welcome all contribution!
