### ISSUE TITLE
When plugin load fails, the snaptel message should convey information about failure reason from plugin

### ISSUE THREAD

**Issue by skonefal** [intelsdi-x/snap#1466]
I have tried to load PCM plugin.
```
skonefal@ubuntus  ~/dev/go/bin  snaptel plugin load snap-plugin-collector-pcm 
Error loading plugin:
timed out waiting for plugin snap-plugin-collector-pcm
```
To see what was the **real** reason, I had to look at snapteld logs:
```
INFO[2017-01-11T10:06:20+01:00] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-pcm
DEBU[2017-01-11T10:06:20+01:00] plugin load timeout set to 3s                 _block=load-plugin _module=control-plugin-mgr path=[snap-plugin-collector-pcm]
DEBU[2017-01-11T10:06:20+01:00] Unable to find PCM.  Ensure it's in your path or set SNAP_PCM_PATH.panic: exec: "pcm.x": executable file not found in $PATH  _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00]                                               _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00] goroutine 1 [running]:                        _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00] panic(0x746ec0, 0xc4200d1700)                 _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00]         /usr/local/go/src/runtime/panic.go:500 +0x1a1  _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00] github.com/intelsdi-x/snap-plugin-collector-pcm/pcm.(*PCM).run(0xc42013c090, 0x0, 0xc42013c0c0)  _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00]         /home/skonefal/dev/go/src/github.com/intelsdi-x/snap-plugin-collector-pcm/pcm/pcm.go:120 +0x57c  _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00] github.com/intelsdi-x/snap-plugin-collector-pcm/pcm.NewPCMCollector(0x0, 0x0, 0x0)  _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00]         /home/skonefal/dev/go/src/github.com/intelsdi-x/snap-plugin-collector-pcm/pcm/pcm.go:105 +0xf9  _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00] main.main()                                   _module=plugin-exec io=stderr plugin=
DEBU[2017-01-11T10:06:20+01:00]         /home/skonefal/dev/go/src/github.com/intelsdi-x/snap-plugin-collector-pcm/main.go:31 +0x26  _module=plugin-exec io=stderr plugin=
ERRO[2017-01-11T10:06:23+01:00] load plugin error when starting plugin        _block=load-plugin _module=control-plugin-mgr error=timed out waiting for plugin snap-plugin-collector-pcm
ERRO[2017-01-11T10:06:23+01:00] timed out waiting for plugin snap-plugin-collector-pcm  _module=_mgmt-rest
DEBU[2017-01-11T10:06:23+01:00] Removing file (/tmp/966588086/snap-plugin-collector-pcm)  _module=_mgmt-rest
DEBU[2017-01-11T10:06:23+01:00] API response                                  _module=_mgmt-rest index=17 method=POST status=Internal Server Error status-code=500 url=/v1/plugins
```

Please consider printing error content from plugins in CLI so that problem debugging would be easier.

The `panic: exec: "pcm.x": executable file not found in $PATH` was the error content - It would be convenient to print it in CLI.

**Comment by IzabellaRaulin** [comment]
@skonefal, I agree it would be more user-friendly and make working with Snap easier. I think this might be treat as an enhancement, so I will add an appropriate label to this issue.

**Comment by IzabellaRaulin** [comment]
I am sorry, I did not notice before that for this case some panic occures. Maybe it's an issue for pcm plugin to handle this in a different way than currently. I will check this and let you know.

**Comment by skonefal** [comment]
The panic is just side effect. I think the problem here is the fact that CLI does not print error message from plugin.
If all plugins returned proper error content in `err` which would be printed in CLI, then it would be awesome, because I would know that `"pcm.x": executable file not found in $PATH` which is what I exactly need.

**Comment by IzabellaRaulin** [comment]
@skonefal, not printing an error message is related to how a plugin handles errors in this case of snap-plugin-collector-pcm there was called `panic(err)`, so only logs contain useful information what happened. 
For sure, this is pcm-plugin's issue, so I opened https://github.com/intelsdi-x/snap-plugin-collector-pcm/issues/33 to improve the plugin load error messages. Also, prepared a pull request https://github.com/intelsdi-x/snap-plugin-collector-pcm/pull/34 with required changes to fix that - @skonefal, please look on that and put your comment there.  

It looks like this issue can be closed because of moving it to https://github.com/intelsdi-x/snap-plugin-collector-pcm.

**Comment by madhutummi** [comment]
Hi @skonefal, tried using snap-plugin-collector-pcm and I am getting "GetMetricTypes call error : exec: "pcm.x": executable file not found in $PATH"
pcx.x excutable is working on the system and I have exported pcm binary path appropriately but still it fails with the above error.

can you please help me to resolve this issue.

Thanks
Madhu

**Comment by madhutummi** [comment]
Typo in previous comment it should be pcm.x

**Comment by PatrykMatyjasek** [comment]
This plugin needs root permissions. Make sure that $PATH is visible in root space. If you're loading it as a user, try sudo -E

**Comment by madhutummi** [comment]
Hi @PatrykMatyjasek, can you please help on this issue as I am new to snap.

Thanks
Madhu

**Comment by PatrykMatyjasek** [comment]
@madhutummi could you join to our slack? It will be easier to help you on this.

**Comment by madhutummi** [comment]
@PatrykMatyjasek sure I will join the slack, send me the slack group info or the link

**Comment by PatrykMatyjasek** [comment]
@madhutummi https://intelsdi-x.herokuapp.com/

**Comment by madhutummi** [comment]
Thanks @PatrykMatyjasek  for helping in fixing the issue.
