### ISSUE TITLE
Task Storage

### ISSUE THREAD

**Issue by uwe42** [intelsdi-x/snap#1471]
Hi,

i was wondering, with version 1.0 and the deb packages, there is the possibility to enable snap (to load on boot), but previews running tasks dose not get stored or restarted. This has to be done by hand, i think. Would it be possible to add a task Storage where i can enable task that gets started as soon as snapd has loaded all plugins?

**Comment by andrzej-k** [comment]
Hi @uwe42,
I think you may want to take a look at: https://github.com/intelsdi-x/snap/blob/master/docs/SNAPTELD_CONFIGURATION.md#restarting-snapteld-to-pick-up-configuration-changes, especially last sentence:
> ... any plugins in the auto_discover_path will be automatically reloaded and any tasks in that same auto_discover_path will be automatically restarted when the when the snapteld process restarts in response to a SIGHUP signal.

**Comment by uwe42** [comment]
Ah seams that i missed that. That will work. Thanks for your help.
