### ISSUE TITLE
Plugins should have target for launching all tests

### ISSUE THREAD

**Issue by skonefal** [intelsdi-x/snap#1472]
Default plugin Makefile template does not have target `test-all` like snap framework does. (Example: https://github.com/intelsdi-x/snap-plugin-collector-perfevents/blob/master/Makefile)

As a plugin developer I want to check easily if the plugin tests pass so that I know that my code works.
Current flow requires me to do:
```
make test small
...(waiting)
make test medium
...(waiting)
make test large
...(waiting)
make test legacy
...(waiting)
````
Or create my own bash scripts with pipefails.

I would like to run all of them through single makefile target.

---

**As a side note:**
When I came to new code with Makefile I usually try to do `make`, `make build`, `make test`.
In snap, when I run `make test` I'm informed that I need some variable to run test which makes it jittery experience, compared to other projects.
Please consider `make test` do the `make test-all` responsibility for more seamless developer experience when immersing into snap.
If you consider this point valid, please let me know and I will open new issue.

**Comment by candysmurf** [comment]
@skonefal, I see "test-all" in current Snap master, would you please clarify your suggestion?

**Comment by skonefal** [comment]
I mean the plugins. Plugin's Makefile template does not have `test-all` target.
Example: https://github.com/intelsdi-x/snap-plugin-collector-perfevents/blob/master/Makefile

**Comment by candysmurf** [comment]
@skonefal, please open this issue in relevant plugin repos.  thanks.

**Comment by skonefal** [comment]
Thank you, I have opened an issue in pluginsync repo (https://github.com/intelsdi-x/snap-pluginsync/issues/53). All plugins should have similar build configuration, right?
I think we can close this issue.

**Comment by IRCody** [comment]
@skonefal: Closing this issue since it's getting addressed in pluginsync.
