### ISSUE TITLE
Configure the TempDir where the API loads plugins.

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap#1494]
One issue we are facing with loading plugins through the api is that the temporary directory which houses the temporary files is not configurable in snapteld's configuration. 

I noticed on line 192 of [mgmt/rest/v1/plugin.go](https://github.com/intelsdi-x/snap/blob/8080135b12e250cdba74937d679fa767d9c3e5ac/mgmt/rest/v1/plugin.go#L192)
the function `writeFile` uses the the ioutil.TempDir function: 
```golang
func writeFile(filename string, b []byte) (string, error) {
	// Create temporary directory
	dir, err := ioutil.TempDir("", "")
        ...
```

ioutil.TempDir defaults to the TMPDIR env variable or to `/tmp` directory if it is not set. I was hoping it could default to either a directory in `/opt/snap/` or be configurable in the snapteld configuration.

Let me know what you guys think.

Thanks!

**Comment by kindermoumoute** [comment]
I like the idea and it would be trivial to implement a temps path in the query - /v2/plugins?tmpPath=myTempPath

What do you think if we add this feature to the version 2 of the API? ([writeFile in v2](https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/v2/plugin.go#L209))

**Comment by jtlisi** [comment]
That would be perfect!

**Comment by jtlisi** [comment]
@kindermoumoute Would this also work if a plugin is loaded through the tribe?

**Comment by kindermoumoute** [comment]
AFAIK, yes.

However, Tribe is not implemented in [v2 routes](https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/v2/api.go#L60-L78) yet. The reason of that is Tribe is still beta, and we might have a different approach on the API for the next version.

That's why it will take some time before this feature work with Tribe.
