### ISSUE TITLE
--auto-discover option needs better documentation

### ISSUE THREAD

**Issue by kciepluc** [intelsdi-x/snap#1499]
SNAPTELD documentation page lacks proper explanation of --auto-discover option. The option description is "Auto discover paths separated by colons", but doesn't say anything about the purpose.
There is a single example below with "snapteld --auto-discover /opt/snap/plugins/" line suggesting this option might be used to automatically load plugins, but that's all.

In the SNAPTELD_CONFIGURATION page at the end there is a comment on restarting snapteld process and it says that not only plugins in the auto_discover_path will be reloaded, but also tasks! (which wasn't mentioned anywhere else).

And there is the TASKS page which doesn't say anything about auto-discovery and auto-loading tasks at all.

I guess that auto-loading tasks feature was added later and documentation wasn't properly updated...
Anyway, I suggest adding an explanation of --auto-discover option on the SNAPTELD page with additional examples (with comments) showing clearly it migt be also used for auto-loading tasks.

Additionally, the TASKS page should also be updated with the proper information regarding auto-loading tasks.

**Comment by nanliu** [comment]
Yeah this isn't documented very well. We should change the default config to use two directories: one for tasks, the other for plugins:

```
# Control sections for configuration settings for the plugin
# control module of snapteld.
control:
  # auto_discover_path sets a directory to auto load plugins and tasks on the start
  # of the snap daemon
  auto_discover_path: /opt/snap/plugins:/opt/snap/tasks
```

**Comment by nanliu** [comment]
We also could use some community contributions deploying Snap with configuration management tools. I feel like this would avoid having everyone reinvent/rediscover good defaults/best practices.

For example, this could be one way take advantage of this setting to load tasks/plugins (with purging support of obsolete tasks/plugins) in Puppet:

```puppet
define snap::plugins(
  $version,
) {
  $url = "https://github.com/intelsdi-x/${name}/releases/download/${version}/${name}_linux_x86_64"
  archive { "/opt/snap/plugins/${name}":
    mode   => '0755',
    source => $url,
    notify => Service['snap-telemetry'],
  }
}

define snap::task(
  $settings,
) {
  file { "/opt/snap/tasks/${name}.yml":
    content => inline_template("@settings.to_yaml"),
    notify  => Service['snap-telemetry'],
  }
}
```

```puppet
file { ['/opt/snap/plugins', '/opt/snap/tasks']:
  ensure => directory,
  purge  => true,
}

snap::plugin { 'snap-plugin-publisher-influxdb':
  version => 20,
}

snap::plugin { 'snap-plugin-collector-psutil':
  version => 9,
}
```

**Comment by jcooklin** [comment]
When the documentation is updated in regards to the auto load path it should mention that plugins will need to have the proper permissions (including execute bit set). 

Relates to: #1501
