### ISSUE TITLE
Do not execute binaries directly from the auto-load path

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1502]
Currently, plugins loaded by the snaptel cli via 'snaptel plugin load file_name' are copied to a temporary directory before they are executed. Plugins placed in the auto-load directory are loaded directly from that filepath without going through this process. This prevents plugin files from getting updated when Snap is running since they are in use. We would like snap plugins to behave the same whether they are loaded via the autoloader or snaptel plugin load cli.

**Comment by jtlisi** [comment]
#1494 is something that relates very closely to this. If the temporary directory could default to `/opt/snap/plugins/tmp/` or something along those lines that would be better than the linux default tmp directory

**Comment by jcooklin** [comment]
@jtlisi:  agreed.  @rashmigottipati is currently working on #1491.
