### ISSUE TITLE
Please vendor deps

### ISSUE THREAD

**Issue by brd** [intelsdi-x/snap#1506]
I am trying to port snap to FreeBSD with (@stdale) and it would be much easier if things where vendored.  See this post for reasons: https://blog.gopheracademy.com/advent-2015/vendor-folder/

**Comment by swills** [comment]
+1

**Comment by IRCody** [comment]
Glide populates the vendor folder with locked commits. Can you explain why having the vendor folder directly in the repo makes it easier for your use case?

**Comment by brd** [comment]
Oh let me look, thanks!

**Comment by mjbrender** [comment]
Love to get your input as well @swills - we've been using Glide for vendoring and appreciate it's conventions over the Go vendor functionality mentioned above. If steps to get Snap built aren't clear in [docs/BUILD_AND_TEST.md](https://github.com/intelsdi-x/snap/blob/master/docs/BUILD_AND_TEST.md) then I'd appreciate recommendations on improving it! cc @brd

**Comment by brd** [comment]
I think what we (FreeBSD) needs is a way to parse the Glide yaml file.  That we don't have to maintain a separate list of deps with hashes.

**Comment by swills** [comment]
I just didn't see the glide file, I'm used to looking for the vendor dir. The glide file provides what we need for now, thanks.

**Comment by IRCody** [comment]
@brd: Can you check if [https://github.com/Masterminds/glide](https://github.com/Masterminds/glide) compiles on freebsd? Then you should be able to run(from the root snap/ dir) `glide install`. This will populate the vendor/ dir from the info in the glide.lock file.

That is the tool we are using for parsing the yaml/lock file to re-populate the vendor directory on builds.

**Comment by IRCody** [comment]
@brd, @swills: I'm going to go ahead and close this issue since it seems like your question was answered. If it wasn't please respond here and I'll re-open.
