### ISSUE TITLE
Validate schema error on latest build

### ISSUE THREAD

**Issue by sandlbn** [intelsdi-x/snap#1515]
Using latest build I get below error. 

```bash
ERRO[0000] Validate schema error                         context=(root)::restapi description=Additional property corsd is not allowed value=map[port:8181 https:false rest_auth:false enable:true rest_certificate: rest_key: rest_auth_password: pprof:false corsd: addr::8181]
```

Steps to reproduce:

```
wget http://snap.ci.snap-telemetry.io/snap/latest_build/linux/x86_64/snapteld
```
```
chmod +x snapteld && mkdir /var/log/snap
```

```
./snapteld -plugin-trust 0 --log-level 1 --log-path /var/log/snap
```

System: CentOS 7
Version: snapteld version test-89bf6c0

**Comment by jcooklin** [comment]
A new release will be cut today (1.1.1) addressing this issue.  Stay tuned.

**Comment by mbbroberg** [comment]
Correction to the need for a new release - as @jcooklin identified upon review, no release has this behavior - it was only master. #1516 fixed this.

**Comment by sandlbn** [comment]
@jcooklin thanks for new build but latest build still doesn't work  

```
root@ubuntu-16:/home/vagrant# ./snapteld --version
snapteld version test-85079bc
```

snapteld returns to terminal prompt right after execution:

```
root@ubuntu-16:/home/vagrant# ./snapteld -t 0 -l 1
root@ubuntu-16:/home/vagrant#
```

**Comment by jcooklin** [comment]
@sandlbn do you have a snapteld config in /etc/snap/?

**Comment by sandlbn** [comment]
Nope, its a new system, do I need to have ?

**Comment by jcooklin** [comment]
@sandlbn no but I was thinking maybe it defined a location for the log and in it we would see some kind of error.  

I'm unable to reproduce the issue you are describing.  I've tried building and downloading "latest" on both Linux and Mac.  Can you [strace](https://linux.die.net/man/1/strace) the starting of snapteld to see if that gives us a hint as to what is wrong?

![img](https://www.dropbox.com/s/z1aw0c3hzvzovs7/start_snapteld.gif?raw=1)
☝️ is running: 
`wget -O snapteld http://snap.ci.snap-telemetry.io/snap/latest_build/linux/x86_64/snapteld && chmod 755 snapteld && snapteld -t 0 -l 1`

**Comment by sandlbn** [comment]
Yes that was my fault, config was stored after first run. Please close this
ticket .
