### ISSUE TITLE
Error while loading plugin

### ISSUE THREAD

**Issue by rehank30** [intelsdi-x/snap#1519]
when i try to load the plugin using the command : snaptel plugin load snap-plugin-collector-facter
it is showing the following error on my Mac machine:
Error loading plugin:
fork/exec /tmp/400102727/snap-plugin-collector-facter: exec format error

**Comment by mkleina** [comment]
This issue applies to plugin itself, see:
https://github.com/intelsdi-x/snap-plugin-collector-facter/issues/22
