### ISSUE TITLE
Cannot remove an Ended Task (windowed scheduler)

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap#1520]
## What happened:
An "_Ended_" task cannot be removed - neither directly removing nor after prior stopping 

This happens for a [**windowed schedule**](https://github.com/intelsdi-x/snap/blob/master/docs/TASKS.md#schedule) for which `stop_timestamp` is defined. That means that after this time the task is ended - this is related to changing the status from "_Running_" to "_Ended_" in line [pkg/schedule/windowed_schedule.go#L101](https://github.com/intelsdi-x/snap/blob/85079bc6f854bc9dfa00921d111e0e5fbec4943b/pkg/schedule/windowed_schedule.go#L101).

## Steps to reproduce it
1) Run an exemplary task manifest with window schedule, for example:
```

  "version": 1,
  "schedule": {
    "type": "windowed",
    "interval": "3s",
    "start_timestamp": "2017-02-15T13:20:56+01:00",
    "stop_timestamp": "2017-02-15T13:48:35+01:00"
  },
  "workflow": {
   [...]
}
```
2) After a time `stop_timestamp` the state of task should be "_Ended_"
```
$ snaptel task list
ID                                       NAME                                            STATE           HIT     MISS    FAIL    CREATED                 LAST FAILURE
5db259f7-3403-421d-896a-78aa15031c80     Task-5db259f7-3403-421d-896a-78aa15031c80       Ended           38      0       0       1:46PM 2-15-2017

```
3) Try to remove the task:
```
$ snaptel task remove 5db259f7-3403-421d-896a-78aa15031c80

Error stopping task:
Task must be stopped
```

4) So, let's stop the task at first and then try to remove it once again:
```
$ snaptel task stop 5db259f7-3403-421d-896a-78aa15031c80
Task stopped:
ID: 5db259f7-3403-421d-896a-78aa15031c80
```
Notice that even stop command looks like be executed successfully, the state of task does NOT change to _Stopped_ (it is still _Ended_)
```
snaptel task list
ID                                       NAME                                            STATE           HIT     MISS    FAIL    CREATED                 LAST FAILURE
5db259f7-3403-421d-896a-78aa15031c80     Task-5db259f7-3403-421d-896a-78aa15031c80       Ended           38      0       0       1:46PM 2-15-2017

```
Still, cannot remove this task even after trying to stop it a prior:
```
$ snaptel task remove 5db259f7-3403-421d-896a-78aa15031c80
Error stopping task:
Task must be stopped
```

It looks like a standstill.

**Comment by andrzej-k** [comment]
Ended state should also probably be described here: https://github.com/intelsdi-x/snap/blob/master/docs/TASKS.md#task-states

**Comment by IzabellaRaulin** [comment]
What can be added, ideally an _Ended_ Task should be something that can be removed without having to stop, so it would be similar what has been done for _Disabled_ Task in https://github.com/intelsdi-x/snap/issues/1043.
