### ISSUE TITLE
RFC: Plugin Initiated Workflow

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#1522]
## Request For Comments: 

**Date To Close**: 02/21/2017
**Required Participants**: @jcooklin, @bjray, @kjlyon 
# Summary: 

Snap currently supports only interval based collection driven by Snap. For some types of metrics, it would be more useful to have the plugin make the decision of what interval to collect metrics on. This proposal is a description of a method to add this capability to Snap, which I’m calling Plugin Initiated Workflow. The general idea is that Snap will maintain a gRPC stream connection with the plugin and wait for collector plugin’s to send metrics back to Snap, at which time Snap will dispatch the metrics down the rest of the workflow specified in the task manifest.

# Proposal:

**Definitions**:

**Streaming collector plugin**: A streaming collector plugin is a plugin that connects to Snap over a grpc stream and sends data back over this connection based on configuration that is set by Snap. For example it might send back every time it has 100 data points or at a minimum every x time interval or some combination of the two. It is differentiated from interval based plugins by the fact that it is not called on a regular interval by Snap. 

**Plugin initiated workflow**: A plugin initiated workflow is the name given to a workflow that is started by a streaming collector plugin sending data to Snap. 

**Motivation/use cases**:
* Pull-based collection systems like statsd and prometheus.
* Log aggregation
* System and application logs are by their nature event based.  For instance, there could be large amounts of time where no logs are generated while at other times many events may be generated in a short amount of time.  Plugin Initiated Workflow (PIW) allows the amount of data/remote calls to scaled with the events that are being monitored.
* ? (Welcome ideas to add to the list).

**Benefits**:
* Less traffic overhead for metrics that are “bursty” since data is only sent when when there is something to send instead of on a set interval.
* Pushes more responsibility for how/when data is collected to the plugin that has better context on what is appropriate for its problem.

**Potential problem areas**:
* New ways of dealing with plugin lifecycle will need to be thought about. Need to minimize the required coordination between control and scheduler.
* Need to handle plugin restarts gracefully. Need to think about designing how this is done in control. 

**In Scope**:
* Initial work to allow streaming collector’s to work with Snap.
* Defining gRPC service that all plugin libs will use to allow streaming with Snap.
* Modifying go-plugin-lib to work with the new streaming gRPC interface.
* Example streaming collector plugin as part of go-plugin-lib modifications.

**Out of Scope**:
* Non-go plugin-libs.

**Comment by jowenopsvision** [comment]
This would be great for monitoring things like Netflow and as mentioned log files. The proposed design sounds great for accomplishing the goal.

**Comment by discoduck2x** [comment]
@IRCody would this apply to publisher plugins aswell? e.g influx publisher which currently only seems to be able to send metrics to influx on each interval specified for the collector e.g cpu. what i mean is that influxpublisher should have a flush interval based on either time interval and/or points/metric count(buffered) (to avoid making to many small constant writes. the influx datasource is best written to in batches (still one wants high res / frequent samples taken by collector)

**Comment by IRCody** [comment]
@discoduck2x: A publisher could already be buffering it's writes to external sources I think. Snap sends the data to the publisher as it gets it but AFAIK there is nothing stopping individual plugins from buffering a certain amount before publishing or implementing a flush interval themselves.

**Comment by IRCody** [comment]
Closing because the implementation has been started in #1526. Feel free to checkout the implementation and comment there.
