### ISSUE TITLE
Support building snap on freebsd

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1527]
Current issues include:
* scripts use shebangs that are not currently portable 
* cgo needs to be enabled for freebsd (due to deps)

![img](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRFHTf5CyfwztlFWcNC71Gz0dbUksf3C_-tNQ3DOfehRnitEPRd_w)

**Comment by mbbroberg** [comment]
FYI @brd & @swills as FreeBSD peoples 👍

**Comment by brd** [comment]
Like, this?

https://svnweb.freebsd.org/ports/head/net-mgmt/intel-snap/

**Comment by brd** [comment]
I need to rename it to snap-telemetry, but I am waiting for @stdale's work to be merged to master and then I will update and rename.
