### ISSUE TITLE
[Question] Tribe multiple seed hosts?

### ISSUE THREAD

**Issue by discoduck2x** [intelsdi-x/snap#1530]
Is there any plan for allowing multiple seed hosts for snap tribe functionality?
Right now if i restart "all" hosts in a tribe their snap daemons will fail if their seed target isnt available at startup.

**Comment by mkleina** [comment]
cc @jcooklin

**Comment by jcooklin** [comment]
There are currently no plans to persist tribe configuration data between reboots.   Currently if the entire global membership became unavailable (all of the nodes were shutdown or couldn't communicate) an outside configuration capability would need to step in to bootstrap the cluster.

**Comment by mbbroberg** [comment]
Thanks so much for your question @discoduck2x. I'm going to close this issue since it has been answered. If you think this feature is really essential to have, please open a new issue to request it.

Cheers 🐢
