### ISSUE TITLE
can't build snap plugins on a busybox system

### ISSUE THREAD

**Issue by gonewest818** [intelsdi-x/snap#1549]
It appears you can't build the snap plugins on a busybox system, because `scripts/build_plugins.sh` invokes `xargs -P ...` and the busybox version of xargs doesn't support that flag. For portability it seems prudent to detect if we're on a busybox system and drop the -P if it's not supported. Yes, in that case the plugins wouldn't build in parallel and thus build time will be longer, but at least the build will succeed.

**Comment by andrzej-k** [comment]
Hey @gonewest818 Thanks for reporting this issue! Would you be open to fix it ;) - we would greatly appreciate contribution.

**Comment by gonewest818** [comment]
yes, certainly.
