### ISSUE TITLE
Autoloaded plugins use default temp dir

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap#1555]
https://github.com/intelsdi-x/snap/blob/master/control/control.go#L394

When a plugin is discovered using the auto-discovery path, it is loaded to the default temp directory. I think it should load to the path configured in the snapteld configuration like when a plugin is loaded through the rest api.

**Comment by rashmigottipati** [comment]
Thanks for opening this issue and submitting a PR, Jacob. I agree with your point. Currently, it is loading to the default temp directory. Rest api loads it using https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/v1/plugin.go#L128 , so autoload should follow the same path. However, the default will remain the same for both routes. Your PR will fix this.
