### ISSUE TITLE
Flaky test in Snap scheduler

### ISSUE THREAD

**Issue by candysmurf** [intelsdi-x/snap#1564]
This test often fails but not every time.

```
Failures:

  * /home/travis/gopath/src/github.com/intelsdi-x/snap/scheduler/scheduler_medium_test.go 
  Line 273:
  Expected: 'Ended'
  Actual:   'Running'
  (Should be equal)
```

**Comment by IzabellaRaulin** [comment]
Links to flaky tests which have been identified:
- [scheduler_medium_test.go#L2; commit 29f15e0b](https://github.com/intelsdi-x/snap/blob/29f15e0b220dc868ac5465f54889b7226891d576/scheduler/scheduler_medium_test.go#L273)

- [scheduler_medium_test.go#L506; commit 0ac530ac](https://github.com/intelsdi-x/snap/blob/0ac530ac5495a76c0d1e5c1656e76ba299d3f71c/scheduler/scheduler_medium_test.go#L506)
