### ISSUE TITLE
Plugin wanted: Slack publisher

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#1565]
I'd like to get a publisher which can publish on Slack to alert operators about critical errors.

**Comment by marcin-krolik** [comment]
Hi, 
I'd like to implement this one :)

**Comment by katarzyna-z** [comment]
The plugin is available at https://github.com/marcin-krolik/snap-plugin-publisher-slack and has been added to plugin catolog in #1621
