### ISSUE TITLE
Plugin wanted: InfluxDB data collector

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#1567]
I'd like to have a collector which can get data stored in InfluxDB to calculate statistics based on them.

**Comment by katarzyna-z** [comment]
I'm working on this plugin.

**Comment by fengw084** [comment]
Hello, I found that the SNAP platform will not be executed immediately after the task is started. For example, I started a TASK task, set the scheduling cycle to 3 hours, start the task and will not be implemented, but after 3 hours after the implementation of the first time. Do not know if there is any way or set up to allow my task to start after the first implementation, so you can quickly see the results of their own tasks

**Comment by mkuculyma** [comment]
@fengw084 please see the answer here https://github.com/intelsdi-x/snap/issues/1574

**Comment by katarzyna-z** [comment]
The plugin is available at https://github.com/intelsdi-x/snap-plugin-collector-influxdb-data and has been added to plugin catolog in #1621
