### ISSUE TITLE
linux plugins on mac

### ISSUE THREAD

**Issue by rehank30** [intelsdi-x/snap#1570]
i am new to snap and have been using mac to run snap plugins. 
As most of plugins are for linux, is there any way to run these plugins on mac?

**Comment by rashmigottipati** [comment]
@rehank30 To be able to run linux specific plugins on mac, you need to either have a physical linux box or a virtual one. I believe some of them require you to run them on physical linux boxes.

**Comment by rehank30** [comment]
@rashmigottipati thank you

**Comment by candysmurf** [comment]
The question is answered.
