### ISSUE TITLE
Scheduled immediately

### ISSUE THREAD

**Issue by fengw084** [intelsdi-x/snap#1574]
I want to start a task, you can immediately execute once. Such as setting a task interval of 3 hours, I would like to start after the implementation of the first time, wait until 3 hours after the implementation of the second, so that you can immediately see the results rather than wait 3 hours after the current can pass A set to complete this function?

**Comment by mkuculyma** [comment]
@fengw084 What version of Snap are you using? Do you have our latest release? The functionality you are requesting was introduced with PR https://github.com/intelsdi-x/snap/pull/1544 and is now part of the Snap 1.2 release. You simply need to upgrade your Snap version. No changes in task manifest are required.
