### ISSUE TITLE
Question and Enhancement

### ISSUE THREAD

**Issue by sLuvpreet33** [intelsdi-x/snap#1596]
My question is about the working of Snap.

Where does it store the data which it is collecting about the system ? There has to be a memory where it is storing data, either in the Main Memory OR the Disk, and in which format it stores data , like in a file OR in some kind of DB ?

Also, In grafana I can view the data of only upto past 1 minute. What should I do if I want to see the data for more time, like past week, 1 month or a year ? Do we have to store its data in some DB(like Influx) to view data for more than 1 minute ? If yes, how can I do that ?

About Enhancement, It would be cool if you add plugins for monitoring Redis and Postgres also.

**Comment by andrzej-k** [comment]
Hi @sLuvpreet33 
Snap has a concept of workflows - it means that metrics collected by collector plugins are internally passed to processor plugins (if they are a part of the workflow) and metrics returned by processor plugins are in turn passed to publisher plugins which are responsible for persisting the metrics in places like databases (relational and time-series), message queues, files, etc.
Full list of plugins is available here: https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md

It's most common case to store metrics collected by Snap in some time-series DB (like InfluxDB) and then integrate Grafana with that DB. So you can use our InfluxDB publisher to store metrics and then just add relevant data source in Grafana.

Regarding plugins for Redis and Postgres these are great suggestions. We're also looking for contributors to create plugins. If you'd be interested here are the starting guidelines: https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md

**Comment by mbbroberg** [comment]
When you get a chance @sLuvpreet33, please let @andrzej-k  know if he answered your questions by either commenting or closing your question. I appreciate it ❤️ 

Also, I love the database ideas. We have no plan to write these two ourselves, but we welcome you writing one or both! You can use the [Plugin Authoring documentation](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md). If you can't make it yourself, you can open an Issue saying you'd like one (one issue per plugin) so it ends up in [the wishlist here](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md#wishlist)

Thanks!
