### ISSUE TITLE
Updates to Contributing Guidelines

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#1609]
Our Pull Request guidelines are documented [here](https://github.com/intelsdi-x/snap/blob/master/CONTRIBUTING.md#pull-request-guidelines), and say:

> Pull requests can contain a single commit or multiple commits. The most important part is that a single commit maps to a single fix. Here are a few scenarios:
> 
> - If a pull request adds a feature but also fixes two bugs, then the pull request should have three commits, one commit each for the feature and two bug fixes
> - If a PR is opened with 5 commits that was work involved to fix a single issue, it should be rebased to a single commit
> - If a PR is opened with 5 commits, with the first three to fix one issue and the second two to fix a separate issue, then it should be rebased to two commits, one for each issue
>
> Your pull request should be rebased against the current master branch. Please do not merge the current master branch in with your topic branch, nor use the Update Branch button provided by GitHub on the pull request page.

Let's discuss if following rules/guidelines should be introduced in Snap. The goal is to have PRs that are fairly easy to review and comprehend and code that is easy to maintain in the future.

- One PR addresses one problem (not necessarily one Issue, for example in cases when single Issue describes several problems) 
- Ideally one PR is associated with one commit (squash your work to single commit before merge), as it's trying to tackle one problem
- To make PR review-able PR should be small enough to be comprehended by human reviewer, thus it's preferred to deliver subset of functionality (code) with tests and documentation rather than delivering code in one PR, then tests and documentation in subsequent PRs. 
- Ideally any code change shall be traceable to the Issue, hence reference Issue in PR description 
- It's advised to delivered in PR only functionality requested in the Issue - but if PR adds functionality not requested in the Issue, then it shall be indicated, with a reason behind, in the PR description to make reviewers aware 
- If you believe that a problem may be solved in several different ways, describe design of the solution as part of the Issue, before submitting PR. 
- To make code changes easier to understand and review consider giving hints to reviewers about scenario in which this code is used also pointing out the impact outside changed code - can be done as "Hints to reviewers" comment, example [here](https://github.com/intelsdi-x/snap-plugin-lib-go/pull/77)
- When code needs refactoring, which is not impacting user facing interfaces or user experience, provide reasoning and benefits of doing so, in the form of Issue. 
- Don't forget about comments in the code 
- If you submit a PR for review for which work is still in progress please indicate what is already available and what is still to be done

CC: @mbbroberg

**Comment by mbbroberg** [comment]
I agree that it'd be great to align this section with our preferred behavior. Good call @andrzej-k 🐢

**Comment by andrzej-k** [comment]
@mbbroberg - Thanks for the feedback.

Any other comments from @intelsdi-x/snap-maintainers or @intelsdi-x/plugin-maintainers ?

**Comment by IzabellaRaulin** [comment]
LGTM
