### ISSUE TITLE
Testing Snap for the very first time: psutil plugins example

### ISSUE THREAD

**Issue by ElisaRojas** [intelsdi-x/snap#1620]
Hi,

I've installed Snap and I wanted to test it with the psutils plugins, following https://github.com/intelsdi-x/snap#load-plugins
I installed psutil, loaded the plugins and verified they were there. Also checked available metrics. Then run the task and everything was ok until there. 

However, the log only shows the metrics collected the very first time (i.e. when the task started). More specifically ```tail -f /tmp/psutil_metrics.log``` does not log more events and ```snaptel task watch <ID>``` appears empty (as it didn't register more events). I also tried leaving the watch open for a long time, but nothing. And the ```psutil-file.yaml``` [file](https://github.com/intelsdi-x/snap/blob/master/examples/tasks/psutil-file.yaml) says it should be collecting stats every 1 second. I don't know if this is related somehow with #1403.

More information about my installation: I'm using Ubuntu 14.04 and I installed Snap from the sources.

Any help would be really appreciated!
Thank you!

**Comment by jcooklin** [comment]
Hi Elisa,

What does your task manifest look like?

Have you tried to watch the task? ('snaptel task watch <task_uuid>')

Joel

**Comment by ElisaRojas** [comment]
Hi Joel,

I'm using the manifest example taken from here [psutil-file.yaml](https://raw.githubusercontent.com/intelsdi-x/snap/master/examples/tasks/psutil-file.yaml).
And yes, I tried watching the task and it appears empty (I left it for several minutes and no event appeared...)

Thank you!

**Comment by jcooklin** [comment]
You mentioned building from source, can you try using the prebuilt binary [here](https://github.com/intelsdi-x/snap-plugin-collector-psutil/releases/download/10/snap-plugin-collector-psutil_linux_x86_64) instead?  

Also, if you're interested I'd like to have a video/sharing session to debug the issue.  We can coordinate through slack (join 👉 https://intelsdi-x.herokuapp.com) just DM me.  In the meantime I'll continue to try and reproduce the issue on a 14.04 system here.

**Comment by IzabellaRaulin** [comment]
Hello @ElisaRojas,
 I would like to ensure if your task manifest - [psutil-file.yaml](https://raw.githubusercontent.com/intelsdi-x/snap/master/examples/tasks/psutil-file.yaml) has set `count = 5`  - the `count` is a parameter determining how many times metrics are collected and published. This is very helpful for achieving a single run task (count=1)  or , in general, "X" runs.

You can list your task and check its status - after executing workflow 5 times, its state should be _Ended_:

```
$ snaptel task list

ID                                       NAME                                            STATE   HIT     MISS    FAIL    CREATED                 LAST FAILURE
01c829c7-46ee-4ec4-816c-bec7a68f4fba     Task-01c829c7-46ee-4ec4-816c-bec7a68f4fba       Ended   5       0       0       10:20PM 5-01-2017
```

To create a task running "forever" please remove this line from your task manifest, so it will look like below:
```yaml
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/psutil/cpu/cpu-total/user: {}
        /intel/psutil/cpu/cpu-total/system: {}
        /intel/psutil/cpu/cpu-total/idle: {}
        /intel/psutil/load/*: {}
      publish:
        - plugin_name: "file"
          config:
            file: "/tmp/psutil_metrics.log"
```
Such task will be running until you decide to stop it (`snaptel task stop <task_id>`). **Please, confirm if that works as you expected** - below there is 3 functionality which might be helpful in verification:  
**a) List task**
```
$ snaptel task list
ID                                       NAME                                            STATE           HIT     MISS    FAIL    CREATED                 LAST FAILURE
c89f7021-79b8-4a12-81fb-9b285a579d70     Task-c89f7021-79b8-4a12-81fb-9b285a579d70       Running         6       0       0       11:03PM 5-01-2017
```
**b) Watch the task**
```
$ snaptel task watch c89f7021-79b8-4a12-81fb-9b285a579d70

Watching Task (c89f7021-79b8-4a12-81fb-9b285a579d70):
NAMESPACE                                DATA                    TIMESTAMP
/intel/psutil/cpu/cpu-total/idle         1.6788086862e+08        2017-05-01 23:04:24.689783482 +0200 CEST
/intel/psutil/cpu/cpu-total/system       251114.26               2017-05-01 23:04:24.689777738 +0200 CEST
/intel/psutil/cpu/cpu-total/user         3.99072801e+06          2017-05-01 23:04:24.689781454 +0200 CEST
/intel/psutil/load/load1                 0.38                    2017-05-01 23:04:24.689104299 +0200 CEST
/intel/psutil/load/load15                0.27                    2017-05-01 23:04:24.689105726 +0200 CEST
/intel/psutil/load/load5                 0.34                    2017-05-01 23:04:24.689105245 +0200 CEST
```
(Ctrl + C to exit from task-watcher)

**c) Stop the running task**
```
$ snaptel task stop c89f7021-79b8-4a12-81fb-9b285a579d70
Task stopped:
ID: c89f7021-79b8-4a12-81fb-9b285a579d70
```

**Comment by ElisaRojas** [comment]
Thank you both @jcooklin and @IzabellaRaulin ! 

@IzabellaRaulin , that was it! Playing a bit with the count number "fixed" it :smile: 
Thanks for your nice explanation!

**Comment by IzabellaRaulin** [comment]
That's great! If you have any further question, do not hesitate to open an issue on GH or reach us on [Slack](https://intelsdi-x.herokuapp.com/).
