### ISSUE TITLE
Can't download mac pkg 1.2.0

### ISSUE THREAD

**Issue by jenchen1398** [intelsdi-x/snap#1679]
I'm getting a 404 error when I try to download the mac pkg 1.2.0 
[https://github.com/intelsdi-x/snap/releases/download/1.2.0/snap-telemetry-1.2.0.pkg]

**Comment by kjlyon** [comment]
Hi @jenchen1398 , are you accessing the download from the [releases](https://github.com/intelsdi-x/snap/releases) page? 

Try the link I pasted below, this is the link I got from that page. 
[https://github.com/intelsdi-x/snap/releases/download/1.2.0/snap-1.2.0-darwin-amd64.tar.gz]

**Comment by jenchen1398** [comment]
I tried downloading from the http://snap-telemetry.io/download.html website. Seems like the link is broken there. Hopefully someone can fix the link on the main snap-telemetry.io website. The link you sent me on github works. Thanks!

**Comment by kjlyon** [comment]
@jenchen1398, Thank you for bringing this to our attention!! 👏  We have opened an issue and will get to work on this.

**Comment by IzabellaRaulin** [comment]
hello @jenchen1398, thank you for reporting the broken link. It's already fixed.  Snap in version 1.30 is now available - share your opinion, we are looking for your feedback in the future.

**Comment by IzabellaRaulin** [comment]
hello @jenchen1398, thank you for reporting the broken link. It's already fixed. **Snap 1.30** is now available - share your opinion, we are looking for your feedback in the future.
