### ISSUE TITLE
Missing documentation for stand-alone feature

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#1687]
Missing documentation for stand-alone feature (at least I don't see it). Users should know how use stand-alone plugins.

**Comment by kjlyon** [comment]
Similar to [plugin diagnostics](https://github.com/intelsdi-x/snap-plugin-lib-go/#plugin-diagnostics) is stand-alone functionality something that should go in the plugin libraries or should it go in the Snap documentation? What are your opinions? 

@intelsdi-x/snap-maintainers

**Comment by katarzyna-z** [comment]
I think that documentation for stand-alone plugin should be in main Snap repo. New users takes a look at main repo and looks for features and stand-alone feature works should work for all snap-plugin-libs.

**Comment by kjlyon** [comment]
I agree that information on how to use stand-alone plugins should go in Snap. Should we include information about how to write a stand-alone plugin in Snap or in the plugin-libs?

**Comment by katarzyna-z** [comment]
I think that information about how to write a stand-alone could be in plugin libs because there are small differences in implementation related to the programming languages
