### ISSUE TITLE
Propose to merge 'snap-plugin-collector-csvreader' into intelsdi-x repo

### ISSUE THREAD

**Issue by cuongquay** [intelsdi-x/snap#1721]
Sometime we need to stub or reload some metrics from CSV files that require having a plugin to collect the csv's column as a single metric. I wrote one plugin to do so at https://github.com/cuongquay/snap-plugin-collector-csvreader.

I would love to be a contributor of your repository. This is a brilliant telemetry collector project as far as I can see,

**Comment by andrzej-k** [comment]
Hey @cuongquay Great work on CVS reader plugin! Two comments if I may:
- You may want to revisit source files headers - the copyright don't have to be attributed to Intel
- To include your plugin in Snap plugin catalog, it's the best to follow this guide: https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md#plugin-metadata

**Comment by cuongquay** [comment]
Thank you for correcting me. I have just updated the copyright headers of source files and adding the metadata.yaml file into this project. Can you review it and tell me if there is any missing?

**Comment by andrzej-k** [comment]
This looks good. Please go ahead and create PR adding your plugin to https://github.com/intelsdi-x/snap/blob/master/docs/plugins.yml. Thanks!
