### ISSUE TITLE
Herokuapp does not work

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap#1744]
The link https://intelsdi-x.herokuapp.com/ to Snap slack does not work. We are working on fixing that - I will provide status under this issue. Please, use https://intelsdi-x.slack.com instead till Heroku service is back. 

Best regards,
Izabella Raulin

**Comment by pcn** [comment]
While this is down, how can we request access to the slack as a new user?

**Comment by taotod** [comment]
@pcn Please send your email address to Izabella and me. Let's check if we can invite your to our slack group. BTW, do you have any topic to discuss? Thanks.

**Comment by pcn** [comment]
Is there a relatively private way to send my email address?

I do have a specific topic: I'm working on a python plugin to report ntp health in a way that we've found is specifically good for our needs, so it may or may not be useful to others.  Something about either the code I've written, the way I'm packaging and running it, or something else is causing it to run once and not report further, and I'm looking for a better understanding of what troubleshooting steps are available to me.

**Comment by IzabellaRaulin** [comment]
@pcn, please send me a message to my email (it is provided on my GH profile) - I will add you to Slack channels.

**Comment by IzabellaRaulin** [comment]
> @pcn, please send me a message to my email (it is provided on my GH profile) - I will add you to Slack channels. 

Ok, I see that you already joined :) Sorry for the inconvenience. We are trying to fix https://intelsdi-x.herokuapp.com/.

**Comment by danieldn** [comment]
Snap's Heroku account is back online. Please confirm link works and invite gets sent properly.
https://intelsdi-x.herokuapp.com/

**Comment by IzabellaRaulin** [comment]
@danieldn - yes, it works! Thank You
