### ISSUE TITLE
Automatic discovery of plugins: Fully Operational

### ISSUE THREAD

**Issue by danielscottt** [intelsdi-x/snap#180]
previously: https://github.com/intelsdi-x/pulse/issues/178

The autodiscovery path for plugin loading should be constantly monitored, and the actions of loading/unloading should mirror the actions of adding and removing plugins from said directory.

**Comment by IRCody** [comment]
After talking with @danielscottt and @jcooklin I am going to close this issue since we are not planning on implementing this feature.
