### ISSUE TITLE
Worker queue sizes should be exposed

### ISSUE THREAD

**Issue by lynxbat** [intelsdi-x/snap#247]
I personally prefer:

1. command line args (`--collect-wpool` `--process-wpool` `--publish-wpool`)
2. EnvVars (now easy with new cli)
3. Eventual pulsed.conf

**Comment by mjbrender** [comment]
We need to get this tracked - tagging as bug so it's pulled into JIRA.

**Comment by geauxvirtual** [comment]
We should not tag items as bugs that are not bugs.

**Comment by mjbrender** [comment]
@geauxvirtual I hear you - it was a temporary hack to get it pulled into jira. It's removed now :bow:

**Comment by mjbrender** [comment]
This is WIP by @tjmcs (SDI-950). Putting it as in progress.

**Comment by geauxvirtual** [comment]
Closing with merge of #763.
