### ISSUE TITLE
snapctl should do url checking and throw a better error

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#260]
snapctl should do url checking and throw a formatting error if a user does not input a url in the format snapctl is expecting.

<img width="794" alt="screen shot 2015-07-07 at 12 09 45 pm" src="https://cloud.githubusercontent.com/assets/1395030/8554851/29af2bd6-24a1-11e5-87d0-361c2b81ed0a.png">

**Comment by mjbrender** [comment]
s/pulse/snap/g

**Comment by mjbrender** [comment]
Still no good as of current version. 

```
build/bin/snapctl --url asdfasdf task list
Error getting tasks:
Get asdfasdf/v1/tasks: unsupported protocol scheme ""
```

**Comment by tiffanyfj** [comment]
I'll tinker around with this.
