### ISSUE TITLE
Packaging Snap Plugins from @lynxbat comment on issue 310

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#319]
> NOTE by @mjbrender: snap was originally nicknamed pulse, which is why you'll see the Pulse used below

Here are some ideas I had:
## Pulse Plugins need to be more than a binary.

One approach is to use a manifest file which can be compressed into a tar file resulting in a plugin image.

Something like:

pulse-publisher-rabbitmq.tar
-- pulse_plugin.yaml
-- pulse-publisher-rabbitmq (binary)
-- `<some signing file>`
-- `<other things>`

Within the manifest we can have points to signing files, details on which arch the plugin was built on, etc.
## Plugin Builds happen from `pulsectl`

We add a new subcommand for pulsectl called `build`. This takes parameters for signing, building, and more. It would output the full tar file writing the manifest as well are handling the go build for the plugin.

In addition we could support the `pulse build` command being pointed at a github.com URL for the purpose of building plugins easily. This would copy the `go get` behavior.

With the `pulse build` command we could easily bootstrap the Intel plugins hosted externally into a local build using github.com URLs.

**Comment by mjbrender** [comment]
Hey @geauxvirtual - what's your call on this issue? Still a valid need or something we should close on?

**Comment by geauxvirtual** [comment]
It's @lynxbat's decision if requested features are to be dropped from snap development.

**Comment by lynxbat** [comment]
^ this is actively a part of packaging design and should remain open/linked into that feature. Especially since it is basically a spec from @geauxvirtual above.

**Comment by mjbrender** [comment]
Good deal. Doing some cleanup on open issues and I like to keep it clear what's what given the ever increasing audience we have on snap. Thanks for clarifying.

**Comment by nanliu** [comment]
I'm wondering if these requirements are captured by#1276. If so we can close this.

**Comment by lynxbat** [comment]
@nanliu yes they are
