### ISSUE TITLE
PCM task example

### ISSUE THREAD

**Issue by annierana** [intelsdi-x/snap#332]
There is already an open issue(https://github.com/intelsdi-x/pulse/issues/315) regarding PCM collector plugin (not uploading in pulse). 

As the PCM metrics meta data will be generated dynamically in collector, it would be great if a sample of task (JSON) for PCM collector can be added to pulse git as well.

**Comment by danielscottt** [comment]
Hi @annierana:

We landed the ability to select metrics to collect via a wildcard in #499.  I'm going to close this issue, but wanted to let you know beforehand.

Using the `*`  is dependent on the plugin author, so unless its been implemented in the plugin, it would still require explicitly declaring the metrics.

**Comment by lynxbat** [comment]
@danielscottt can we open an issue on the PCM repo referring to this?

**Comment by danielscottt** [comment]
Referring to implementing the `*`?

**Comment by lynxbat** [comment]
If there is a query use case here that should be in that plugin, yes. Just so we don't lose the end use case.
