### ISSUE TITLE
Perf events plugin

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#347]
Collect following HW metrics for Cgroups from "perf" - Performance Counters for Linux:
*  cycles
*  instructions
*  cache-references
*  cache-misses
*  branch-instructions
*  branch-misses
*  stalled-cycles-frontend
*  stalled-cycles-backend
*  ref-cycles

**Comment by danielscottt** [comment]
This is landed: https://github.com/intelsdi-x/snap-plugin-collector-perfevents
