### ISSUE TITLE
IPMI plugin

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#356]
This plugin will retrieve data from Intel Node Manager via IPMI. Following metrics will be gathered:

| Metric                                           | Command                                                      |
|--------------------------------------------------|--------------------------------------------------------------|
| CPU C-State Residency (0xBE-Core CUPS Sensor)    | 2Dh-Get Sensor Reading                                       |
| Memory Bandwidth (0xC0-Memory CUPS Sensor)       | 2Dh-Get Sensor Reading                                       |
| IO Bandwidth (0xBF-IIO CUPS Sensor)              | 2Dh-Get Sensor Reading                                       |
| Inlet Temperature (0xA3-Inlte Air Temperauture)  | 2Dh-Get Sensor Reading or C8h-Get Node Manager Statistics    |
| Outlet Temperature (0xBD-Outlet Air Temperature) | 2Dh-Get Sensor Reading or C8h-Get Node Manager Statistics    |
| Airflow (0xA2-Volumetric Airflow)                | 2Dh-Get Sensor Reading or C8h-Get Node Manager Statistics    |
| Platform Power                                   | C8h-Get Node Manager Statistics                              |
| CPU Power                                        | C8h-Get Node Manager Statistics                              |
| Memory Power                                     | C8h-Get Node Manager Statistics                              |
| CPU Margin to throttle – functional              | 40h-Send Raw PECI command or C8h-Get Node Manager Statistics |
| CPU Margin to Spec – Reliability                 | 40h-Send Raw PECI command                                    |
| Memory – Margin to throttle                      | 40h-Send Raw PECI command or C8h-Get Node Manager Statistics |
| Component temperature - VR                       | D9h-Send Raw PMBus Command (if I2C used as comp. interface)  |
| Component temperature - HDD                      | D9h-Send Raw PMBus Command (if I2C used as comp. interface)  |
| Component temperature - Chipset                  | D9h-Send Raw PMBus Command (if I2C used as comp. interface)  |

**Comment by danielscottt** [comment]
This has landed: https://github.com/intelsdi-x/snap-plugin-collector-node-manager
