### ISSUE TITLE
Global Config Spec

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#386]
> NOTE by @mjbrender: snap was originally nicknamed pulse, which is why you'll see the Pulse used below

Global Config
=============
 
This spec describes adding global configuration to pulse.  We will describe two types of config below.  The first is the top level configuration and will be referred to as *Global Config* while the second is specific to providing plugin configuration *at load time* and will be referred to going forward as *Global Plugin Config*.  The pulse agent can be provided these configurations through a switch and configuration file at startup or through the API (pulsectl) after starting.     

*Example usage*
```
pulsed -config ~/pulsed.cfg
```

*~/pulsed.cfg*
```
{
    "control": {
        "cache_ttl": "5s"
    },
    "scheduler": {
        "default_deadline": "5s",
        "worker_pool_size": 5
    },
    "plugin": {
        "all": {
            "password": "p@ssw0rd"
        },
        "collector": {
            "pcm": {
                "path": "/usr/local/pcm/bin",
                "versions": {
                    "1": {
                        "user": "john"
                    }
                }
            }
        }, 
        "publisher": {
            "influxdb": {
                "server": "xyz.local",
                "password": "$password"
            }
        }
    }
}
```

*API/client usage*
```
pulsectl config --control cache_ttl 5s
pulsectl config --scheduler cache_deadline 5s
pulsectl config --collector pcm.path /usr/local/bin
pulsectl config --control --unset cache_ttl 
```

Global Config provides runtime configuration and the ability to define a variable once and reference it in multiple plugins.  

A ConfigPolicy derived from the Global Config (and Global Plugin Config) will be passed to the method GetMetricTypes.  The Publish, Collect or Process methods will continue to receive ConfigPolicy but it will now be a merge between the tasks configuration and the Global Configuration.

**Comment by danielscottt** [comment]
Reopening this, the ability to configure the daemon is not yet implemented.

**Comment by geauxvirtual** [comment]
Closing with the merge of #763.
