### ISSUE TITLE
Metric catalog order

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap#402]
Metric catalog order not working properly. List of metrics should be in alphabetical order.

Currently "pulsectl metric list" output: 
*(example for pmc plugin)*
![image](https://cloud.githubusercontent.com/assets/11335874/10454608/1fa1a684-71b6-11e5-85a0-c3fc58c4a7df.png)

**Comment by danielscottt** [comment]
This was closed by #414
