### ISSUE TITLE
Task watcher does not refresh properly

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap#451]
## Task watcher does not refresh in proper way
Marked by red box -> watcher output contains current values, but some remains from previous values are also visible.

![image](https://cloud.githubusercontent.com/assets/11335874/10794079/befeff7c-7d93-11e5-98ab-82bbfb9e9bd3.png)

This issue also occurs for namespace (can be observed when watcher reordered showed metrics). Some remains from previous longer namespace are still there.
![image](https://cloud.githubusercontent.com/assets/11335874/10794622/0659a8c0-7d96-11e5-8f84-9874655937fa.png)

**Comment by marcin-krolik** [comment]
Issue resolved by CSI erase display code

**Comment by andrzej-k** [comment]
Fixed by #606
