### ISSUE TITLE
Creating pulsectl task reinitialize loaded plugin

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap#460]
Invalid re-initialization of loaded plugin when task is creating which causes that plugin main() is called second time and the plugin structure is re-initialized what caused that obtained plugin's conf settings from Global Config (in GetMetricTypes()) are  lost.

To clarify this issues the Fprintf text was added to main.go
![image](https://cloud.githubusercontent.com/assets/11335874/10851260/757e7da8-7f2a-11e5-9082-38bf88f5174e.png)

Example: 

#### Step 1:  Loading plugin
**2015/10/30 12:02:39 MAIN() is called**

2015/10/30 12:02:39 Debug: **in `GetMetricTypes`()**
2015/10/30 12:02:39 **Set ceph conf based on Pulse Global Conf**
2015/10/30 12:02:39 ceph.path=/home/test/Ceph_CentOS/ceph_pmstore_write_apml/src
2015/10/30 12:02:39 ceph.socket.path=/home/test/Ceph_CentOS/ceph_pmstore_write_apml/src/out
2015/10/30 12:02:40 len(ceph.daemons)=5
2015/10/30 12:02:40 ceph.daemons=[mds.a.asok mon.a.asok osd.0.asok osd.1.asok osd.2.asok]

#### Step 2:  Creating a task
**2015/10/30 12:03:44 MAIN() is called** (AGAIN)

2015/10/30 12:03:45 Debug: **in `GetCollectMetrics`()**
2015/10/30 12:03:45 ceph.path=
2015/10/30 12:03:45 ceph.socket.path=
2015/10/30 12:03:46 len(ceph.deamons)=0
2015/10/30 12:03:46 ceph.deamons=[]

Because plugin main() is executed second time -> what caused that `New()` function is executed which return new, empty `ceph := &Ceph{}` and data obtained in GetMetricsType from Global Config  kept in Ceph structure are lost.

**Comment by jcooklin** [comment]
@IzabellaRaulin: Managing init between loaded and running plugins should happen just like you are doing it in GetMetricTypes ([here](https://github.com/intelsdi-x/snap-plugin-collector-ceph/blob/master/ceph/ceph.go#L188-L190)) and CollectMetrics ([here](https://github.com/intelsdi-x/snap-plugin-collector-ceph/blob/master/ceph/ceph.go#L168-L174)) as opposed to exposing a separate RPC call that control would use to communicate config.    

Closing this issue.
