### ISSUE TITLE
interested in becoming a maintainer

### ISSUE THREAD

**Issue by conikeec** [intelsdi-x/snap#588]

**Comment by danielscottt** [comment]
Hey @conikeec!  Thanks for your interest.

We don't quite have a system for adding maintainers just yet, but I'm confident we will soon.  We will keep you updated here as we work out those details.

**Comment by conikeec** [comment]
BTW: Spoke to @lynxbat offline about this, so check with him as well

**Comment by mjbrender** [comment]
Great to know @conikeec. Are you at Tectonic Summit as well? Find me too :+1:

**Comment by conikeec** [comment]
No @mjbrender . Decided to stay local given our new born :(

**Comment by mjbrender** [comment]
@conikeec congratulations though!! So cool.

**Comment by lynxbat** [comment]
Awesome @conikeec!

We are working the process now to accept maintainers. I am going to leave this open until we have an update (should be soon) and proceed from there. Super excited to have your help.

**Comment by conikeec** [comment]
Thanks @lynxbat . Look forward to it

**Comment by conikeec** [comment]
Thanks @mjbrender

**Comment by mjbrender** [comment]
Hey @conikeec - I started to implement the Help Wanted flag. It'd be great to have you pick up any open issues with those (or others, as long as they're not "in progress").
