### ISSUE TITLE
Address gofmt issues as reported by goreportcard.com

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#626]
The following files have gofmt issues according to goreportcard.com

./control/metrics_test.go
./control/plugin/collector_proxy_test.go
./control/plugin/collector_test.go
./mgmt/rest/client/metric.go
./mgmt/rest/client/plugin.go
./mgmt/rest/plugin.go
./mgmt/rest/task.go
./mgmt/tribe/tribe.go
./plugin/collector/snap-collector-mock1/main_test.go
./plugin/collector/snap-collector-mock1/mock/mock.go
./plugin/collector/snap-collector-mock2/main_test.go
./plugin/collector/snap-collector-mock2/mock/mock.go
./plugin/publisher/snap-publisher-file/main_test.go

**Comment by tiffanyfj** [comment]
I'll work on this.

**Comment by geauxvirtual** [comment]
Closed by #629
