### ISSUE TITLE
Break plug-in architecture to a repo of its own

### ISSUE THREAD

**Issue by pires** [intelsdi-x/snap#632]
I'm aware this may be a ridiculous request, but I really enjoy your plug-in architecture approach and I believe it would benefit the overall Go community if it was a project on its own, abstracted from `publisher`, `collector` and other Snap related concepts, ofc.

**Comment by jcooklin** [comment]
There is also interest in separating the client plugin package into its own repo.  

Definitely a suggestion worth considering.  Thanks @pires.

**Comment by danielscottt** [comment]
Not ridiculous at all @pires!  We've talked about this a lot, and it is definitely something I'm interested in.

+1 from me.

**Comment by lynxbat** [comment]
I love the idea also since it could make improving the plugin arch something decoupled from snap itself.

This could be a big effort right now given the plugin typing and some of the wiring around this directly to routing and other things.

**Comment by pires** [comment]
Oh wow, I was not expecting this reaction. You guys rock! :+1:

**Comment by lynxbat** [comment]
Well, not sure we rock until we :ship: it :)

That said, we are open to help if you want to take a first stab at helping @pires. We can help answer questions on how it work on the gutter channel or future slack channel.

**Comment by pires** [comment]
Sounds like a plan!

**Comment by lynxbat** [comment]
Because of possible reuse of the plugin model in other projects. I am pulling this one back out of the freezer.

**Comment by tjmcs** [comment]
I think this would be quite useful, especially if you have a way of mocking up the daemon responses somehow so that plugin developers could test plugins independent of a running instance of snapd...

**Comment by mjbrender** [comment]
I'm a little sad for me to say I haven't seen this one move forward. :disappointed: 

We *did* separate out the plugin clients if that helps you at all: https://github.com/intelsdi-x/snap-plugin-lib-go

Sorry about our excitement not turning into a plugin architecture you could reuse @pires. I'm going to close this issue knowing we won't be getting to this in the coming year. 

My consolation prize: let me know if you could use a hand on something and I'll make sure to help out. You can email me at matthew [.] brender `@` intel.com.

**Comment by pires** [comment]
Thanks for the ping @mjbrender. I'll keep your offer in mind if I pick this up.
