### ISSUE TITLE
REST API Response with Metadata field

### ISSUE THREAD

**Issue by mingchan** [intelsdi-x/snap#636]
It is **NOT** a common practice to include metadata field in payload  and want to understand the need and use-case behind it.
Also the info provided in the metadata field in already accessible from rest clients and it is redundant info as well.

## API Response Meta
Parameter  | Description | 
| :---------| :--------------- | 
| code | HTTP status code |
| message | the operation response message |
| type | the operation type |
| version | the API meta version |

Like the HTTP Code, which is already returned to the client and client already has access to it and no need to provide in the payload.

```
{
  "meta": {
    "code": 200,
    "message": "Plugin list returned",
    "type": "plugin_list_returned",
    "version": 1
  },
```
The client initiates the REST API and it is expecting certain format the API returns.
Essentially the REST API contractually to provide the info in the format.  There is no need to put that in the meta field. 
Version?  It is already explicitly used in the request URL by the client, ***“/v1/…”***

===================
Thanks,
Ming

**Comment by candysmurf** [comment]
@Ming, thanks for your interest and feedback.

We could have a lot of use cases for using Meta info. One of the examples could be for future activity analytics.

The meta version is different than the API version. Hope this helps. Please let me know if you have more questions.

**Comment by mingchan** [comment]
Thanks! Good to know.


    On Tuesday, December 15, 2015 6:51 PM, Emily Gu <notifications@github.com> wrote:
 

 @Ming, thanks for your interest and feedback.We could have a lot of use cases for using Meta info. One of the examples could be for future activity analytics.The meta version is different than the API version. Hope this helps. Please let me know if you have more questions. —

**Comment by mingchan** [comment]
Spent some time think about meta-version v.s. api-version.
Since the api-version contractually describes the content returned (meta + body ), if the meta format is changed, wont the api-version will be bumped as well?  Will it be in practice the two versioning scheme will cause more confusion?

**Comment by lynxbat** [comment]
@mingchan Possibly but not definitely. 

For example:

API v1 may use:
foo v1
bar v1
baz v1

API v2 may use:
foo v1
bar v2
baz v2
qux v1
