### ISSUE TITLE
Update metric catalog over time

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#651]
A mechanism in snapd is needed that will periodically update the catalog (call GetMetricTypes) on a configurable interval.

**Comment by thomastaylor312** [comment]
+1 on this. We definitely have this need because many of our plugins dynamically generate their list of allowed metrics and this can change on a daily or weekly basis.

**Comment by jcooklin** [comment]
Dynamice namespaces were introduced to address this need.  Please see the doc [here](https://github.com/intelsdi-x/snap/blob/master/docs/METRICS.md) for more info.
