### ISSUE TITLE
Snap should log when jobs are skipped due to deadline expiration.

### ISSUE THREAD

**Issue by ConnorDoyle** [intelsdi-x/snap#656]
Quoting @geauxvirtual in a comment from related issue #655:

> The problem revolves around what is mentioned earlier in that the exported task having a new deadline field. By default, the deadline for a job is 5 seconds. The publish job takes the parents deadline which is the time the job was created + 5 seconds. You can see here in this part of the code https://github.com/intelsdi-x/snap/blob/master/scheduler/worker.go#L49-L56, we do not generate an error log if the deadline passes, and we just kill the job. If you look at the gist you posted,

**Comment by geauxvirtual** [comment]
Looking at the code, should we add a method to coreJob that allows for adding to errors for the job? While logging the message helps in debugging this issue, being able to add to the errors array would allow us to write a test.

**Comment by ConnorDoyle** [comment]
I like that idea.  It doesn't look like there's anything special about the coreJob struct that use sites depend on.  How about replacing occurrences of `coreJob` as members of `collectorJob` and friends with the `job` interface type?  That could protect against clobbering the accumulated errors along the way.
