### ISSUE TITLE
PLUGIN_AUTHORING.md not clear for non-Golang plugins

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#660]
It's unclear how a developer would create a plugin in anything other than Go within the [AUTHORING](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md) documentation as it stands today. 

In particular, it's difficult to how to comply with the [mandatory packages](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_AUTHORING.md#mandatory-packages) and the next 3 sections specific to each type of plugin. 

Overall, it would be helpful to refer to a non-Golang plugin or two as example.

**Comment by mjbrender** [comment]
Comments @andrzej-k? I'd like your perspective.

**Comment by andrzej-k** [comment]
@mjbrender  - I agree that's not clear, however up until now we don't have non-Golang production grade, maintained plugin. Framework is ready for non-Golang plugins but unless we have experience in writing such plugins it would be hard to give good guidelines to others.
@jcooklin Do you know something more about non-Golang plugins, could share your insights?

**Comment by mjbrender** [comment]
Makes sense @andrzej-k - we'll cross that bridge when we get there.

**Comment by thomastaylor312** [comment]
I know there is some documentation on how to create the plugins with a python example @tiffanyfj showed to me. This is definitely something we should figure out because a lot of people who are interested in this don't know Go. Having something more common in the Sys Admin space (like python) would help get some more traction.

**Comment by kindermoumoute** [comment]
Close this as https://github.com/intelsdi-x/snap/pull/1343 is merged.
