### ISSUE TITLE
snapctl task watch doesn't work properly in tmux

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap#684]
When `snapctl task watch` is running in tmux with 2 terminals in vertical split, metrics are visible for fraction of second then screen goes empty. When same command is running in fresh tmux session without additional terminals, list of metrics is visible for significantly longer time but blinking is still noticeable. Problem does not occur in `screen`, however such problem doesn't occur with other (even complex, using ncurses) applications.

I'm 99% sure this worked well before beta.

**Comment by jcooklin** [comment]
@lmroz I do not see the same behavior you are describe when running tux 2.0-3 under Ubuntu 15.10.  Will you provide more detail on the version and environment you are running under?

**Comment by lmroz** [comment]
I have tmux 1.9a on Fedora 21. Problem doesn't seem to be caused by terminal emulator because I observe same behavior on gnome-terminal and mintty (from cygwin).

**Comment by tiffanyfj** [comment]
@lmroz Hey if you update to 2.1, do you still get the error?

**Comment by tiffanyfj** [comment]
@lmroz Installed 1.9a on workstation Fedora 21 and I don't see this problem.

**Comment by IzabellaRaulin** [comment]
@lmroz, it seems that this issue cannot be reproduced easily. Moreover, it might be not related with snap itself, but with tmux - please check is it still occurs for upgraded version of tmux as @tiffanyfj suggested. 

If this issue still occurs on your system, feel free to re-open this github-issue - please provide additional information which might help to reproduce that. Thank You.
