### ISSUE TITLE
statically linking snapd/snapctl in the downloads area? 

### ISSUE THREAD

**Issue by edyesed** [intelsdi-x/snap#687]
I'm working on building a Dockerfile for snapd ( based off alpine:3.3 ), and linking appears to be different from ubuntu. How do you feel about building a statically linked snapd/snapctl?

**Comment by jcooklin** [comment]
Are you building a Dockerfile for an x86-64 platform?  We are currently building

**Comment by geauxvirtual** [comment]
We have done limited testing so far with statically linked binaries for snap, but the limited testing I've done with a statically linked binary in a scratch docker image seemed to work without issue. I haven't tried alpine based image, but with a statically linked binary, I would expect it to function the same. 

We are looking to improve our support for running snap inside a docker image, be it a ubuntu/centos base, scratch base, or alpine, but it will also most likely require statically linking the plugins as well for scratch and alpine images.

**Comment by lynxbat** [comment]
We are looking to automate our builds more this quarter. A statically linked docker image could be a possible output. Definitely worth exploring.

**Comment by mjbrender** [comment]
Tagging appropriately. Thanks again for suggesting it @edyesed :raised_hands:

**Comment by geauxvirtual** [comment]
@edyesed We've recently been able to update the one snap dependency that relied on CGO to a version that no longer needs CGO and have the ability to build snapd without CGO enabled (#719). We haven't cut a release of snap with this commit yet, but if you build snapd from master, you should be able to run it in an alpine based docker image. I've verified this by creating a docker image from `alpine:3.3`, copying a snapd binary built from latest master into `/`, and verifying the container runs.

Please test as well and report any additional issues you may uncover.

```
FROM alpine:3.3
ADD snapd /

CMD ["/snapd", "-l", "1", "-t", "0"]
```

```
$ docker run --rm alpinetest:latest
time="2016-03-17T00:44:16Z" level=info msg="Starting snapd (version: v0.12.0-beta-122-g01874e8)"
time="2016-03-17T00:44:16Z" level=info msg="setting GOMAXPROCS to: 1 core(s)"
time="2016-03-17T00:44:16Z" level=info msg="control started" _block=start _module=control
time="2016-03-17T00:44:16Z" level=info msg="module started" _module=snapd block=main snap-module=control
time="2016-03-17T00:44:16Z" level=info msg="scheduler started" _block=start-scheduler _module=scheduler
time="2016-03-17T00:44:16Z" level=info msg="module started" _module=snapd block=main snap-module=scheduler
time="2016-03-17T00:44:16Z" level=info msg="setting plugin trust level to: disabled"
time="2016-03-17T00:44:16Z" level=info msg="auto discover path is disabled"
time="2016-03-17T00:44:16Z" level=info msg="Configuring REST API with HTTPS set to: false" _module="_mgmt-rest"
time="2016-03-17T00:44:16Z" level=info msg="Starting REST API on :8181" _module="_mgmt-rest"
time="2016-03-17T00:44:16Z" level=info msg="REST API is enabled"
time="2016-03-17T00:44:16Z" level=info msg="snapd started" _module=snapd block=main
time="2016-03-17T00:44:16Z" level=info msg="setting log level to: debug"
```

**Comment by syepes** [comment]
+1 Hope this gets included in the next release.

**Comment by jcooklin** [comment]
https://github.com/intelsdi-x/sbr/issues/6

**Comment by geauxvirtual** [comment]
I don't believe SBR is being used any more for building the binaries. @nanliu can confirm this.

**Comment by nanliu** [comment]
sbr is still used for the plugin tar.gz. I've only migrated the package builds. I will add this for consideration in 0.16 release. If nothing else, I'll check and make sure it's consistent across the board.

**Comment by nanliu** [comment]
We released snap containers on docker hub (includes alpine) that should address this issue:
https://hub.docker.com/r/intelsdi/snap/

If you have any issues with those containers, please file them in this repository: 
https://github.com/intelsdi-x/snap-docker
