### ISSUE TITLE
'go vet' fails 

### ISSUE THREAD

**Issue by pjholmes** [intelsdi-x/snap#691]
Under go1.5.1, test.sh fails because 'go vet' fails with the following errors:

mgmt/rest/config.go:37: github.com/intelsdi-x/snap/mgmt/rest/rbody.PluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:61: github.com/intelsdi-x/snap/mgmt/rest/rbody.PluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:103: github.com/intelsdi-x/snap/mgmt/rest/rbody.DeletePluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:145: github.com/intelsdi-x/snap/mgmt/rest/rbody.SetPluginConfigItem composite literal uses unkeyed fields

**Comment by geauxvirtual** [comment]
What OS did you encounter this on?

I ask because running `make test` on Go 1.5.3 on Mac OS X, I do not see `go vet` reporting any issues. In our Travis testing Go 1.5.3, `go vet` does not report any issues. However, testing Go 1.6rc2 on Linux, `make test` exits with these `go vet` errors. 

Just trying to determine why there is a discrepancy between Go versions or environments.

**Comment by tiffanyfj** [comment]
@geauxvirtual I've had this issue before in a different file (you can see it in closed PRs)

For me: go1.5
```
./scripts/test.sh                                        ✹ ✭
Getting GoConvey if not found
Getting goimports if not found
Getting govet if not found
Getting cover if not found
gofmt
goimports
go vet
mgmt/rest/config.go:37: github.com/intelsdi-x/snap/mgmt/rest/rbody.PluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:61: github.com/intelsdi-x/snap/mgmt/rest/rbody.PluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:103: github.com/intelsdi-x/snap/mgmt/rest/rbody.DeletePluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:145: github.com/intelsdi-x/snap/mgmt/rest/rbody.SetPluginConfigItem composite literal uses unkeyed fields
exit status 1
```

**Comment by mjbrender** [comment]
I'm not seeing this with 1.5.3 @pjholmes. Is 1.5.1  a must for ou?

**Comment by geauxvirtual** [comment]
Closing this issue with the merge of #726 (commit cherry-picked from PR #692)
