### ISSUE TITLE
 Intermittent failures in control_test

### ISSUE THREAD

**Issue by candysmurf** [intelsdi-x/snap#720]
Failures:

  * /Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/intelsdi-x/snap/control/control_test.go
  Line 1141:
  Expected '[]' to NOT be nil (but it was)!

**Comment by candysmurf** [comment]
I have been unable to reproduce this issue and that I will close the issue in 2 days unless someone else comments on the issue.

**Comment by mjbrender** [comment]
No reproduction, so closing it @candysmurf :+1:
