### ISSUE TITLE
how do you query the available config items for a plugin

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap#723]
Without reading the code, there does not seem to be any way to find out what config items are available for plugin, ie to get the output the response of GetConfigPolicy()

I assumed that the `GET /v1/plugins/:type/:name/:version/config` API method would return this data, but it appears to simply return any configuration defined in the GlobalConfig.

Am i just not looking in the right spot, or is there no way to query the ConfigPolicy of a plugin.

**Comment by danielscottt** [comment]
Hi @woodsaj - I'm afraid you're correct.  Metrics' config policies are available, but it looks like they aren't for processor or publisher plugins.  I think this is probably a pretty easy fix, but I'd want to dig into it a bit further to be sure because of potential conflicts with the global config path you mentioned.

**Comment by IRCody** [comment]
Hey @woodsaj, @danielscottt and I were talking about this just now and were hoping to get your feedback.

Currently you can get Metric ConfigPolicy by doing ```GET /v1/metrics```. This seems to cover ConfigPolicy for collector plugins since collector plugin ConfigPolicy is inherently tied to metrics. Is there a use case where it doesn't? The response for this looks like:

```
{
  "meta": {
    "code": 200,
    "message": "Metric",
    "type": "metrics_returned",
    "version": 1
  },
  "body": [
    {
      "last_advertised_timestamp": 1456187456,
      "namespace": "/intel/mock/foo",
      "version": 2,
      "policy": [
        {
          "name": "password",
          "type": "string",
          "required": true
        },
        {
          "name": "name",
          "type": "string",
          "default": "bob",
          "required": false
        }
      ],
      "href": "http://localhost:8181/v1/metrics/intel/mock/foo?ver=2"
    }
  ]
}
```

For processor and publisher plugins you are correct there is currently no way to get the ConfigPolicy. We were thinking we should add it to the results returned from ```GET /v1/plugins/:type/:name/:version``` which would look like:

```
{
  "meta": {
    "code": 200,
    "message": "Plugin returned",
    "type": "plugin_returned",
    "version": 1
  },
  "body": {
    "name": "file",
    "version": 3,
    "type": "publisher",
    "signed": false,
    "status": "loaded",
    "loaded_timestamp": 1456187457,
    "href": "http://localhost:8181/v1/plugins/publisher/file/3",
    "config_policy": {
      "config": {
        "root": {
          "nodes": null,
          "keys": [
            ""
          ],
          "keysbytes": null,
          "node": {
            "rules": {
              "file": {
                "key": "file",
                "required": true,
                "default": null,
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}
```

Does this expose the information you needed/expected in a way that is useful to you? We'd appreciate any feedback or thoughts.

**Comment by lynxbat** [comment]
I think we should be careful with "default". In the case of a password a simple get reveals passwords possibly. I have thought a 'password' rule type is probably needed.

**Comment by IRCody** [comment]
Right now the method I mentioned above will dump the default password if one is supplied in GetConfigPolicy() for the plugin which probably shouldn't happen.

Looking at it just now it seems like ```GET /v1/plugins/:type/:name/:version/config``` reveals similar information. If you start snapd with the [example config](https://github.com/intelsdi-x/snap/blob/master/examples/configs/snap-config-sample.json) and then do:

```
>  curl "http://localhost:8181/v1/plugins/processor/movingaverage/1/config"
{
  "meta": {
    "code": 200,
    "message": "Plugin config item retrieved",
    "type": "config_plugin_item_returned",
    "version": 1
  },
  "body": {
    "password": "new password",
    "user": "tiffany"
  }
}
```
You can see all the configured information which seems not great unless I'm missing something. I think you can get similar info from tasks that are running also. I'm going to look into it more tomorrow.

**Comment by danielscottt** [comment]
Just going to throw this out there.

A lot of the data, the `/v1/plugins/:type/:name/:version/config` noun is a concrete example, is for Tribe's consumption.  Once the gRPC module communication lands, I think it's feasible that all of the Tribe communication could use these instead.

**Comment by woodsaj** [comment]
Thanks for the quick response here everyone.  

I hadn't noticed the policy data in the response from /v1/metrics, and for my current plans i think this would be sufficient.

But long term, i do see a lot of benefit to making the configPolicy from processor and publisher plugins available.  Including it with the /v1/plugins/:type/:name/:version response seems like a logical approach as the policy is a property of the plugin version.

**Comment by IzabellaRaulin** [comment]
Resolved by https://github.com/intelsdi-x/snap/pull/728
