### ISSUE TITLE
Discussion/Question: Advanced authentication

### ISSUE THREAD

**Issue by thomastaylor312** [intelsdi-x/snap#725]
I noticed that we are [adding](https://github.com/intelsdi-x/snap/pull/724) HTTP basic auth to the REST API. Are there any plans to add things like LDAP integration in the future or would it be better to handle that with a reverse proxy?

**Comment by lynxbat** [comment]
Yes. We are planning on an AAA feature which should allow for integrating LDAP/AD.

**Comment by thomastaylor312** [comment]
@lynxbat Thanks! Anything I can follow on Github?

**Comment by mjbrender** [comment]
Hey @thomastaylor312 - we do, but not connected! We're grooming an Epic in JIRA (674) with the following as a goal: 

> Extend the security implementation for snap to help remove barriers to adoption within production scenarios. This would cover authentication, authorization and access control.

This is linked to #286 - let's keep the original open to track this effort and clarify. Thanks!
