### ISSUE TITLE
Metric API to return a named list (metrics_returned) in the body?

### ISSUE THREAD

**Issue by mingchan** [intelsdi-x/snap#730]
Just going through the return for “GET /v1/metrics” call.

Should it return a named list like below instead?

```
“body”: {
    “metrics_returned”: [...]
}
```

So that it is consistent with other API calls like

```
GET /v1/plugins
GET /v1/tasks
```

They return “loaded_plugins” and “ScheduledTasks” lists respectively.

**Comment by IRCody** [comment]
This seems like a sensible change for consistency's sake.
