### ISSUE TITLE
Plugin being killed during long write

### ISSUE THREAD

**Issue by thomastaylor312** [intelsdi-x/snap#731]
It looks like snap is killing a plugin when it is not receiving a heartbeat (which is a good behavior) but it is doing that when the plugin is busy handling a large amount of data (300K+ in this case). Is there something I am missing? Logs below from a fresh instance of snap running:

```
DEBU[0484] collector run completed                       _module=scheduler-job block=run job-type=collector metric-count=304627
DEBU[0484] starting publisher job                        _module=scheduler-job block=run content-type=snap.gob job-type=publisher plugin-config=map[user:{test} database:{testing} host:{localhost} password:{test} port:{8086}] plugin-name=influx plugin-version=-1
DEBU[0486] plugin selected                               _module=control-routing block=select hitcount=0 index=publisher:influx:v10:id1 pool size=1 strategy=least-recently-used
ERRO[0539] error with publisher job                      _module=scheduler-job block=run content-type=snap.gob error=unexpected EOF job-type=publisher plugin-config=map[host:{localhost} password:{test} port:{8086} user:{test} database:{testing}] plugin-name=influx plugin-version=-1
WARN[0539] Task failed                                   _block=spin _module=scheduler-task consecutive failure limit=10 consecutive failures=1 error=unexpected EOF task-id=fa79deb7-c1b6-4381-8927-19bda227952e task-name=Task-fa79deb7-c1b6-4381-8927-19bda227952e
DEBU[0539] task spin loop                                _module=scheduler-task
DEBU[0539] event received                                _block=handle-events _module=scheduler-events event-namespace=Scheduler.MetricsCollected metric-count=304627 task-id=fa79deb7-c1b6-4381-8927-19bda227952e
WARN[0540] heartbeat missed                              _module=control-aplugin aplugin=publisher:influx:v10:id1 block=check-health
INFO[0540] Nothing to do for this event                  _block=handle-events _module=control-runner event=Control.PluginHealthCheckFailed
WARN[0541] heartbeat missed                              _module=control-aplugin aplugin=publisher:influx:v10:id1 block=check-health
INFO[0541] Nothing to do for this event                  _block=handle-events _module=control-runner event=Control.PluginHealthCheckFailed
WARN[0542] heartbeat missed                              _module=control-aplugin aplugin=publisher:influx:v10:id1 block=check-health
WARN[0542] heartbeat failed                              _module=control-aplugin aplugin=publisher:influx:v10:id1 block=check-health
WARN[0542] handling dead available plugin event          _block=handle-events _module=control-runner aplugin=publisher:influx:v10:id1 event=Control.AvailablePluginDead
INFO[0542] hard killing available plugin                 _module=control-aplugin aplugin=publisher:influx:v10:id1 block=kill
DEBU[0542] Hard killing plugin                           _module=control-plugin-execution path=/tmp/741494120/snap-plugin-publisher-influxdb
```

**Comment by geauxvirtual** [comment]
Can you post the logs from the plugin? The logs posted show an error returned from the plugin with the publishing job. My initial guess is the plugin crashed during the publishing job, which would explain the missed heartbeats later on.

**Comment by thomastaylor312** [comment]
Looks like `err="NaN is an unsupported value for field value" plugin-name=influx plugin-type=publisher plugin-version=10 point=<nil>` caused a nil pointer reference and caused the plugin to panic. So a mixture of bad data and a hard to read log (it was all in byte arrays). So I think we can just close this.

**Comment by lynxbat** [comment]
@thomastaylor312 Do you think we could make the plugin control report these errors better? How can we reduce the time it took for you to nail it down to a publisher bug?

**Comment by geauxvirtual** [comment]
I feel this brings up a valid point that `unexpected EOF`could be improved upon. While that may be an error message received, it just becomes noise and has little value in knowing exactly why the job failed.

**Comment by thomastaylor312** [comment]
@lynxbat In all honesty yes. The problem right now is that some of the plugins dump raw byte arrays instead of strings, which makes it hard to read. Also, it may be useful to actually bring plugin logs into the main snap log (at least in debug). I know that may be a pain to implement, but it would be useful. However, at least making the plugin control report better errors would improve the debugging experience quite a bit.

**Comment by lynxbat** [comment]
Keeping the plugin logs is going to stay. Log aggregation can be solved external of snap (and probably better).

But better exception handling would be nice into the plugin logs.

**Comment by thomastaylor312** [comment]
@lynxbat Good point. I am all for the better exception handling.

**Comment by mjbrender** [comment]
Hey @thomastaylor312, @lynxbat, what have we decided is the best action here? Is this a bug or is it expected behavior that could have better exception handling? If the former, we'll tag this as a bug. If the latter, let's label it a question and open up an issue for better exception handling in this situation. Thanks :ok_hand:

**Comment by thomastaylor312** [comment]
This is expected behavior that should have better error handling. So I'd
say tag it as a question.

**Comment by mjbrender** [comment]
Thanks @thomastaylor312. I'll pop this open under the InfluxDB plugin and make a general note on plugin development. Better exception handling is always better.

**Comment by thomastaylor312** [comment]
@mjbrender should we close this now that you have opened [the new issue](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/issues/47)?

**Comment by mjbrender** [comment]
+1 @thomastaylor312. Closing given there's nothing further to glean from this question. Thanks for starting the discussion!

**Comment by thomastaylor312** [comment]
👍
