### ISSUE TITLE
Hangs when using example tasks/plugins

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#751]
When running the example task under examples/tasks/mock-file.json It has an error:
```
ERRO[0080] error with processor job                      _module=scheduler-job block=run content-type=snap.gob error=plugin pool not found job-type=processor plugin-config=map[] plugin-name=passthru plugin-version=-1
```
This causes snapd to hang.  It doesn't respond to ctrl+c. The task is shown as still running in using `snapctl task list` but has only a single hit. It seems like it might be related to the changes from #743  since I do not get the error if I reset before that.

Steps to reproduce:
``` 
snapd -t 0 -l 1
```

Then load the plugins:
```
snapctl plugin load ../plugin/snap-collector-mock1
snapctl plugin load ../plugin/snap-collector-mock2
snapctl plugin load ../plugin/snap-publisher-file
snapctl plugin load ../plugin/snap-processor-passthru
```

Create the task:
```
snapctl task create -t examples/tasks/mock-file.json
```

**Comment by geauxvirtual** [comment]
This bug was introduced with PR #743.
