### ISSUE TITLE
Remove pkg/ctree/tree.go if not used

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#754]
Is pkg/ctree/tree.go still used? It seems to overlap with core/cdata/tree.go. If this is dead code then consider removing it.

**Comment by geauxvirtual** [comment]
Pkg/ctree is the general config tree implementation used by both ConfigDataTree in core/cdata and ConfigPolicy in control/plugin/cpolicy. Removing this package would break snap.
