### ISSUE TITLE
Task enabling should emit an event

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#755]
In scheduler/scheduler.go EnableTask() should emit an event in addition to just logging that task was enabled.

**Comment by IRCody** [comment]
Can you expand more on why you think an event should be emitted in EnableTask and what purpose that would serve?

**Comment by nanliu** [comment]
@andrzej-k, do you have any feedback on why this should be changed?

**Comment by andrzej-k** [comment]
I don't have a use case for this currently. This request was a result of our initial Snap design review. Can be probably closed for now.
