### ISSUE TITLE
chrono used in production code

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap#756]
According to chrono package documentation, it is intended to be used for testing, but it seems that it's also used in production code: scheduler/worker.go. Maybe additional comment is needed there to explain why it's used, or if possible chrono should not be used there.

**Comment by jcooklin** [comment]
When timed production code needs to be tested deterministically time.Now() should be replaced by Chrono.Now().  Only tests should make calls to the other methods of Chrono (Forward, Reset, Pause, Continue).

**Comment by andrzej-k** [comment]
@jcooklin Thanks for clarifying this. Closing this issue now.
