### ISSUE TITLE
Config validation-only mode

### ISSUE THREAD

**Issue by ConnorDoyle** [intelsdi-x/snap#764]
Continuing discussion started in PR #763.

Would it be helpful to have a flag that causes snapd to validate and dump the effective configuration (return nonzero on error)?

> @tjmcs commented:
> I think that would be a great enhancement; were you thinking of a "debug_startup" flag of some sort that would describe the configuration that would be applied based on a given snapd command (after applying defaults, the appropriate configuration flag, if any, and any command line flags that were provided) or were you thinking of a command you could run from the CLI or RESTful API to retrieve the current configuration of a running snapd instance?

Yes, exactly that.  For me, I think I'd want to just dump the config to stdout (as YAML or JSON) and exit.  Snapd already serves the config via the HTTP interface, no?  Adding that feature to `snapctl` seems useful too.  It already fetches plugin configs so maybe a natural extension.

> @geauxvirtual commented
> What would be considered the role of validate? Just that there are no errors in parsing a YAML or JSON configuration file? Or also validate values passed in as being acceptable? (i.e MaxRunningPlugins is between 1 and 10)

Good question!  Ideally it would validate syntax, content and values with the same logic that `snapd` uses when starting up.

**Comment by mbbroberg** [comment]
Doing some clean up on older ideas from the maintainers because the awesome ideas are plentiful but our time is limited. Given this is over a year old, isn't essential to the project and hasn't been worked on, I'm going to close it. ❤️
