### ISSUE TITLE
SnapGOBContentType only type supported for Processor and Publisher plugins

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#771]
In `*processJob.Run` (https://github.com/intelsdi-x/snap/blob/master/scheduler/job.go#L290-L331) and `*publishJob.Run` (https://github.com/intelsdi-x/snap/blob/master/scheduler/job.go#L380-L419 and https://github.com/intelsdi-x/snap/blob/master/scheduler/job.go#L380-L419), the contentType for a plugin is checked. If the type is not `SnapGOBContentType`, the switch statements drop to a default case which is to log a fatal message causing the **snap daemon to exit with status 1**. In the case of a publish job with a process job as the parent job, there is no default for the case statement, so neither the publish occurs nor is an error message logged, or in the case of these jobs, a fatal message is logged.

Logging this issue for two reasons:

- [ ] Add support for other content types
- [ ] Discuss current behavior for snap daemon (exiting with status 1) if unsupported content type is detected.

**Comment by IRCody** [comment]
The changes in #1150 will (I think) resolve this.
