### ISSUE TITLE
Packaging for Centos 7

### ISSUE THREAD

**Issue by nqn** [intelsdi-x/snap#774]
It would be super handy to have rpms (with idomatic structure: docs in man pages or /usr/share, configuration in /etc, systemd units, daemon output ending in syslog, etc). instead of having to build or pull in the bare binary.

**Comment by geauxvirtual** [comment]
We should create an issue that covers both RPM and DEB formats so there is one place to document  everything that needs to land in snap to support packaging for both formats.

**Comment by mjbrender** [comment]
How does this relate to @nanliu's work to create packages. See http://snap-telemetry.io/download.html

**Comment by nanliu** [comment]
We have released packages and have a package build repo at: https://github.com/intelsdi-x/snap_packaging

If anyone have a specific platform that they need packages for which is not covered by our package repo, please open an issue.
