### ISSUE TITLE
Drop testing Go 1.4.3 in Travis

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#779]
Currently we test Go 1.4.3, Go 1.5.3, and Go 1.6 in Travis. Our tests rely on a number of external tools (go vet, golint, etc). 

As per this commit for golint, https://github.com/golang/lint/commit/a113636da96a2efee02051f523c74104dbe4d202, golint has dropped support for Go 1.4.3, and now requires Go 1.5 or Go 1.6.

Per Golang documentation, when a major version is released, the previous version is no longer supported outside of critical/security updates (https://golang.org/doc/devel/release.html). With the release of Go 1.6, this means Go 1.5 is no longer supported, and Go 1.4 was no longer supported once Go 1.5 was released.

With the change in golint requiring Go 1.5 or Go 1.6, any testing in Travis using golint with Go 1.4.3 fails to run. 

Opening this issue to gather any arguments against dropping testing of Go 1.4.3 from the Travis tests. Seeing as the tests currently won't run without some re-work of how we install the external tools for testing, the easier approach is to just remove Go 1.4.3 from the testing matrix.

**Comment by geauxvirtual** [comment]
Regardless of the above, grpc requires Go 1.5+. When the RPC work for scheduler and control lands, Go 1.4.3 testing will need to be removed for tests to pass in Travis.

**Comment by jcooklin** [comment]
Closed by #838
