### ISSUE TITLE
Chaining processor --> processor in a workflow is not supported

### ISSUE THREAD

**Issue by danielscottt** [intelsdi-x/snap#785]
In `processorJob.Run()`, the only parent job type which is available is `collectJob`: https://github.com/intelsdi-x/snap/blob/717b91f0e74ba1377dec0e1c801f18b613a05266/scheduler/job.go#L290-L343

This is a large block; the most important part is [line 332](https://github.com/intelsdi-x/snap/blob/717b91f0e74ba1377dec0e1c801f18b613a05266/scheduler/job.go#L332). This `default` is for the parent job type `switch`.

cc: @nqn

**Comment by jcooklin** [comment]
Fixing this issue we should also 
-  test that having multiple processors with the same processor parent works (fan-out)
-  address the metrics field [(here)](https://github.com/intelsdi-x/snap/blob/717b91f0e74ba1377dec0e1c801f18b613a05266/scheduler/job.go#L267) on processJob which is not referenced
