### ISSUE TITLE
Invalid API response when using snapctl 

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#810]
When using snapctl to query metrics while running one of the example tasks we have the following metrics:
```
 % ./snapctl metric list
NAMESPACE                VERSIONS
/intel/mock/*/baz        1,2
/intel/mock/bar          1,2
/intel/mock/foo          1,2
```

When I do `./snapctl metric get -m="/intel/mock/*"` I am expecting to get all of the metrics since no version is specified. I actually see:
`Received an invalid API response (META/TYPE)`

Digging a little deeper, the rest API is sending a response with all the metrics. The rest client gives the error because it's expecting MetricReturnedType but is receiving MetricsReturnedType which is what causes the error. The code that impacts this is [here](https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/client/metric.go#L103-L121). The server side is doing some interpretation of the wildcard [here](https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/metric.go#L64-L82) but only if the namespace ends in a *.

**Comment by IRCody** [comment]
Closing since #1048 is a newer issue with with a better description and linked PR that addresses this issue.

**Comment by obourdon** [comment]
Oops sorry I did not see that the issue was already logged. Will be more careful in the future
