### ISSUE TITLE
go get github.com/intelsdi-x/snap results in error: expects import "go4.org/errorutil"

### ISSUE THREAD

**Issue by sarahjhh** [intelsdi-x/snap#813]
when I run `go get github.com/intelsdi-x/snap ` I get the following error message:

`package github.com/camlistore/go4/errorutil: code in directory /Users/sjhan/snappy04/src/github.com/camlistore/go4/errorutil expects import "go4.org/errorutil"`

the repositiory still downloads, but unable to run make.
however, if I run `godep restore` then afterwards this error goes away and am able to run make successfully.

`go env` results:
```
sjhan-mac02:snap sjhan$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sjhan/snappy04"
GORACE=""
GOROOT="/Users/sjhan/.gvm/gos/go1.6"
GOTOOLDIR="/Users/sjhan/.gvm/gos/go1.6/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by geauxvirtual** [comment]
Can you clarify this issue?

I'm not surprised running `go get` on snap returns an error as `go get` tries to walk the entire project and download needed dependencies to build snap. However, running `make` first runs `godep restore` which will download and set all dependencies to the correct versions for snap before trying to build the project. Did you run `make` or `make all` after downloading snap? `make all` does not run `godep restore`, just builds snap and the plugins.

I've verified running `go get github.com/intelsdi-x/snap` and then running `make` works.

```
:~$ go get github.com/intelsdi-x/snap
package github.com/camlistore/go4/errorutil: code in directory ~/test/src/github.com/camlistore/go4/errorutil expects import "go4.org/errorutil"
:~$ cd test/src/github.com/intelsdi-x/snap/
:~/test/src/github.com/intelsdi-x/snap$ make
make deps
make[1]: Entering directory '/home/pulse/test/src/github.com/intelsdi-x/snap'
bash -c "./scripts/deps.sh"
Getting godep if not found
Checking snap root for deps
Checking snapctl for deps
Checking snap mgmt/rest for deps
make[1]: Leaving directory '/home/snap/test/src/github.com/intelsdi-x/snap'
make all
make[1]: Entering directory '/home/snap/test/src/github.com/intelsdi-x/snap'
bash -c "./scripts/build.sh /home/snap/test/src/github.com/intelsdi-x/snap true"

****  snap build (v0.13.0-beta-6-gb380122)  ****

Source Dir = /home/snap/test/src/github.com/intelsdi-x/snap
 Building snapd
 Building snapctl
    snapctl => /home/snap/test/src/github.com/intelsdi-x/snap/build/bin/snapctl
 Building Plugin(s)
    snap-processor-passthru => /home/snap/test/src/github.com/intelsdi-x/snap/build/plugin/
    snap-publisher-file => /home/snap/test/src/github.com/intelsdi-x/snap/build/plugin/
    snap-collector-mock2 => /home/snap/test/src/github.com/intelsdi-x/snap/build/plugin/
    snap-collector-mock1 => /home/snap/test/src/github.com/intelsdi-x/snap/build/plugin/

*******************
make[1]: Leaving directory '/home/snap/test/src/github.com/intelsdi-x/snap'
```

**Comment by lynxbat** [comment]
Given how `go get` is pretty idiomatic, we should be sure the experience is seamless for users without having to know to run make after. Not sure we can fix that at the moment but this should be talked through /cc @mjbrender @bjray

**Comment by geauxvirtual** [comment]
By pinning dependencies for snap, `go get` is pretty much useless without running `make` to set dependencies correctly prior to building snap which also includes building snapctl. If `go get` were to build snap, it would be built around dependencies that we don't test against currently and could introduce unknown issues into the user experience.

A user wanting to test snap should be directed to the releases page that includes pre-built binaries. Developers wanting to use the latest version should use `git` to clone the repo and follow our build instructions which involves running make.

**Comment by lynxbat** [comment]
What about moving to true vendoring?

**Comment by geauxvirtual** [comment]
It _could_ be a solution, however, `go get` would still only build `snapd`, probably as `snap` since that is the name of the repo, and wouldn't build `snapctl`. Whatever binary `go get` would produce wouldn't have a version with the way we set version at build time unless the user specified build flags to the go get command to set the version.

**Comment by lynxbat** [comment]
I think offering true packaging (rpm, deb, docker, binary download, etc) helps mitigate this for those that don't want to develop against snap (and just use it).

**Comment by mjbrender** [comment]
Agreed w/that point @lynxbat. `go get` is a standard and should be able to occur without error. 

This comes back to understanding who needs what from our project. Users need to get to the binaries as easily as possible. Developers need to be able to develop against the snap framework by extending it or by creating a new plugin. 

The Developer path doesn't mean everything is ready to go from a User POV. It should make sense. This includes no errors and clear directions. If we need to change the directions to make the errors  go away, let's make sure we do. 

Let's keep evolving! :hatching_chick: => :hatched_chick: => :chicken:

**Comment by lynxbat** [comment]
:hatching_chick: => :hatched_chick: => :chicken: => :dragon_face:

**Comment by geauxvirtual** [comment]
Not every go project directs users of their project to use go get. It's convenience for projects, not a standard.

**Comment by geauxvirtual** [comment]
Although `go get` is not the recommended way to download snap at this time, `go get` of snap no longer fails. We made no changes as the error was from an external pkg. I feel this issue is resolved, and any further discussions around `go get` or packaging should be moved to another issue.

**Comment by mjbrender** [comment]
^ @geauxvirtual missed this note and agree. Closing.
