### ISSUE TITLE
Single run task 

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#828]
As a user I would like to be able to submit a single run task.

**Comment by lynxbat** [comment]
Would this be better named as an `ephemeral task`?

Also, a task without a schedule (single run) is just a workflow.
Would `ad hoc` workflow be better? Do we want to keep under a `task` construct even though it may result in a mass of `ephemeral tasks`? Should be create a new construct?

Also, this is not for watcher modes right?

**Comment by lynxbat** [comment]
Comments:

1. A single run seems like a Task Library (can be re-run). Not bad but I feel like there is utility in having the ability to fire off task with a schedule window that applies to the moment they are fired. This also feels like a new schedule type (meta-scheduler?).
2. Ephemeral is cool but should remain in a final state then pruned automatically. This brings in the #879 use case.
3. Not sure I follow No 3 above. A workflow is a workflow. The context of the Task is ad hoc or not.

**Comment by IRCody** [comment]
The RFC for single run task is at #985. Closing this issue since I think the discussion is better had in the more specific and recent issues #879 and #985.
