### ISSUE TITLE
plugin-config action in snapctl should not be grouped with tribe commands.

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#833]
Currently in snapctl, `plugin-config` action is only available when tribe is enabled in snapd; however, `plugin-config` should be available regardless if snapd is configured for tribe or not.

https://github.com/intelsdi-x/snap/blob/master/cmd/snapctl/commands.go#L201-L216

**Comment by IRCody** [comment]
Should this to be `snapctl plugin-config ...` or moved under the plugin commands as `snapctl plugin config ...`?
