### ISSUE TITLE
Consider removing resource name from namespace

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap#844]
From my point of view namespace should contain only metric name, not resource identifiers. This should be moved to source and source should be now something like:

```
type Source struct {
    Host string
    Extra map[string]string
}
```

Rationale:
- Metric list is usually known at load time, but list of targets require additional configuration (like hostname, socket paths etc.). Moreover it's either static (and presented in metric catalog) if obtained using global config or reduces to presented approach (with `*` in place of resource name).
- Having uniform metric name in database requires labels mechanism and stripping this information from namespace.
- Metric catalog presented to user is either polluted with target information or exposes `*` that is no more informative than presented approach.
- Source in current form is insufficient to select data from same physical node, but obtained using in-band and out-of-band collection (ex. IPMI and PCM).
- If snap is intended to work in cluster mode, metric catalog should be uniform across the cluster.
- Source of collection might not be related to any particular host, but for example openstack cluster and tenant in that cluster.

In this approach plugin on GetMetricTypes could expose multiple entries with same namespace as long as combination of `Namespace` and `Source` is unique and that combination should be key in metric catalog. Special value like `*` used in namespace should be possible value for source's extra.  In Task Manifest user should be able to specify `Source` and `Namespace`.
In current form dynamic queries are just conjunction of clauses and that easily maps to selection by source:
`"/intel/disk/[sda|sdb]/*/writes"` -> `"/intel/disk/writes" : {Drive: ['sda', 'sdb']}`
`"/intel/disk/sda/1/writes"` -> `"/intel/disk/writes" : {Drive: ['sda'], Partition: ['1']}`
`"/intel/disk/*/1/writes"` -> `"/intel/disk/writes" : {Partition: ['1']}`

**Comment by candysmurf** [comment]
@lmroz, good topics for discussion.

It seems that:
1. Wildcard is good for the aggregation of metric types therefore it reduces the size of metric list. The actual metric(namespace) itself should never have any "*" inside
2. Unified namespace is good in terms of use cases like search and etc, but it's not enough to identify the uniqueness. When you store data inside a DB, unified namespaces may be stored as an extra column to santisfy the use cases.
3.

**Comment by IRCody** [comment]
@lmroz, @candysmurf: there have been a lot of changes to namespace/source since this issue was created. Is this issue still relevant given the changes?

**Comment by jcooklin** [comment]
The resource name should be included in the namespace as a static or dynamic namespace element as is appropriate.

Using a dynamic namespace element
`/intel/*/writes`
`/intel/[device]/writes` listing catalog with `--verbose` 

This is related to #421.

**Comment by IRCody** [comment]
I think this is also related to #652.

**Comment by mbbroberg** [comment]
Doing some clean up on older ideas from the maintainers. Given the changes to source and the lack of activity on this thread I'm going to close it as an answered question. Please open a feature request if there is a specific need. Cheers 🐢
