### ISSUE TITLE
Accessing global configuration within a plugin with snap v0.13

### ISSUE THREAD

**Issue by rji** [intelsdi-x/snap#849]
I've been stuck on this one for a little while now and thought it's time that I ask here for help. In my free time, I've been working on a couple of snap plugins for collecting Mesos cluster metrics and have run into an issue / need some guidance around accessing configuration parameters.

First and foremost, I'm using:
  * Ubuntu 14.04.4 x64
  * Go 1.6
  * snap v0.13.0
  * snap-plugin-utilities/config at fab7eb9d5ffe54a246333468cbbfe689b4070633

My implementation for accessing the global config resembles the following:

In GetMetricTypes:
```go
func (m *MesosAgent) GetMetricTypes(cfg plugin.PluginConfigType) ([]plugin.PluginMetricType, error) {
	url, err := buildHostUrl(cfg)
	// ...
```

In CollectMetrics (not being called yet, just including this in the interest of completeness):
```go
func (m *MesosAgent) CollectMetrics(mts []plugin.PluginMetricType) ([]plugin.PluginMetricType, error) {
	url, err := buildHostUrl(mts[0])
	// ...
```

Shared function for building a URL (string) to pass to the HTTP client:
```go
func buildHostUrl(cfg interface{}) (string, error) {
	items, err := config.GetConfigItems(cfg, []string{"host", "port"})
	if err != nil {
		return "", err
	}

	host := items["host"].(string)
	port := items["port"].(int)

	return "http://" + host + ":" + strconv.Itoa(port), nil
}
```

I run snapd with `--config <path/to/config.json>`, with a configuration that includes:

```json
{
  "control": {
    "plugins": {
      "collector": {
        "mesosagent": {
          "all": {
            "host": "10.180.10.180",
            "port": 5051
          }
        }
      }
    }
  }
}
```

When calling `snapctl plugin load build/rootfs/snap-plugin-collector-mesosagent`, the snap logs reveal the following:

```
time="2016-04-11T00:30:05Z" level=info msg="API request" _module="_mgmt-rest" index=1 method=POST url="/v1/plugins" 
time="2016-04-11T00:30:07Z" level=debug msg="wrote 8300943 to /tmp/192431333/snap-plugin-collector-mesosagent" 
time="2016-04-11T00:30:07Z" level=info msg="Loading plugin: /tmp/192431333/snap-plugin-collector-mesosagent" _module="_mgmt-rest" 
time="2016-04-11T00:30:07Z" level=info msg="plugin load called" _block=load _module=control 
time="2016-04-11T00:30:07Z" level=info msg="plugin load called" _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-mesosagent 
time="2016-04-11T00:30:07Z" level=debug msg="timeout chan start" _block=waitHandling _module=control-plugin-execution 
time="2016-04-11T00:30:07Z" level=debug msg="response chan start" _block=waitHandling _module=control-plugin-execution 
time="2016-04-11T00:30:07Z" level=debug msg="kill chan start" _block=waitHandling _module=control-plugin-execution 
time="2016-04-11T00:30:07Z" level=debug msg="plugin response (ok) received" _block=waitHandling _module=control-plugin-execution 
time="2016-04-11T00:30:07Z" level=debug msg="Getting plugin config" _block_=getPluginConfigDataNode _module=config config-cache-key="0:mesosagent:1" config-cache-value=&{0xc8201ecda0 map[port:{5051} host:{10.180.10.180}]} 
time="2016-04-11T00:30:07Z" level=error msg="error in getting metric types" _block=load-plugin _module=control-plugin-mgr error="GetMetricTypes call error : Cannot find host in Global Config" plugin-type=collector 
time="2016-04-11T00:30:07Z" level=error msg="GetMetricTypes call error : Cannot find host in Global Config" _module="_mgmt-rest" 
time="2016-04-11T00:30:07Z" level=debug msg="Removing file (/tmp/192431333/snap-plugin-collector-mesosagent)" _module="_mgmt-rest" 
time="2016-04-11T00:30:07Z" level=info msg="API response" _module="_mgmt-rest" index=1 method=POST status="Internal Server Error" status-code=500 url="/v1/plugins"
```

The presence of the map in `config-cache-value` leads me to believe that my configuration JSON is correct, but alas, `config.GetConfigItems()` returns the following error:

```
Cannot find host in Global Config
```

Thoughts / tips?

**Comment by marcin-krolik** [comment]
Hi Rji,
Thanks a lot for your interest in snap! Unfortunately it seems that snap v0.13 release commit (ed2e620) does not support new global config layout. 
Please rebuild snap on latest commit from master (rebuild plugin as well), or alternatively you may move "plugins" sections outside "control" like in below example:

```json
{
  "control": {},
  "plugins": {
    "collector": {
      "mesosagent": {
        "all": {
           "host": "10.180.10.180",
           "port": 5051
         }
       }
    }
  },
  "publisher": {},
  "processor": {}
}
```

Let me know if that helps.

**Comment by rji** [comment]
Hey @marcin-krolik,

Thanks for the quick response! Unfortunately, I've tried both the old and new config formats already, against snap v0.12 and v0.13 (release, not master), with no luck. Modifying my config JSON to what you recommended with snap v0.13 (release) results in the same error, and I no longer see my config values in the map in the snap debug logs (where I did in my original post):

```
time="2016-04-11T16:09:07Z" level=debug msg="Getting plugin config" _block_=getPluginConfigDataNode _module=config config-cache-key="0:mesosagent:1" config-cache-value=&{0xc8201d3060 map[]} 
```

Changing the config file formats between versions (old config format for snap v0.12 and new config format for snap v0.13) yields the config map in the debug logs, so I think I'm on the right path there, but my plugin (and more specifically, snap-plugin-utilities/config) still can't seem to access those config values. Note that I haven't tried this on master yet; I'm hoping to stick to actual releases if at all possible.

**Comment by IRCody** [comment]
I tried to reproduce it with the v0.13 binary using the mock plugin but did not experience the same failures. [Code](https://github.com/IRCody/snap/blob/configTest/plugin/collector/snap-collector-mock1/mock/mock.go#L86) for the plugin here. It checks for host/port from config and returns an error if config.GetConfigItems errors and adds a metric at the namespace `/intel/mock/something/worked` if it doesn't.

The config I am using is:
```json
{
  "control": {
    "plugins": {
      "collector": {
        "mock": {
          "all": {
            "host": "10.180.10.180",
            "port": 5051
          }
        }
      }
    }
  }
}
```
The only change I made to your config was the plugin name. Does this seem like an accurate reproduction of what you are doing or am I missing a step? 

Can you check the contents of cfg.Table() inside your GetMetricTypes? An example of how this can be done is [here](https://github.com/IRCody/snap/blob/configTest/plugin/collector/snap-collector-mock1/mock/mock.go#L97-L98). That would help narrow down where the problem is.

**Comment by IzabellaRaulin** [comment]
I also was trying to reproduce that one for snap commit  6a3560f8a47362150abcb8ba3d38232151a6a24e (the last which is included for 0.13-beta release) - I created dedicated mock4 plugin which using snap-plugin-utilities to retrieving config items (with some helpful prints), and **everything works fine**.

The config file that I used:

```json
{
    "control": {
        "cache_ttl": "5s",
        "plugins": {
            "collector": {
                "mock": {
                    "all": {
                        "host": "10.101.102.103",
                        "port": 8086
                    }
                }
            },
            "publisher": {},
            "processor": {}
        }
    },
    "scheduler": {
        "default_deadline": "5s",
        "worker_pool_size": 5
    }
}
```

The command:
``` 
snapd -l 1 -t 0 --config ./myexample/configs/snap-config-sample.json
```

Below the most important fragment of this mock collector plugin - > **This mock plugin You can find on my [forked snap, branch global_config] (https://github.com/IzabellaRaulin/snap/tree/global_config) at snap/plugin/collector/snap-collector-mock4**

![image](https://cloud.githubusercontent.com/assets/11335874/14438990/18942f9a-0029-11e6-9864-707bd3a78a49.png)

![image](https://cloud.githubusercontent.com/assets/11335874/14439007/297416a4-0029-11e6-8ed5-21374bd6364a.png)

See also /tmp/snap-collector-mock4.stderr after loading this plugin.

**Comment by candysmurf** [comment]
I was able to reproduce this issue. The log is

DEBU[0014] Getting plugin config                         _block_=getPluginConfigDataNode _module=config config-cache-key=0:elasticsearch:1 config-cache-value=&{0x820deedb0 map[]}
ERRO[0014] error in getting metric types                 _block=load-plugin _module=control-plugin-mgr error=unexpected EOF plugin-type=collector

**Comment by rji** [comment]
Hey everyone,

Thanks for your quick replies and all of your help up to this point!

Despite what the snap logs said previously (`config-cache-value=&{0xc8201ecda0 map[port:{5051} host:{10.180.10.180}]}`),
which lead me to believe snap was behaving properly, I was seeing the following after I started printing out `cfg.Table()`:

```
GetMetricTypes call error : error getting config map[]: Cannot find host in Global Config, actual config table: map[]
```

One thing I noticed about @IzabellaRaulin's Mock v4's Godeps was that it was using Go 1.5, and up to this point I had been using Go 1.6. So I took a look at the [go 1.6 release notes](https://golang.org/doc/go1.6):
> The runtime has added lightweight, best-effort detection of concurrent misuse of maps. As always, if one goroutine is writing to a map, no other goroutine should be reading or writing the map concurrently. If the runtime detects this condition, it prints a diagnosis and crashes the program. The best way to find out more about the problem is to run the program under the race detector, which will more reliably identify the race and give more detail.

So I downgraded to Go 1.5 and attempted to run through everything again:

```
$ snapctl plugin load build/rootfs/snap-plugin-collector-mesosagent 
Plugin loaded
Name: mesosagent
Version: 1
Type: collector
Signed: false
Loaded Time: Mon, 11 Apr 2016 19:57:42 UTC
```

From what I can tell, this appears to be an issue accessing snap's config map from the snap-plugin-utilities, but only in Go 1.6 (and possibly newer).

**Comment by IRCody** [comment]
I'm using go1.6 and not having the issue so I'm not sure that is the cause. The concurrent use(or misuse) of maps doesn't seem like it would be the issue since it would crash the program instead of giving you a not-found error.

When changing to go1.5 did you also `go get github.com/intelsdi-x/snap` to get the imports for your pluging (control/{plugin, cpolicy}, etc)? I'm wondering if there might have been a mismatch between the way config was working in your previous pull of snap and the fresh one you (might've) pulled when switching to go1.5.

**Comment by rji** [comment]
Hey @IRCody,

When I downgraded to Go 1.5, I destroyed my development environment and brought it up clean. To prove the 1.5 vs 1.6 theory, I just destroyed it again and re-deployed with Go 1.6, and now the plugin won't load again (due to an empty config map).

A bit about my setup:
* I installed snap v0.13 to `/usr/local/snap` via the binaries hosted on GitHub
* I installed Go from the official binaries on golang.org
* I'm using godep in my project, and each time I build the plugin I'm bringing in snap via `godep restore`

For what it's worth, here are the contents of my `Godeps.json`, pointing at the snap v0.13 release commit:

```json
{
	"ImportPath": "github.com/rji/snap-plugin-collector-mesosagent",
	"GoVersion": "go1.6",
	"GodepVersion": "v62",
	"Deps": [
		{
			"ImportPath": "github.com/Sirupsen/logrus",
			"Comment": "v0.10.0",
			"Rev": "4b6ea7319e214d98c938f12692336f7ca9348d6b"
		},
		{
			"ImportPath": "github.com/gopherjs/gopherjs/js",
			"Comment": "go1.5-43-gf10744b",
			"Rev": "f10744b1512e8cf31ec55b49ddeb1c93ed2de46e"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap-plugin-utilities/config",
			"Rev": "fab7eb9d5ffe54a246333468cbbfe689b4070633"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/control/plugin",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/control/plugin/cpolicy",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/control/plugin/encoding",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/control/plugin/encrypter",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/core",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/core/cdata",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/core/ctypes",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/core/serror",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/pkg/ctree",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/pkg/schedule",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/intelsdi-x/snap/scheduler/wmap",
			"Comment": "v0.13.0-beta",
			"Rev": "ed2e620679f19950c660b3c44ce5a2f8e67eae17"
		},
		{
			"ImportPath": "github.com/jtolds/gls",
			"Comment": "v4.2.0",
			"Rev": "8ddce2a84170772b95dd5d576c48d517b22cac63"
		},
		{
			"ImportPath": "github.com/robfig/cron",
			"Comment": "v1-16-g0f39cf7",
			"Rev": "0f39cf7ebc65a602f45692f9894bd6a193faf8fa"
		},
		{
			"ImportPath": "github.com/smartystreets/assertions",
			"Comment": "1.6.0-2-g2d74a41",
			"Rev": "2d74a419fbe076f8c76ed8b1c7c633a676c5dc63"
		},
		{
			"ImportPath": "github.com/smartystreets/assertions/internal/go-render/render",
			"Comment": "1.6.0-2-g2d74a41",
			"Rev": "2d74a419fbe076f8c76ed8b1c7c633a676c5dc63"
		},
		{
			"ImportPath": "github.com/smartystreets/assertions/internal/oglematchers",
			"Comment": "1.6.0-2-g2d74a41",
			"Rev": "2d74a419fbe076f8c76ed8b1c7c633a676c5dc63"
		},
		{
			"ImportPath": "github.com/smartystreets/goconvey/convey",
			"Comment": "1.6.1-20-gcc5d85f",
			"Rev": "cc5d85f4f15bd2163abf0fe6e6753356dde72aa2"
		},
		{
			"ImportPath": "github.com/smartystreets/goconvey/convey/gotest",
			"Comment": "1.6.1-20-gcc5d85f",
			"Rev": "cc5d85f4f15bd2163abf0fe6e6753356dde72aa2"
		},
		{
			"ImportPath": "github.com/smartystreets/goconvey/convey/reporting",
			"Comment": "1.6.1-20-gcc5d85f",
			"Rev": "cc5d85f4f15bd2163abf0fe6e6753356dde72aa2"
		},
		{
			"ImportPath": "golang.org/x/sys/unix",
			"Rev": "9eef40adf05b951699605195b829612bd7b69952"
		},
		{
			"ImportPath": "gopkg.in/yaml.v2",
			"Rev": "a83829b6f1293c91addabc89d0571c246397bbf4"
		}
	]
}
```

Unfortunately, I don't know much more than what I've shared here at this point, other than I can seem to reproduce it rather reliably. I'm happy to open up the repo to my development environment (it's all Vagrant based) if you'd want to have a closer look.

**Comment by IRCody** [comment]
@rji: Thanks for going to the effort to try that. I can look at your repo tomorrow if it's not to much trouble so I can try to track down the issue.

**Comment by rji** [comment]
@IRCody No problem, thanks for your help on this! The Vagrant environment is over at https://github.com/rji/vagrant-mesos-snap, and specifically you'd want to change the value of `GOLANG_RELEASE` at https://github.com/rji/vagrant-mesos-snap/blob/master/Vagrantfile#L7. It isn't anything too complex, just a shell script that sets up a bunch of services that I'm working with on a single host.

**Comment by IRCody** [comment]
@rji: Took some time to look at your environment. I can't get it to fail on 1.6 (I haven't tried 1.5 yet) with my example plugin so there must be something else I'm missing. The steps I took were:
* Start vm using the vagrant file above
* Set gopath
* go get github.com/intelsdi-x/snap-plugin-utilities + go get github.com/intelsdi-x/snap (because the mock plugin lives here)
* checked out snap repo at `ed2e620679f19950c660b3c44ce5a2f8e67eae17` -- same as commit from your Godeps.jso
* made slight modifications to the mock plugin to use config.GetConfigItems() and print out results to stdout when found. Then build this plugin. My getMetricTypes looks like:
```go
//GetMetricTypes returns metric types for testing
func (f *Mock) GetMetricTypes(cfg plugin.PluginConfigType) ([]plugin.PluginMetricType, error) {
        mts := []plugin.PluginMetricType{}
        things, err := config.GetConfigItems(cfg, []string{"host", "port"})
        if err != nil{
                return nil, err
        } else {
                for k, v := range things {
                        fmt.Println(k, ":", v)
                }
                mts = append(mts, plugin.PluginMetricType{Namespace_: []string{"something", "worked"}})
        }
        if _, ok := cfg.Table()["test-fail"]; ok {
                return mts, fmt.Errorf("missing on-load plugin config entry 'test'")
        }
        if _, ok := cfg.Table()["test"]; ok {
                mts = append(mts, plugin.PluginMetricType{Namespace_: []string{"intel", "mock", "test"}})
        }
        mts = append(mts, plugin.PluginMetricType{Namespace_: []string{"intel", "mock", "foo"}})
        mts = append(mts, plugin.PluginMetricType{Namespace_: []string{"intel", "mock", "bar"}})
        mts = append(mts, plugin.PluginMetricType{
                Namespace_: []string{"intel", "mock", "*", "baz"},
                Labels_:    []core.Label{{Index: 2, Name: "host"}},
        })
        return mts, nil
}
```

The config file I'm using is the same as yours (except for the name of the plugin):
```json
{
  "control": {
    "plugins": {
      "collector": {
        "mock": {
          "all": {
            "host": "10.180.10.180",
            "port": 5051
          }
        }
      }
    }
  }
}
```

I ran snapd with `$SNAP_PATH/bin/snapd -t 0 -l 1 --config test-config.json`. Then `snapctl plugin load /path/to/my/plugin`. The output I get on stdout (in /tmp/<plugin-name>.stdout) is:
```
vagrant@vagrant-ubuntu-trusty-64$ cat /tmp/snap-collector-mock1.stdout
2016/04/12 17:30:06 port : 5051
2016/04/12 17:30:06 host : 10.180.10.180
```

So I am getting the port/host. Are there any differences in the method I'm using vs the one you are using to start your plugin? The most obvious one I can think of is Godeps which I tried to simulate by building against snap repo at the same commit as your godeps.json is set to. Other than that I'm not sure what to try next.

**Comment by rji** [comment]
Hey @IRCody, thanks for taking the time to look into this deeper! From what you've tried so far, it sounds like you should've been able to reproduce the with the mock plugin. To be honest, I haven't had time yet to try out the mock plugin that you folks linked me to the other day. Since it's pretty barebones, let me give that a shot and see if I can reproduce it on my side. Sorry that I don't have more info for you yet; as you could imagine this one has me a bit stumped as well :)

**Comment by IRCody** [comment]
I have a feeling it might be something to do with godeps. I tried to check snap out at the same commit you had in your godeps.json but maybe I'm missing another dependency?

As far as trying out the mock plugin -- You can go to your snap repo and copy/paste the GetMetricTypes() code above over the one for mock1 plugin inside snap/plugin/collector/snap-collector-mock1/mock/mock.go and run go build and load that one and see if it's still happening.

**Comment by rji** [comment]
Hey @IRCody, great catch! It does appear this is godeps related, and that the change in Go was just a red herring. I noticed that my Makefile wasn't properly cleaning up `vendor/` before rebuilding, so that actually remained consistent across go versions and my destroying / recreating the development environment. I'm not sure if there's anything else that needs to be tracked on this specific ticket, but I certainly appreciate your help here!
