### ISSUE TITLE
RecordFailure in scheduler/task.go used inconsistently between job types

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#858]
Usage of [RecordFailure()](https://github.com/intelsdi-x/snap/blob/master/scheduler/task.go#L359) is inconsistent between [collect](https://github.com/intelsdi-x/snap/blob/master/scheduler/workflow.go#L319) and [process](https://github.com/intelsdi-x/snap/blob/master/scheduler/workflow.go#L407)/[publish](https://github.com/intelsdi-x/snap/blob/master/scheduler/workflow.go#L449). 

`errors := t.manager.Work(j).Promise.Await()`

For process and publish we are sending errors to RecordFailure(), for collect we are sending j.Errors(). Is this expected/correct? It's not clear to me which one should be sent to RecordFailure() or if some other behavior is desired.

There is also a related issue where RecordFailure will panic if len(e) == 0 since it doesn't check before indexing directly into e. Because on collect it is called with j.Errors(), without first checking j.Errors length (but len(errors) is checked), it is possible for the length to be 0.

**Comment by geauxvirtual** [comment]
I've started to look into this. It appears we have two sets of errors that can be returned by `errors := t.manager.Work(j).Promise.Await()`, actual job errors during the running of the job and promise errors. Job errors will get added to Job().Errors() and returned when the job completes, which will populate `errors` (https://github.com/intelsdi-x/snap/blob/master/scheduler/worker.go#L59). However, promise errors do not get added to the job, and are returned to `errors` through the chain of calls from `AwaitUntil()`, and `Await()` . This is the case I see where `errors` could be greater than `0`, but `Job().Errors()` is `0` causing the panic.

It seems in the first call to `errors := t.manager.Work(j).Promise.Await()`, errors should be passed to `RecordFailures()`, which is the existing behavior for Process and Publish jobs.

**Comment by candysmurf** [comment]
@geauxvirtual & @IRCody, I just read the issue. May I ask 

1. if j.Errors() is not empty, should the program record the error and *return*?
2. If the answer is to continue calling *errors := t.manager.Work(j).Promise.Await()" no matter if j.Errors is empty or not, then concatenating both errors together and send them into RecordFailure, will that be enough?

Please share your thoughts. thank you.
