### ISSUE TITLE
snap-plugin-collector-libvirt does not report all value

### ISSUE THREAD

**Issue by redmask11** [intelsdi-x/snap#881]
I have two vms running on my physical server, like below:
root@controller:~# virsh list --all
 Id    Name                           State
----------------------------------------------------
 2     instance-00000022              running
 5     instance-0000002d              running

I use snap-plugin-collector-libvirt to collect all data and publish it to file, here is my task json file:
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "10s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/libvirt/controller/*/cpu/cputime":{},
                "/libvirt/controller/*/mem/actual_balloon":{},
                "/libvirt/controller/*/mem/available":{},
                "/libvirt/controller/*/mem/major_fault":{},
                "/libvirt/controller/*/mem/max":{},
                "/libvirt/controller/*/mem/mem":{},
                "/libvirt/controller/*/mem/min_fault":{},
                "/libvirt/controller/*/mem/nr":{},
                "/libvirt/controller/*/mem/rss":{},
                "/libvirt/controller/*/mem/swap_in":{},
                "/libvirt/controller/*/mem/swap_out":{},
                "/libvirt/controller/*/mem/unused":{}
            },
            "publish": [
                {
                    "plugin_name": "file",
                    "config": {
                        "file": "/tmp/publish"
                    }
                }
            ]
        }
    }
}

root@controller:~/snap/demo-snap# snapctl metric list
NAMESPACE                                                        VERSIONS
/libvirt/controller/*/cpu/cputime                                5
/libvirt/controller/*/mem/actual_balloon                         5
/libvirt/controller/*/mem/available                              5
/libvirt/controller/*/mem/major_fault                            5
/libvirt/controller/*/mem/max                                    5
/libvirt/controller/*/mem/mem                                    5
/libvirt/controller/*/mem/min_fault                              5
/libvirt/controller/*/mem/nr                                     5
/libvirt/controller/*/mem/rss                                    5
/libvirt/controller/*/mem/swap_in                                5
/libvirt/controller/*/mem/swap_out                               5
/libvirt/controller/*/mem/unused                                 5
/libvirt/controller/instance-00000022/cpu/cputime                5
/libvirt/controller/instance-00000022/cpu/vcpu/0/cputime         5
/libvirt/controller/instance-00000022/cpu/vcpu/1/cputime         5
/libvirt/controller/instance-00000022/disk/vda/rdbytes           5
/libvirt/controller/instance-00000022/disk/vda/rdreq             5
/libvirt/controller/instance-00000022/disk/vda/wrbytes           5
/libvirt/controller/instance-00000022/disk/vda/wrreq             5
/libvirt/controller/instance-00000022/mem/actual_balloon         5
/libvirt/controller/instance-00000022/mem/available              5
/libvirt/controller/instance-00000022/mem/major_fault            5
/libvirt/controller/instance-00000022/mem/max                    5
/libvirt/controller/instance-00000022/mem/mem                    5
/libvirt/controller/instance-00000022/mem/min_fault              5
/libvirt/controller/instance-00000022/mem/nr                     5
/libvirt/controller/instance-00000022/mem/rss                    5
/libvirt/controller/instance-00000022/mem/swap_in                5
/libvirt/controller/instance-00000022/mem/swap_out               5
/libvirt/controller/instance-00000022/mem/unused                 5
/libvirt/controller/instance-0000002d/cpu/cputime                5
/libvirt/controller/instance-0000002d/cpu/vcpu/0/cputime         5
/libvirt/controller/instance-0000002d/disk/vda/rdbytes           5
/libvirt/controller/instance-0000002d/disk/vda/rdreq             5
/libvirt/controller/instance-0000002d/disk/vda/wrbytes           5
/libvirt/controller/instance-0000002d/disk/vda/wrreq             5
/libvirt/controller/instance-0000002d/mem/actual_balloon         5
/libvirt/controller/instance-0000002d/mem/available              5
/libvirt/controller/instance-0000002d/mem/major_fault            5
/libvirt/controller/instance-0000002d/mem/max                    5
/libvirt/controller/instance-0000002d/mem/mem                    5
/libvirt/controller/instance-0000002d/mem/min_fault              5
/libvirt/controller/instance-0000002d/mem/nr                     5
/libvirt/controller/instance-0000002d/mem/rss                    5
/libvirt/controller/instance-0000002d/mem/swap_in                5
/libvirt/controller/instance-0000002d/mem/swap_out               5
/libvirt/controller/instance-0000002d/mem/unused                 5

root@controller:~/snap/demo-snap# snapctl task watch 006f7e99-4017-4c51-ad2c-698795027d0b
Watching Task (006f7e99-4017-4c51-ad2c-698795027d0b):
NAMESPACE                                                        DATA            TIMESTAMP                                       SOURCE
/libvirt/controller/instance-0000002d/cpu/cputime                14210000000     2016-04-27 01:13:59.218062575 -0400 EDT         controller
/libvirt/controller/instance-0000002d/cpu/cputime                3108910000000   2016-04-27 01:13:59.220301598 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/actual_balloon         4194304         2016-04-27 01:13:59.231300627 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/actual_balloon         65536           2016-04-27 01:13:59.226170392 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/available              0               2016-04-27 01:13:59.237051842 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/available              0               2016-04-27 01:13:59.242251192 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/major_fault            696             2016-04-27 01:13:59.252869535 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/major_fault            0               2016-04-27 01:13:59.247979223 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/max                    65536           2016-04-27 01:13:59.186531282 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/max                    4194304         2016-04-27 01:13:59.188725875 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/mem                    4194304         2016-04-27 01:13:59.193724255 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/mem                    65536           2016-04-27 01:13:59.191489805 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/min_fault              478474          2016-04-27 01:13:59.204687113 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/min_fault              0               2016-04-27 01:13:59.199485476 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/nr                     0               2016-04-27 01:13:59.161261599 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/nr                     0               2016-04-27 01:13:59.155908468 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/rss                    0               2016-04-27 01:13:59.172605889 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/rss                    104808          2016-04-27 01:13:59.167176599 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/swap_in                0               2016-04-27 01:13:59.210279145 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/swap_in                0               2016-04-27 01:13:59.215287744 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/swap_out               0               2016-04-27 01:13:59.183739084 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/swap_out               0               2016-04-27 01:13:59.178371876 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/unused                 0               2016-04-27 01:13:59.258578891 -0400 EDT         controller
/libvirt/controller/instance-0000002d/mem/unused                 0               2016-04-27 01:13:59.2635737 -0400 EDT           controller

My question is : why task watcher outputs vm's data whose name is instance-0000002d twice but not display daat for vm  instance-00000022? any error in snap agent?seems plugin is right from listed metrics from plugin.

**Comment by tiffanyfj** [comment]
Hey. If you look at the file, /tmp/publish, does it show instance-00000022 or does it also look like watch? Thanks.

**Comment by redmask11** [comment]
same as the watch output

**Comment by redmask11** [comment]
Anyone can help to take a look at the issue, thanks!

**Comment by redmask11** [comment]
By the way, does snap-plugin-collector-libvirt can collect data dynamically with vm add or remove?
from my test, it only display running vm's metrics when start task. 
if user start one more vm after then, task won't collect that vm's data, any good suggestion for this problem?

**Comment by sandlbn** [comment]
@redmask11 it's not possible to dynamically query libvirt daemon now for new VM's. This will be supported in a future releases and it's depended on snap framework features.

**Comment by sandlbn** [comment]
@redmask11 I checked on my dev machine and everything is fine with data from 2 different domains.

Watching Task (89a6cc6e-644f-45a2-b051-20e44814c4be):
NAMESPACE 					 DATA 		 TIMESTAMP 					 SOURCE
/libvirt/generic/cpu/cputime 			 1.052e+10 	 2016-04-27 15:18:50.356201254 +0100 IST 	 generic
/libvirt/vagrant_operator/cpu/cputime 		 1.525e+10 	 2016-04-27 15:18:50.35741336 +0100 IST 	 vagrant_operator
/libvirt/vagrant_operator/mem/available 	 0 		 2016-04-27 15:18:50.361121626 +0100 IST 	 vagrant_operator
/libvirt/vagrant_operator/mem/max 		 4.194304e+06 	 2016-04-27 15:18:50.362140369 +0100 IST 	 vagrant_operator
/libvirt/vagrant_operator/mem/rss 		 732528 	 2016-04-27 15:18:50.355080207 +0100 IST 	 vagrant_operator

**Comment by redmask11** [comment]
@sandlbn in your task the "generic" and "vagrant_operator" is host name of physical server but not vm name,right?
seems the metrics is different in you task and my mask.
in my mind ,the metrics should be like : /libvirt/+hostname+vmname+cpu/cputime,
could you share with me you task json file?
besides, I used  snapd and libvirt plugin from official relaese "v0.13.0-beta",which version do you used?

**Comment by sandlbn** [comment]
@redmask11 I'm using 0.13.0-beta and I'm a 2 commits ahead from your version. But I didn't change any logic in plugin except I removed hostname from namespace and I moved it to the tag section. Can u open this bug against plugin https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/new ? not snap ? please mention your libvirt version and operating system also please paste your task manifest. We where checking libvirt plugin on Ubuntu 14.04 and Centos 7 and Fedora 21-23 .

**Comment by redmask11** [comment]
move to libvirt issue list, thanks.

**Comment by IzabellaRaulin** [comment]
Moved to https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/20
