### ISSUE TITLE
How to collect disk usage and net usage for each vm

### ISSUE THREAD

**Issue by redmask11** [intelsdi-x/snap#882]
Could anyone tell me how to define task json file to get disk read/write bytes and net rx/tx bytes for each vm?   seems snap-plugin-collector-libvirt only export * metrics for cpu and memory:
/libvirt/controller/*/cpu/cputime                                5
/libvirt/controller/*/mem/actual_balloon                         5
/libvirt/controller/*/mem/available                              5
/libvirt/controller/*/mem/major_fault                            5
/libvirt/controller/*/mem/max                                    5
/libvirt/controller/*/mem/mem                                    5
/libvirt/controller/*/mem/min_fault                              5
/libvirt/controller/*/mem/nr                                     5
/libvirt/controller/*/mem/rss                                    5
/libvirt/controller/*/mem/swap_in                                5
/libvirt/controller/*/mem/swap_out                               5
/libvirt/controller/*/mem/unused 

so i can define workflow in task json file to get cpu and memory metrics.
 "workflow": {
        "collect": {
            "metrics": {
                "/libvirt/controller/*/cpu/cputime":{},
                "/libvirt/controller/*/mem/mem":{},

How should I do to get disk & net tx/rx bytes for each vm?

**Comment by sandlbn** [comment]
@redmask11  Can u open this bug against libvirt plugin  ? 

But for machine with configured nic or bridge you should get 

/libvirt/generic/cpu/cputime 		 5
/libvirt/generic/cpu/vcpu/0/cputime 	 5
/libvirt/generic/disk/hda/rdbytes 	 5
/libvirt/generic/disk/hda/rdreq 	 5
/libvirt/generic/disk/hda/wrbytes 	 5
/libvirt/generic/disk/hda/wrreq 	 5
/libvirt/generic/mem/actual_balloon 	 5
/libvirt/generic/mem/available 		 5
/libvirt/generic/mem/major_fault 	 5
/libvirt/generic/mem/max 		 5
/libvirt/generic/mem/mem 		 5
/libvirt/generic/mem/min_fault 		 5
/libvirt/generic/mem/nr 		 5
/libvirt/generic/mem/rss 		 5
/libvirt/generic/mem/swap_in 		 5
/libvirt/generic/mem/swap_out 		 5
/libvirt/generic/mem/unused 		 5
/libvirt/generic/net/vnet0/rxbytes 	 5
/libvirt/generic/net/vnet0/rxdrop 	 5
/libvirt/generic/net/vnet0/rxerrs 	 5
/libvirt/generic/net/vnet0/rxpackets 	 5
/libvirt/generic/net/vnet0/txbytes 	 5
/libvirt/generic/net/vnet0/txdrop 	 5
/libvirt/generic/net/vnet0/txerrs 	 5
/libvirt/generic/net/vnet0/txpackets 	 5

from metric list command. Can you include xml config for your domain ?

**Comment by IRCody** [comment]
Closing this issue since it looks like another more specific one is open on the [libvirt plugin](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/20) here.
