### ISSUE TITLE
failed to load mysql collector plugin

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap#895]
receiving error:
Error loading plugin:
unexpected EOF

**Comment by geauxvirtual** [comment]
Can you provide more detail?

Version of Snap?

Version of MySQL collector plugin?

Are you passing in a global configuration for the mysql plugin when starting snapd?

Documentation for the global configuration requirements for this plugin can be found here: https://github.com/intelsdi-x/snap-plugin-collector-mysql#global-config

**Comment by mjbrender** [comment]
+1 to @geauxvirtual's observation. This is most likely a situation where you cannot load a plugin that doesn't have the required configuration options. MySQL, like a few others, require a global configuration. You'd start `snapd` like this: 

```
$ bin/snapd -l 1 -t 0 --config config.json
```

Where your `config.json` file includes `"mysql_connection_string"` and `"mysql_use_innodb"`. Here's the example [from the plugin repository](https://github.com/intelsdi-x/snap-plugin-collector-mysql/blob/master/examples/configs/config.json): 

```
{
    "control": {
        "cache_ttl": "5s"
    },
    "scheduler": {
        "default_deadline": "5s",
        "worker_pool_size": 5
    },
    "plugins": {
        "collector": {
	    "mysql": {
                "all": {
                    "mysql_connection_string": "root:test@tcp(localhost:3306)",
	                "mysql_use_innodb": false
                }
            }

        },
        "publisher": {},
        "processor": {}
    }
}
```

**Comment by lynxbat** [comment]
Probably a bug here on better logging for config (if there isn't a bug already open).

**Comment by imvisiontech** [comment]
that's indeed what I was missing when runnig the snapd.
thanks.

**Comment by IzabellaRaulin** [comment]
Move to mysql collector issue list, thanks.
