### ISSUE TITLE
Add validation of keys in config

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#898]
When snapd is started with a global config file the user should receive an 
error if invalid keys are present.  Snapd should not start if an invalid 
config is provided.

**Comment by IRCody** [comment]
I think we need a more specific definition for what makes a config invalid. Are all the sections required? If not what is the minimum set of options we are going to require?

Some things that definitely make a config invalid:
* Invalid/unknown keys
* Valid keys in invalid positions
