### ISSUE TITLE
No output for which port was selected dynamically

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#900]
When specifying a rest api port of '0', a dynamic port is selected but the port is not output to the user.

```
INFO[0000] Starting REST API on :0                       _module=_mgmt-rest
```

**Comment by geauxvirtual** [comment]
Why would we even support this through snapd?

**Comment by IRCody** [comment]
Unsure if it was intended but snap currently supports it (i.e. specifying port 0 causes a dynamic port to be chosen). This issue was to decide if we want to continue with that (then we need to adjust the output) or disallow that.
