### ISSUE TITLE
Collector and Publisher plugin for EXASOL DB

### ISSUE THREAD

**Issue by mkempken** [intelsdi-x/snap#906]
It would be great if we could use our analytic in-memory database for storing metrics (publisher) and it would be also great if it was possible to query our build in EXA_STATISTICS schema for database performance metrics (collector). Should be easy to connect using Linux ODBC.
Free community edition (prebuild virtual machine) can be found here https://www.exasol.com/portal/display/DOWNLOAD/Free+Trial

**Comment by mjbrender** [comment]
@mkempken thanks for the recommendation. These plugins are best when written by someone who knows the target product and none of our maintainers are not familiar with this one. Do you or another exasoldb user want to write a plugin? 

You could use the InfluxDB plugin as a template to follow along with our documentation.

**Comment by mkempken** [comment]
@mjbrender thanks for your answer. I'll get in contact with our R&D to see if we can get resources for adopting the influxdb plugins. Thanks

**Comment by mkempken** [comment]
@mjbrender Unfortunately, the influxdb plugin won't work for us because we require an ODBC or JDBC driver to communicate with our database...

**Comment by thomastaylor312** [comment]
@mkempken I think @mjbrender means to use the Influx plugin as an example
to follow while building your own.

**Comment by mjbrender** [comment]
Exactly @mkempken, what @thomastaylor312 stated. We are very supportive of you writing a plugin to publish or collect from EXASOL DB since we won't be able to get to that ourselves anytime soon.

**Comment by IRCody** [comment]
@mkempken: Closing this issue. Feel free to open another one or contact us on [gitter](https://gitter.im/intelsdi-x/snap) if you have any questions about writing a plugin.
