### ISSUE TITLE
godep speter.net/go/exp/math/dec/inf dependency failure

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap#914]
This repository does not appear to be available anymore on code.google.com and our godep needs to be updated accordingly:

```
❯ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make deps
bash -c "./scripts/deps.sh"
Getting godep if not found
Checking snap root for deps
# cd .; git clone https://code.google.com/p/go-decimal-inf.exp /Users/nanliu/gopath/src/speter.net/go/exp/math/dec/inf
Cloning into '/Users/nanliu/gopath/src/speter.net/go/exp/math/dec/inf'...
fatal: repository 'https://code.google.com/p/go-decimal-inf.exp/' not found
godep: error downloading dep (speter.net/go/exp/math/dec/inf): exit status 128
godep: Error downloading some deps. Aborting restore and check.
make[1]: *** [deps] Error 1
make: *** [default] Error 2
```

**Comment by nanliu** [comment]
This is related to: https://github.com/kubernetes/kubernetes/issues/23529

**Comment by IRCody** [comment]
Looks like the repo is now located at [https://gopkg.in/inf.v0](https://gopkg.in/inf.v0). Tried searching for where it was used but couldn't find any references to "speter.net". Are we using this anywhere?

**Comment by geauxvirtual** [comment]
This is the inherent problem with Godeps. It's a dependency of a dependency. Godep tries to load every dependency our project requires, which involves getting dependencies that our dependency needs to load.

**Comment by obourdon** [comment]
Seems like this issue can be closed
https://github.com/intelsdi-x/snap/commit/1d87e72dfaa0f9555e6e7711a5e24cd1daedaf6d
worked for me
