### ISSUE TITLE
Feature Request: Add tag display to watch command in snapctl by passing a verbose flag

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#924]
When using snapctl to watch a task, a user should be able to pass a `-v` or `--verbose` flag to the watch command to see the tags associated with metrics being collected for the task. The REST API already supports returning tags for the metrics during watch, so this is just adding the ability to view the tags via snapctl.

**Comment by IRCody** [comment]
Closed by #912.
