### ISSUE TITLE
pass taskId to collectMetrics method in plugins

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap#940]
I have a use case for needing to know the previous metrics collected when collecting new metrics.
Though i can use a unique identifier passed through the configPolicy, exposing the taskId to collectMetrics would be ideal.

**Comment by marcin-krolik** [comment]
@woodsaj : do you think t's possible to achieve your goal with tagging metrics in the task manifest? There is opened PR #941  to Snap framework which introduces such functionality. This way  your metrics from given task manifest could be tagged with some unique identifier of your choice.

**Comment by woodsaj** [comment]
yep, that could work.

**Comment by IRCody** [comment]
@woodsaj: Since #941 was merged is it ok to close this issue?
