### ISSUE TITLE
Publishing metric extended from dynamic elemenets

### ISSUE THREAD

**Issue by marcin-krolik** [intelsdi-x/snap#949]
There are uses cases where parts of a metric namespace is undesirable in published metric. 

Let's say that some ```foo``` collector provides such ```/intel/foo/*/power```, where wildcard is a dynamic metric element which expands to host IP address. This way what is returned from ```CollectMetrics``` is expanded to ```/intel/foo/1.1.1.1/power```, ```/intel/foo/1.1.1.2/power``` and ```/intel/foo/1.1.1.3/power```. 
As a end user I don't want to have my timeseries DB populated with such metrics. I prefer to have simpler metric ```/intel/foo/power``` tagged with ```host_ip: 1.1.1.x```. 

Before introduction of new metric schema and ```core.Namespace```, it was possible to provide ```metric.Label_```, which in turned was used in timeseries publishers like ```snap-plugin-publisher-influxdb``` to remove unwanted namespace elements from metric and save them as tags. 

Currently it seems we don't have any mechanism which would allow similar action.

### Solution 1
Introduction of additional field in ```NamespaceElement``` to allow publisher to "see" unwanted namespace elements and turn them into tags.

```go
type NamespaceElement struct {
	Value       string
	Description string
	Name        string
	Removable   bool
}

func (n Namespace) AddRemovableElement(value string) Namespace {
	nse := NamespaceElement{Value: value, Removable: true}
	return append(n, nse)
}
```
Above function would need to be used in collectors whenever dynamic element is expanded to set of available instances.

Additionally, all timeseries publishers would need to be enhanced by a generic function which would remove all ```removable``` elements from the namespace and turn them into tags.

Pros:
- generic solution which will work every time

Cons:
- requires change in the framework
- additional effort to implement generic function in publishers
- additional effort to implement change in some collector plugins

### Solution 2
New processor plugin which would serve as a "namespace filter". It would require regex expression provided in configuration and based on the regex it would remove namespace element which matches and turn it into a tag.

Pros:
- no changes to framework
- no changes to plugins

Cons:
- playing with regex gives ability to damage published metrics (namespace changed unintentionally)

cc: @intelsdi-x/snap-maintainers , @intelsdi-x/plugin-maintainers @PatrykMatyjasek @mkuculyma

**Comment by marcin-krolik** [comment]
As for the second solution, processor is ready [ns-filter](https://github.com/intelsdi-x/snap-plugin-processor-ns-filter/pull/1)

**Comment by candysmurf** [comment]
ns-filter gave me 404. Would you please lift the restriction?

From my understanding, a namespace is a unique identifier. You can always define tags at your will to fit your needs. Do I miss anything?

**Comment by marcin-krolik** [comment]
@candysmurf: Settings updated. You should be able now to access the repo.

As for your question regarding namespace - yes, namespace is unique identifier, and yes, you are free to define tags. Problem is with publishing to time series dbs like InfluxDB. Example, when someone gathers power metric from 300 hosts, and metrics are like that

```
/intel/foo/1.1.1.1/power
/intel/foo/1.1.1.2/power
/intel/foo/1.1.1.3/power
...
/intel/foo/1.1.1.350/power
```

If metrics are being stored exactly like that in InfluxDB it's completely useless. It would be much simpler to store ```/intel/foo/power``` each data point with added tag ```host_ip: 1.1.1.X```, query and display such metrics in Grafana. It seems in real use case people don't want things like host IP embedded in metric namespace.

I hope it answered your question.

**Comment by IRCody** [comment]
I think this is already possible and being done in the influxdb publisher. See: [this](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/influx/influx.go#L163-L170). Is this what you were trying to do?

**Comment by marcin-krolik** [comment]
@IRCody : Well, but you have to take into account that collected metric **is no longer dynamic**. If metric of ```/intel/foo/*/power```` is being send to ```CollectMetric()```, it is expanded and returned as 
```
/intel/foo/1.1.1.1/power
/intel/foo/1.1.1.2/power
/intel/foo/1.1.1.3/power
...
/intel/foo/1.1.1.350/power
```
So instead of one dynamic metric, many static metrics are being returned. You cannot returned it as dynamic metric.

**Comment by marcin-krolik** [comment]
Probably my mistake in description of Solution 1 could have been misleading. I updated proposed implementation

**Comment by candysmurf** [comment]
@marcin-krolik, thanks for your explanation. I would say [ns-filter](https://github.com/intelsdi-x/snap-plugin-processor-ns-filter/pull/1) is a good start, but it's aimed at a host field. Maybe a more generic solution is needed. The question is if all such requirements should be Snap's burden or processors or even publishers?

**Comment by candysmurf** [comment]
@marcin-krolik, I implemented the dynamic metrics for Redfish. It's a full-fledged implementation regarding wildcard and pipes. For example, it allows wildcard at any position theoretically(although practically we may not have such use cases).  Should we have a meeting to discuss a generic solution so that it may benefit more plugins?

**Comment by marcin-krolik** [comment]
@candysmurf ns-filter is not targeted to host. It operates on any regular expresion provided. 

Generaly I think this issue can be closed as [this line](https://github.com/intelsdi-x/snap/blob/master/plugin/collector/snap-collector-mock1/mock/mock.go#L58) shows how to overcome my problem.
