### ISSUE TITLE
Yaml and JSON task files found in auto_discover_path should create tasks on snapd startup

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap#950]
It would be nice that when starting snapd with -a option (auto_discover_path) plugins are loaded as documented but after that, Yaml and JSON files found also trigger tasks creation and running state.

**Comment by IRCody** [comment]
I think that adding the ability to run tasks on startup would be good. I think a way to do it would be to have scheduler.Start() handle dealing with it(by passing the auto-discover-paths?). This would also potentially be a good point to move auto-discovered plugin loading out of snapd.go and into control.Start().

You could ensure that plugins are loaded before starting tasks just by making sure control.Start() is called before scheduler.Start().

**Comment by thomastaylor312** [comment]
I would love to see this. From a scalability standpoint I know that people with large environments will want a defined list of tasks to kick off automatically on every machine after a reboot when they start snapd. It would streamline the whole process.

**Comment by obourdon** [comment]
I have submitted PR [https://github.com/intelsdi-x/snap/pull/961] for the auto-discover-path code migration from snapd.go to control.go. Now working on rewriting the task auto discovery as suggested

**Comment by obourdon** [comment]
@IRCody : I have been playing around with the scheduler.Start() code and even though s.metricManager  seems to map control.pluginControl structure, I did not manage to be able to access its Config.AutoDiscoverPath field. I am pretty sure that this is due to my current lack of in-depth knowledge of Golang so could you please give me some hints on how to achieve this. Thanks

**Comment by obourdon** [comment]
@IRCody : seems like I finally got around this by exposing a new method (GetAutoDiscoverPaths) in the managesMetric interface. Currently testing the code

**Comment by IRCody** [comment]
@obourdon: Sorry I didn't see your comments in time to help but glad you found a way.
