### ISSUE TITLE
potential collisions in logs when several versions of the same plugin are running

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap#957]
As the snap framework provides this very nice & useful possibility to have a new version of a plugin to run side by side with a previous one we found out that this may rise an issue concerning plugin log files
because these are all located within the TMPDIR (/tmp under Linux & MacOSX) and their names is based on the plugin binary file name.

Therefore if the X plugin is uploaded with the same file name for both v1 and v2 the framework will happily accept this but the logs will all be /tmp/X.(stdout,stderr,log) for both v1 and v2

**Comment by IRCody** [comment]
Would a simple solution for this be to append the version to the filename? Something like `plugin-name.v1.{stdout,stderr,log}`?

**Comment by obourdon** [comment]
Definitely agree with your proposal, simple and efficient

**Comment by bjray** [comment]
Per offline conversations, we will create a new RFC for a more holistic logging approach for Snap.

**Comment by IzabellaRaulin** [comment]
Resolved by #1055. Logs are not longer send to an individual file from plugins. They are send to snapd's log.
