### ISSUE TITLE
libvirt plugin reports same instance instead of multiple instances when using *

### ISSUE THREAD

**Issue by beyossi** [intelsdi-x/snap#963]
the machine I use has 5 instances: instance-00000010, instance-00000015, instance-00000016, instance-0000001a and instance-0000001b. I am creating the task for libvirt * instances (see attached vm.json) but then the snap reports the metrics 5 times each for the same object (the higher instance number). sample output is attached.
This exact behaviour is consistent with other machines as well.

[vm.json.txt](https://github.com/intelsdi-x/snap/files/292776/vm.json.txt)
[outexample.txt](https://github.com/intelsdi-x/snap/files/292779/outexample.txt)

**Comment by lynxbat** [comment]
I linked the issue to the libvirt plugin. We will have someone troubleshoot this.

**Comment by sandlbn** [comment]
@lynxbat: I'll take a look tomorrow. @beyossi are you using binary version of plugin or you builder plugin from sources ?

**Comment by IzabellaRaulin** [comment]
@sandlbn, this issue is resolved, isn't it?

**Comment by mjbrender** [comment]
Hey all - this one is completed in the correct repo 🙌 https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/23

Thanks again to @beyossi for finding this one and for other maintains for connecting the dots 🎯
