### ISSUE TITLE
Add the ability to configure the number of task retries

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#967]
The task manifest should include an optional field for setting the number of times the task will be retried before failing.

The rest interface is currently setting retries to 10 ([here](https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/task.go#L98)).

Providing a value of -1 should indicate that the task should never go into a disabled state.

**Comment by iceycake** [comment]
Can we also pass -1 to the value so that the task will be never disabled by the error?

**Comment by elemoine** [comment]
It sounds to me that this issue is related to one I created on the Heka publisher plugin: https://github.com/intelsdi-x/snap-plugin-publisher-heka/issues/7.

**Comment by iceycake** [comment]
Any traction on this issue?  Our team is getting close to move on and want to use Snap in our environment.  However, this is currently a major deal breaker (e.g.  If there is connectivity issue with TSDB, I can image thousands of the servers running Snap will disable the task and there is no mechanism to auto restart them).

If there is no one active working on this issue, I can work on it and submit a PR.

**Comment by jcooklin** [comment]
@iceycake I am not aware of anyone working on this.

**Comment by lynxbat** [comment]
@iceycake A PR would be awesome on this. We are scoping an RFC for a buffering option that will handle temporary failures at a publisher level better also.

Let us know if you need some help with the PR. @tjmcs could help with how config is run in Snap.

**Comment by iceycake** [comment]
@lynxbat I did work on a publisher plugin (snap-plugin-publisher-cloudwatch) so I have some ideas on how the whole thing works.  Let me take a look this week and see if I can pull something quick.

**Comment by lynxbat** [comment]
Awesome @iceycake 

Looking forward to seeing it

**Comment by iceycake** [comment]
I have talked to @IRCody.  I will work on this issue as 2 separated pull request.  Submitted #1006 first just making the maximum # of failures customizable.  Will submit another pull request on infinite retries, which requires more works.
