### ISSUE TITLE
Inconsistencies in "snap metric list" output

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap#980]
I have a snapd daemon with two plugins loaded: snap-plugin-collector-cpu and snap-collector-mock2.

```
# snapctl plugin list
NAME             VERSION         TYPE            SIGNED          STATUS          LOADED TIME
cpu              2               collector       false           loaded          Thu, 09 Jun 2016 14:01:50 UTC
mock             2               collector       false           loaded          Thu, 09 Jun 2016 14:03:37 UTC
```

When I run `snapctl metric list` I get this output:

```
# snapctl metric list
NAMESPACE                                        VERSIONS
/intel/mock/*/baz                                2
/intel/mock/bar                                  2
/intel/mock/foo                                  2
/intel/procfs/cpu/0/active_jiffies               2
/intel/procfs/cpu/0/active_percentage            2
…
```

I am surprised to see a wildcard in the "baz" namespace (from the snap-collector-mock2 plugin), and **no** wildcard in the cpu namespaces (from the snap-plugin-collector-cpu). It looks to me that the plugins do not behave in the same way.

I'd expect the following sort of output:

```
# snapctl metric list
NAMESPACE                                        VERSIONS
/intel/mock/*/baz                                2
/intel/mock/bar                                  2
/intel/mock/foo                                  2
/intel/procfs/cpu/*/active_jiffies               2
/intel/procfs/cpu/*/active_percentage            2
```

What do you think? Is this an issue that should be reported to snap-plugin-collector-cpu (and possibly other plugins suffering the same issue)?

Thanks.

**Comment by jcooklin** [comment]
>Is this an issue that should be reported to snap-plugin-collector-cpu (and possibly other plugins suffering the same issue)?

Yes, issues should be opened on plugins that expose static namespaces where the schema, or in other words a dynamic namespace, would be appropriate.

I created https://github.com/intelsdi-x/snap-plugin-collector-cpu/issues/19l

**Comment by lmroz** [comment]
On of possible solutions of other issue also addresses this: https://github.com/intelsdi-x/snap/pull/977#issuecomment-225906150
