### ISSUE TITLE
RFC - Single Run Task

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap#985]
## Definition

A Single Run Task is a task where the workflow is going to be scheduled for execution immediately (at most once). The task is saved so that it may be run again easily simply by starting it again.
## Purpose

A single run task serves the following purposes:
- Allows a user to test a task end to end easily with 1 run through the workflow to ensure a task will work.
- Forms a sort of 'task library' for infrequently run tasks. 
## Desired User experience
- Specify a task as single run, Via task.json posted to rest 
- task specified as a single run can be run again easily by doing snapctl task start <task id>.
- not necessarily related – On the command line via snapctl by overwriting schedule type. 
## Implementation notes

Implement new, single run, scheduler type that runs a workflow once.
## Questions
- Should a request to run a single task block in rest to wait for exit code to send back as the response?
  Would be potentially useful for users who want to manage scheduler of a task directly without polling snap for task completion.

**Comment by lynxbat** [comment]
Wouldn't a schedule time that has a `start time` and `count` satisfy this need in the existing framework?
The UX for the CLI could have a friendly switch for single-run (set count==1).

The scheduler would execute the Task when the start time is current or in the past until the run count meets the count. If it is one it would execute once.

I am opposed to schedule type on the CLI unless the UX is considered. Manifest structure shouldn't impose on CLI UX.

**Comment by IRCody** [comment]
>Wouldn't a schedule time that has a start time and count satisfy this need in the existing framework?
The UX for the CLI could have a friendly switch for single-run (set count==1).

>The scheduler would execute the Task when the start time is current or in the past until the run count meets the count. If it is one it would execute once.

You meant schedule type not time? If so I think this makes sense. Seems simple enough implementation wise -- run n times vs run once.

>I am opposed to schedule type on the CLI unless the UX is considered. Manifest structure shouldn't impose on CLI UX.

The RFC wasn't attempting to take a position on whether the schedule type changing is explicit (via --schedule-type=x) or implicit (i.e. via something like `snapctl task create --run-count=1 -t task.json`). 

Is your position that we should only allow single-run to be defined in the task manifest? I think it could be useful to run an existing task just once without having to modify the manifest directly but don't feel super strongly about it.

**Comment by jackson-intel** [comment]
We're working on deploying some Intel collectors with SNAP and would like a feature like this one.

**Comment by IzabellaRaulin** [comment]
@intelsdi-x/snap-maintainers, @intelsdi-x/plugin-maintainers, @jackson-intel, @skonefal - do you have any comments or concerns which you would like to add to this RFC? We are planning to close this RFC by the end of the next week (2/17/2017) and focus on development.

**Comment by IzabellaRaulin** [comment]
Focusing on development. A pull request providing single run task will appear in this week.
