### ISSUE TITLE
Fix dependencies related to Kubernetes

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#986]
There is a dependency in the snap godep file that no longer exists in the kubernetes repo. This is causing godep restore to fail as it cannot change into this directory and try to checkout the dependency at the revision in the Godeps.json file. Also, it appears the commit kubernetes(and related dependencies) is pinned to in snap Godeps.json file is to a commit that has been reverted. These dependencies should be updated.

**Comment by elemoine** [comment]
I may be wrong, but it sounds like the same [issue](https://github.com/intelsdi-x/snap/issues/953) I had a while ago. I would like to verify that. How can I reproduce the problem exactly? Just run `godep restore`? Thanks.
