### ISSUE TITLE
Tasks running distributed workflow do not stop, error 10 times, then disable

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#987]
When trying to stop a task that is executing a distributed workflow, snapctl reports an error when trying to stop the task `No plugins found`. The task will eventually show as disabled when listing tasks via snapctl.

![screen shot 2016-06-10 at 5 20 45 pm](https://cloud.githubusercontent.com/assets/1395030/15981853/60d74a4a-2f30-11e6-9347-e06c01ed0b3e.png)

Node A (described below) shows the following errors in the log file when a task is attempted to be stopped. The task will try to execute 10 times following the stop command, failing each time and then becoming disabled.

![screen shot 2016-06-10 at 5 19 07 pm](https://cloud.githubusercontent.com/assets/1395030/15981780/5d76b9b8-2f2f-11e6-947c-5a14bf21a31f.png)

Setup: 
Node A:
  - Running the task
  - Loaded mock1, mock2, and processor plugins

Node B:
  - Loaded publisher plugin

Task being run
```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/mock/foo": {},
                "/intel/mock/bar": {},
                "/intel/mock/*/baz": {}
            },
            "config": {
                "/intel/mock": {
                    "name": "root",
                    "password": "secret"
                }
            },
            "process": [
                {
                    "plugin_name": "passthru",
                    "process": null,
                    "publish": [
                        {
                            "plugin_name": "file",
                            "target": "192.168.242.139:10082",
                            "config": {
                                "file": "/tmp/snap_published_mock_file.log"
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

**Comment by IRCody** [comment]
@geauxvirtual: Thanks for finding this. The root cause seems to be during unsubscribe we always checked for metrics to unsubscribe (even if none were present). I added a PR to address this issue by only going through the step of checking for metrics/collector plugins if at least 1 is present.
