### ISSUE TITLE
support for CORS headers

### ISSUE THREAD

**Issue by brharrington** [intelsdi-x/snap#998]
It doesn't look like snapd currently supports [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) at least with v0.14.0-beta. This would be useful to allow javascript based tooling to interact with the snapd without needing to be on the same host or use a proxy layer.

Is this planned or are there any objections to adding CORS support?

**Comment by lynxbat** [comment]
This was on my list of concerns. In another internal project we started heavily using Beego and have been very pleased so I was debating moving the API to a Beego service and leveraging their CORS automated hooks: https://github.com/astaxie/beego/blob/master/plugins/cors/cors.go

Thoughts? @brharrington

**Comment by brharrington** [comment]
I'm not familiar with Beego, so I can't really offer an opinion on it overall. At first glance the CORS support looks like it would work for my needs.

**Comment by lynxbat** [comment]
@brharrington Thanks

We will track against this issue.

**Comment by lynxbat** [comment]
@bjray We need to capture this one in a spike next sprint.

**Comment by mjbrender** [comment]
Bump on this one - been too long since we talked whether we have time to do this cc @jcooklin

**Comment by candysmurf** [comment]
@mjbrender, as I'm working on Swagger doc for our APIs. I can submit a PR for it.

**Comment by mjbrender** [comment]
👏 👏 👏  @candysmurf
